/**
 * @generated by tools/gen-api.cjs
 *
 * 来源：server/openapi.json（由服务端代码生成） → 管理端接口文件：endpoints.ts
 * 重新生成：cd server && npm run gen:api
 * 一致性守卫：node tools/audit-api-generated.cjs（生成物落后于文档即 FAIL）
 *
 * ⚠️ 请勿手改：改接口请改服务端的 DTO / 控制器（含 operationId），再重新生成。
 */

import { http } from "./http";
import type { HttpOptions } from "./http";
import { routes } from "./routes";
import type { Account, AccountDetail, AccountPage, AccountQuery, AdminAuthResult, AdminInfo, AdminLogin, AdminPage, AdminQuery, AdminRegister, AdminRole, AdminRolePage, AdminStats, AdminUpdatePayload, Announcement, AnnouncementPage, AnnouncementQuery, AuditActionList, AuditExport, AuditLogPage, AuditQuery, BatchDeleteResult, BatchDeleteRoles, BatchStatusResult, BatchUpdateAccountStatus, ChangeAdminPassword, CreateAnnouncement, ResetAccountPassword, ResetAdminPassword, ResetPasswordResult, RolePatchPayload, RoleQuery, StatsBreakdown, StatsRecentItem, StatsRecentQuery, StatsTrend, StatsTrendQuery, SystemInfo, UpdateAccountStatus, UpdateAnnouncement } from "./models";

/**
 * 接口方法（管理端唯一调服务端的地方，自动生成，禁止手改）
 *
 * 路径来自 `./routes`（生成），类型来自 `./models`（生成）。
 * 页面只从 `./index` barrel import，不写路径、不拼令牌、不判状态码。
 */

/**
 * 请求选项：method / path / body 已由生成的方法填好，调用方只管 silent、timeout 之类的开关
 */
type Options = HttpOptions;

// 模型类型再导出一次：调用方 `import type { RoleSummary } from "./Api"` 这类既有写法仍然可用
export type { Account, AccountDetail, AccountPage, AccountQuery, ActiveAnnouncement, AdminAuthResult, AdminInfo, AdminLogin, AdminPage, AdminQuery, AdminRegister, AdminRole, AdminRolePage, AdminStats, AdminUpdatePayload, Announcement, AnnouncementPage, AnnouncementQuery, AuditActionList, AuditExport, AuditLog, AuditLogPage, AuditQuery, AuthResult, BatchDeleteResult, BatchDeleteRoles, BatchStatusResult, BatchUpdateAccountStatus, ChangeAdminPassword, CreateAnnouncement, CreateRole, Health, Login, PageMeta, PageQuery, Register, ResetAccountPassword, ResetAdminPassword, ResetPasswordResult, RoleBagCell, RoleDetail, RolePatchPayload, RoleQuery, RoleSummary, SaveRole, StatsBreakdown, StatsBreakdownItem, StatsRecentItem, StatsRecentQuery, StatsTrend, StatsTrendPoint, StatsTrendQuery, SystemConfigItem, SystemDatabase, SystemInfo, SystemRuntime, SystemTableCount, UpdateAccountStatus, UpdateAnnouncement } from "./models";

/** adminAccount 模块的接口（9 个，生成） */
export const accountsApi = {
  /**
   * 账号列表（GET /admin/accounts）
   *
   * keyword 模糊匹配账号名；status 可按状态筛选。
   *
   * 权限点：account:read
   */
  list: (query: AccountQuery = {}, options?: Options) => http.get<AccountPage>(routes.adminAccount.list, { query, ...options }),
  /**
   * 删除账号（DELETE /admin/accounts/{id}）
   *
   * 名下角色一并删除（外键级联），不可恢复。
   *
   * 权限点：account:delete
   */
  remove: (id: string, options?: Options) => http.del<null>(routes.adminAccount.remove(id), options),
  /**
   * 账号详情（GET /admin/accounts/{id}）
   *
   * 返回账号信息 + 名下角色概要列表。
   *
   * 权限点：account:read
   */
  detail: (id: string, options?: Options) => http.get<AccountDetail>(routes.adminAccount.detail(id), options),
  /**
   * 踢下线（清掉账号当前的在线角色）（POST /admin/accounts/{id}/offline）
   *
   * 幂等：本来就不在线时直接返回当前状态。
   *
   * 权限点：role:select
   */
  kick: (id: string, options?: Options) => http.post<Account>(routes.adminAccount.kick(id), undefined, options),
  /**
   * 重置玩家账号的密码（PATCH /admin/accounts/{id}/password）
   *
   * 玩家忘记密码时用这条（客户端没有找回流程）。
   *
   * 权限点：account:password
   */
  resetPassword: (id: string, body: ResetAccountPassword, options?: Options) => http.patch<ResetPasswordResult>(routes.adminAccount.resetPassword(id), body, options),
  /**
   * 清空账号下的全部角色（DELETE /admin/accounts/{id}/roles）
   *
   * 账号保留、名下角色全删（重置玩家存档用），不可恢复；作为在线角色的会顺带清掉在线标记。与「删除账号」的区别：账号本身还在，玩家可以重新创建角色。
   *
   * 权限点：role:delete
   */
  purgeRoles: (id: string, options?: Options) => http.del<BatchDeleteResult>(routes.adminAccount.purgeRoles(id), options),
  /**
   * 封禁 / 解封账号（PATCH /admin/accounts/{id}/status）
   *
   * 改完立刻生效：守卫每次请求都回查账号状态，在线的玩家下一次请求就被拒。
   *
   * 权限点：account:status
   */
  updateStatus: (id: string, body: UpdateAccountStatus, options?: Options) => http.patch<Account>(routes.adminAccount.updateStatus(id), body, options),
  /**
   * 批量封禁 / 解封账号（POST /admin/accounts/batch-status）
   *
   * 一次最多 100 个账号，字段与单条接口完全一致（原因 / 时长对封禁生效）。
   *
   * 权限点：account:status
   */
  batchStatus: (body: BatchUpdateAccountStatus, options?: Options) => http.post<BatchStatusResult>(routes.adminAccount.batchStatus, body, options),
  /**
   * 概览统计（GET /admin/stats）
   *
   * 账号 / 角色总量、今日新增、当前封禁中账号数、在线账号数、管理员数。
   *
   * 权限点：stats:read
   */
  stats: (options?: Options) => http.get<AdminStats>(routes.adminAccount.stats, options),
};

/** adminAdmin 模块的接口（4 个，生成） */
export const adminsApi = {
  /**
   * 管理员列表（GET /admin/admins）
   *
   * keyword 模糊匹配管理员账号名；role 可按角色筛选。
   *
   * 权限点：admin:read
   */
  list: (query: AdminQuery = {}, options?: Options) => http.get<AdminPage>(routes.adminAdmin.list, { query, ...options }),
  /**
   * 删除管理员（DELETE /admin/admins/{id}）
   *
   * 不可恢复；同样保护最后一个启用中的超级管理员。
   *
   * 权限点：admin:manage
   */
  remove: (id: string, options?: Options) => http.del<null>(routes.adminAdmin.remove(id), options),
  /**
   * 修改管理员（PATCH /admin/admins/{id}）
   *
   * 改角色或启停。允许改自己（超管轮值），但**最后一个启用中的超级管理员**不能被降级 / 停用 —— 避免没人能进后台。改完立即生效。
   *
   * 权限点：admin:manage
   */
  update: (id: string, body: AdminUpdatePayload, options?: Options) => http.patch<AdminInfo>(routes.adminAdmin.update(id), body, options),
  /**
   * 重置某个管理员的密码（PATCH /admin/admins/{id}/password）
   *
   * 只有超级管理员能做（`admin:manage`）—— 管理员之间不能互相改密码。
   *
   * 权限点：admin:manage
   */
  resetPassword: (id: string, body: ResetAdminPassword, options?: Options) => http.patch<ResetPasswordResult>(routes.adminAdmin.resetPassword(id), body, options),
};

/** adminAnnouncement 模块的接口（4 个，生成） */
export const announcementsApi = {
  /**
   * 公告列表（GET /admin/announcements）
   *
   * `keyword` 模糊匹配标题与正文；`level` / `enabled` / `active` 可筛。
   *
   * 权限点：announcement:read
   */
  list: (query: AnnouncementQuery = {}, options?: Options) => http.get<AnnouncementPage>(routes.adminAnnouncement.list, { query, ...options }),
  /**
   * 发布公告（POST /admin/announcements）
   *
   * 不传 `startsAt` = 立即生效，不传 `endsAt` = 不设截止（**不要**为了「长期有效」编一个很远的结束时间）。
   *
   * 权限点：announcement:write
   */
  create: (body: CreateAnnouncement, options?: Options) => http.post<Announcement>(routes.adminAnnouncement.create, body, options),
  /**
   * 删除公告（DELETE /admin/announcements/{id}）
   *
   * 不可恢复（**没有软删除**）：只是想让它不再对玩家展示，应当用「停用」或设置结束时间。
   *
   * 权限点：announcement:write
   */
  remove: (id: string, options?: Options) => http.del<null>(routes.adminAnnouncement.remove(id), options),
  /**
   * 编辑公告（PATCH /admin/announcements/{id}）
   *
   * **部分更新**：只改请求体里出现的字段 —— 列表上的「启用 / 停用」只传 `enabled` 即可，不会覆盖其它字段。
   *
   * 权限点：announcement:write
   */
  update: (id: string, body: UpdateAnnouncement, options?: Options) => http.patch<Announcement>(routes.adminAnnouncement.update(id), body, options),
};

/** adminAudit 模块的接口（3 个，生成） */
export const auditApi = {
  /**
   * 操作日志列表（GET /admin/audit-logs）
   *
   * 按时间倒序返回管理端的写操作记录（含登录成功 / 失败、改密码）。`keyword`（模糊匹配操作人账号名 / 动作 / 目标 id / 请求路径）、`actorId` / `action` / `targetType` / `targetId` / `success` / `from` / `to` 均可选，条件之间是「与」的关系。
   *
   * 权限点：audit:read
   */
  list: (query: AuditQuery = {}, options?: Options) => http.get<AuditLogPage>(routes.adminAudit.list, { query, ...options }),
  /**
   * 出现过的动作清单（GET /admin/audit-logs/actions）
   *
   * 返回日志里出现过的全部动作（接口标识），供界面的「动作」筛选下拉使用 —— 界面不写死动作清单。
   *
   * 权限点：audit:read
   */
  actions: (options?: Options) => http.get<AuditActionList>(routes.adminAudit.actions, options),
  /**
   * 导出操作日志（CSV）（GET /admin/audit-logs/export）
   *
   * 筛选条件与列表接口**完全一致**（含 `sort` / `order`，导出即「当前筛选下的全部」）；`page` / `size` 不生效 —— 条数上限取服务端配置 `AUDIT_EXPORT_MAX_ROWS`，超出时返回前 N 条并置 `truncated`。
   *
   * 权限点：audit:read
   */
  export: (query: AuditQuery = {}, options?: Options) => http.get<AuditExport>(routes.adminAudit.export, { query, ...options }),
};

/** adminAuth 模块的接口（4 个，生成） */
export const authApi = {
  /**
   * 管理员登录（POST /admin/auth/login）
   *
   * 成功后把返回的 token 放到 `Authorization: Bearer <token>`。
   */
  login: (body: AdminLogin, options?: Options) => http.post<AdminAuthResult>(routes.adminAuth.login, body, { auth: false, ...options }),
  /**
   * 获取当前登录管理员（GET /admin/auth/me）
   *
   * 返回当前管理员的角色与**权限点清单** —— 管理端据此显示 / 隐藏菜单与按钮（服务端仍会独立校验，前端隐藏只是体验）。
   */
  me: (options?: Options) => http.get<AdminInfo>(routes.adminAuth.me, options),
  /**
   * 修改自己的密码（PATCH /admin/auth/password）
   *
   * 任何已登录管理员都能改**自己**的密码，需要带上原密码（光有令牌不该能改口令）。
   */
  changePassword: (body: ChangeAdminPassword, options?: Options) => http.patch<AdminAuthResult>(routes.adminAuth.changePassword, body, options),
  /**
   * 注册管理员（POST /admin/auth/register）
   *
   * 注册许可由两件配置决定：配了 `ADMIN_REGISTER_CODE` 就必须带对注册码；没配则要求 `ADMIN_REGISTER_OPEN=true`（**默认关闭** —— 忘记配注册码不该等于人人可开后台）。**第一个**注册的管理员自动成为超级管理员，之后注册的一律是普通管理员。
   */
  register: (body: AdminRegister, options?: Options) => http.post<AdminAuthResult>(routes.adminAuth.register, body, { auth: false, ...options }),
};

/** adminRole 模块的接口（6 个，生成） */
export const rolesApi = {
  /**
   * 角色列表（GET /admin/roles）
   *
   * keyword 匹配角色名或角色 id；accountId 限定账号；online / occupation / sex / minLevel / maxLevel 做筛选。
   *
   * 权限点：role:read
   */
  list: (query: RoleQuery = {}, options?: Options) => http.get<AdminRolePage>(routes.adminRole.list, { query, ...options }),
  /**
   * 删除角色（DELETE /admin/roles/{id}）
   *
   * 不可恢复；是账号在线角色时一并清掉在线标记。
   *
   * 权限点：role:delete
   */
  remove: (id: string, options?: Options) => http.del<null>(routes.adminRole.remove(id), options),
  /**
   * 角色详情（GET /admin/roles/{id}）
   *
   * 含完整 data（背包 / 装备等原样返回）。
   *
   * 权限点：role:read
   */
  detail: (id: string, options?: Options) => http.get<AdminRole>(routes.adminRole.detail(id), options),
  /**
   * 修改角色（PATCH /admin/roles/{id}）
   *
   * 只提交要改的字段，其余原样保留。开放三类：**基础信息**（角色名 / 职业 / 性别 / 等级 / 时装 / 头像 / 所在地图）、**常用数值**（金币 / 绑定元宝 / 银两 / 经验 / 战魂 / 称号 / 军衔）、**运行时数据**（装备穿戴表 / 技能等级表 / 背包格子，结构化编辑，传 `bag: []` 即清空背包）。
   *
   * 权限点：role:write
   */
  patch: (id: string, body: RolePatchPayload, options?: Options) => http.patch<AdminRole>(routes.adminRole.patch(id), body, options),
  /**
   * 设为在线角色（POST /admin/roles/{id}/select）
   *
   * 把角色设为所属账号的在线角色（等价于玩家在选角界面选它进游戏）。
   *
   * 权限点：role:select
   */
  select: (id: string, options?: Options) => http.post<AdminRole>(routes.adminRole.select(id), undefined, options),
  /**
   * 批量删除角色（POST /admin/roles/batch-delete）
   *
   * 按 id 列表删除（最多 100 条）。已不存在的 id 静默跳过（幂等）；作为某个账号在线角色的会被顺带清掉在线标记。返回实际删除的条数与涉及的账号 id。
   *
   * 权限点：role:delete
   */
  batchRemove: (body: BatchDeleteRoles, options?: Options) => http.post<BatchDeleteResult>(routes.adminRole.batchRemove, body, options),
};

/** adminStats 模块的接口（3 个，生成） */
export const statsApi = {
  /**
   * 分布统计（GET /admin/stats/breakdown）
   *
   * 等级（10 级一档）/ 职业 / 性别 / 所在地图四组分布。
   *
   * 权限点：stats:read
   */
  breakdown: (options?: Options) => http.get<StatsBreakdown>(routes.adminStats.breakdown, options),
  /**
   * 最近动态（GET /admin/stats/recent）
   *
   * 最近若干条写操作（复用操作日志表），概览页用来看「刚才发生了什么」。不含请求体。
   *
   * 权限点：stats:read
   */
  recent: (query: StatsRecentQuery = {}, options?: Options) => http.get<StatsRecentItem[]>(routes.adminStats.recent, { query, ...options }),
  /**
   * 增长趋势（按天）（GET /admin/stats/trend）
   *
   * 返回最近 N 天的逐日新增账号与新增角色。**没有数据的日期也会返回（值为 0）** —— 前端可以直接画折线，不用自己补。日期按服务器本地时区。
   *
   * 权限点：stats:read
   */
  trend: (query: StatsTrendQuery = {}, options?: Options) => http.get<StatsTrend>(routes.adminStats.trend, { query, ...options }),
};

/** adminSystem 模块的接口（1 个，生成） */
export const systemApi = {
  /**
   * 系统信息（GET /admin/system）
   *
   * 版本 / Node 版本 / 运行时长 / 内存 / 数据文件路径与体积 / 各表行数 / 脱敏配置快照。
   *
   * 权限点：system:read
   */
  info: (options?: Options) => http.get<SystemInfo>(routes.adminSystem.info, options),
};
