/**
 * @generated by tools/gen-api.cjs
 *
 * 来源：server/openapi.json（由服务端代码生成） → 管理端接口文件：models.ts
 * 重新生成：cd server && npm run gen:api
 * 一致性守卫：node tools/audit-api-generated.cjs（生成物落后于文档即 FAIL）
 *
 * ⚠️ 请勿手改：改接口请改服务端的 DTO / 控制器（含 operationId），再重新生成。
 */

/**
 * 服务端 DTO 的镜像（自动生成，禁止手改）
 *
 * 字段与服务端 `@ApiProperty` 一一对应；这里的每一条都对应 OpenAPI 文档里的一个 schema。
 */

export type Register = {
  /**
   * 游戏账号：3~20 位字母 / 数字 / 下划线
   */
  username: string;
  /**
   * 密码：6~32 位
   */
  password: string;
};

export type Login = {
  /**
   * 游戏账号
   */
  username: string;
  /**
   * 密码
   */
  password: string;
};

export type CreateRole = {
  /**
   * 角色完整数据（客户端 entities/Role 的 JSON；必须含 id / name / occupation / sex / level）
   */
  data: Record<string, unknown>;
};

export type SaveRole = {
  /**
   * 角色完整数据（全量覆盖）
   */
  data: Record<string, unknown>;
  /**
   * 客户端读到的修订号（带上即开启乐观锁：与服务端不一致时返回 20006，需先拉最新数据）
   */
  revision?: number;
};

export type AdminRegister = {
  /**
   * 管理员账号：3~20 位字母 / 数字 / 下划线
   */
  username: string;
  /**
   * 密码：6~32 位
   */
  password: string;
  /**
   * 注册码（服务端配置了 ADMIN_REGISTER_CODE 时必填）
   */
  registerCode?: string;
};

export type AdminLogin = {
  /**
   * 管理员账号
   */
  username: string;
  /**
   * 密码
   */
  password: string;
};

export type ChangeAdminPassword = {
  /**
   * 当前密码
   */
  oldPassword: string;
  /**
   * 新密码（6~32 位）
   */
  newPassword: string;
};

export type UpdateAccountStatus = {
  /**
   * 目标状态：disabled 封禁 / active 解封（封禁四件套一并清空）
   */
  status?: "active" | "disabled";
  /**
   * 封禁原因：写进操作日志，也会出现在玩家登录被拒的提示里
   */
  reason?: string;
  /**
   * 封禁时长（小时）；不填或 null = 永久。仅在 status=disabled 时有意义
   */
  durationHours?: unknown | null;
};

export type ResetAccountPassword = {
  /**
   * 新密码（6~32 位）
   */
  password: string;
};

export type BatchDeleteRoles = {
  /**
   * 要删除的角色 id 列表（最多 100 条）
   */
  ids: string[];
};

export type RoleBagCell = {
  /**
   * 格子行号（0 ~ 63）
   */
  row: number;
  /**
   * 格子列号（0 ~ 63）
   */
  col: number;
  /**
   * 物品 id（客户端 configs/items 的 key）
   */
  id: string;
  /**
   * 数量
   */
  count: number;
};

export type RolePatchPayload = {
  /**
   * 角色名
   */
  name?: string;
  /**
   * 职业（1 战士 / 2 魔法师 / 3 道士 / 4 全职业）
   */
  occupation?: "1" | "2" | "3" | "4";
  /**
   * 性别（1 男 / 2 女 / 3 全性别）
   */
  sex?: "1" | "2" | "3";
  /**
   * 等级
   */
  level?: number;
  /**
   * 金币
   */
  gold?: number;
  /**
   * 绑定元宝
   */
  bindGold?: number;
  /**
   * 银两
   */
  silver?: number;
  /**
   * 经验
   */
  exp?: number;
  /**
   * 战魂等级
   */
  soulOfWar?: number;
  /**
   * 称号等级
   */
  title?: number;
  /**
   * 军衔阶数
   */
  rank?: number;
  /**
   * 时装（外观）id；null = 取消时装
   */
  fashionCloth?: number | null;
  /**
   * 头像编号
   */
  avatar?: number;
  /**
   * 所在地图 id（客户端 configs/map 的 key）
   */
  onMap?: string;
  /**
   * 装备穿戴表（槽位名 → 装备 id；null 或空串表示该槽位空着）
   */
  equipments?: Record<string, string | null>;
  /**
   * 技能等级表（技能 id → 等级）
   */
  skills?: Record<string, number>;
  /**
   * 背包格子（稀疏：行/列/物品 id/数量）；空数组 = 清空背包
   */
  bag?: RoleBagCell[];
};

export type AdminUpdatePayload = {
  /**
   * 目标角色
   */
  role?: "super_admin" | "admin" | "viewer";
  /**
   * 目标状态
   */
  status?: "active" | "disabled";
};

export type ResetAdminPassword = {
  /**
   * 新密码（6~32 位）
   */
  password: string;
};

export type PageMeta = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
};

export type PageQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字（不同接口含义见其说明）
   */
  keyword?: string;
};

export type Account = {
  /**
   * 账号 id
   */
  id: string;
  /**
   * 账号名
   */
  username: string;
  /**
   * 状态：active 正常 / disabled 封禁（临时封禁到期后由服务端扫回 active）
   */
  status: string;
  /**
   * 封禁原因（未封禁为 null）
   */
  banReason: string | null;
  /**
   * 封禁到期时间（毫秒）；null 表示未封禁或永久封禁
   */
  banUntil: number | null;
  /**
   * 执行封禁的管理员账号名（未封禁为 null）
   */
  bannedBy: string | null;
  /**
   * 封禁时间（毫秒；未封禁为 null）
   */
  bannedAt: number | null;
  /**
   * 当前选中的角色 id（未选角色时为 null）
   */
  onlineRoleId: string | null;
  /**
   * 角色数量（列表接口返回）
   */
  roleCount?: number;
  /**
   * 注册时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近更新时间（毫秒）
   */
  updatedAt: number;
  /**
   * 最近登录时间（毫秒，从未登录为 null）
   */
  lastLoginAt: number | null;
};

export type AuthResult = {
  /**
   * 访问令牌（放 Authorization: Bearer <token>）
   */
  token: string;
  /**
   * 令牌有效期（与 JWT_EXPIRES_IN 一致）
   */
  expiresIn: string;
  /**
   * 账号信息
   */
  account: Account;
};

export type RoleSummary = {
  /**
   * 角色 id
   */
  id: string;
  /**
   * 所属账号 id
   */
  accountId: string;
  /**
   * 角色名
   */
  name: string;
  /**
   * 职业：1 战士 / 2 魔法师 / 3 道士 / 4 全职业
   */
  occupation: string;
  /**
   * 性别：1 男 / 2 女 / 3 全性别
   */
  sex: string;
  /**
   * 等级
   */
  level: number;
  /**
   * 是否当前选中（在线）角色
   */
  online: boolean;
  /**
   * 修订号（每次落库 +1；客户端保存进度时带上它做乐观锁）
   */
  revision: number;
  /**
   * 创建时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近更新时间（毫秒）
   */
  updatedAt: number;
};

export type RoleDetail = {
  /**
   * 角色 id
   */
  id: string;
  /**
   * 所属账号 id
   */
  accountId: string;
  /**
   * 角色名
   */
  name: string;
  /**
   * 职业：1 战士 / 2 魔法师 / 3 道士 / 4 全职业
   */
  occupation: string;
  /**
   * 性别：1 男 / 2 女 / 3 全性别
   */
  sex: string;
  /**
   * 等级
   */
  level: number;
  /**
   * 是否当前选中（在线）角色
   */
  online: boolean;
  /**
   * 修订号（每次落库 +1；客户端保存进度时带上它做乐观锁）
   */
  revision: number;
  /**
   * 创建时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近更新时间（毫秒）
   */
  updatedAt: number;
  /**
   * 角色完整数据（客户端 entities/Role 的 JSON 快照，服务端按不透明文档存取；管理端只编辑其中的常用字段）
   */
  data: Record<string, unknown>;
};

export type AdminInfo = {
  /**
   * 管理员 id
   */
  id: string;
  /**
   * 管理员账号名
   */
  username: string;
  /**
   * 状态：active 正常 / disabled 停用
   */
  status: string;
  /**
   * 管理员角色：super_admin 超级管理员 / admin 管理员 / viewer 只读观察员
   */
  role: "super_admin" | "admin" | "viewer";
  /**
   * 角色中文名（界面直接展示）
   */
  roleLabel: string;
  /**
   * 该角色拥有的权限点（管理端据此显示 / 隐藏按钮；服务端仍会独立校验）
   */
  permissions: string[];
  /**
   * 创建时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近登录时间（毫秒，从未登录为 null）
   */
  lastLoginAt: number | null;
};

export type AdminAuthResult = {
  /**
   * 访问令牌（放 Authorization: Bearer <token>）
   */
  token: string;
  /**
   * 令牌有效期
   */
  expiresIn: string;
  /**
   * 管理员信息
   */
  admin: AdminInfo;
};

export type AccountDetail = {
  /**
   * 账号信息
   */
  account: Account;
  /**
   * 该账号的角色列表
   */
  roles: RoleSummary[];
};

export type AdminStats = {
  /**
   * 账号总数
   */
  accountCount: number;
  /**
   * 角色总数
   */
  roleCount: number;
  /**
   * 已选中在线角色的账号数
   */
  onlineAccountCount: number;
  /**
   * 今日新增账号数
   */
  todayNewAccountCount: number;
  /**
   * 管理员数量
   */
  adminCount: number;
};

export type AccountPage = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
  /**
   * 当前页的账号列表
   */
  list: Account[];
};

export type AdminPage = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
  /**
   * 当前页的管理员列表
   */
  list: AdminInfo[];
};

export type AdminRole = {
  /**
   * 角色 id
   */
  id: string;
  /**
   * 所属账号 id
   */
  accountId: string;
  /**
   * 角色名
   */
  name: string;
  /**
   * 职业：1 战士 / 2 魔法师 / 3 道士 / 4 全职业
   */
  occupation: string;
  /**
   * 性别：1 男 / 2 女 / 3 全性别
   */
  sex: string;
  /**
   * 等级
   */
  level: number;
  /**
   * 是否当前选中（在线）角色
   */
  online: boolean;
  /**
   * 修订号（每次落库 +1；客户端保存进度时带上它做乐观锁）
   */
  revision: number;
  /**
   * 创建时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近更新时间（毫秒）
   */
  updatedAt: number;
  /**
   * 角色完整数据（客户端 entities/Role 的 JSON 快照，服务端按不透明文档存取；管理端只编辑其中的常用字段）
   */
  data: Record<string, unknown>;
  /**
   * 所属账号名
   */
  accountName: string | null;
};

export type AdminRolePage = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
  /**
   * 当前页的角色列表
   */
  list: AdminRole[];
};

export type BatchDeleteResult = {
  /**
   * 请求删除的条数
   */
  requested: number;
  /**
   * 实际删除的条数（已不存在的 id 不计入）
   */
  deleted: number;
  /**
   * 实际被删掉的角色 id
   */
  ids: string[];
  /**
   * 被顺带清掉在线角色标记的账号 id（删的是在线角色时）
   */
  clearedOnlineAccountIds: string[];
};

export type ResetPasswordResult = {
  /**
   * 被重置的对象 id
   */
  id: string;
  /**
   * 被重置的对象名（账号名 / 管理员名，界面直接展示）
   */
  name: string;
  /**
   * 提示：口令变更后，该对象此前签发的令牌**已全部作废**，需要用它重新登录
   */
  revokedTokens?: boolean;
};

export type AuditLog = {
  /**
   * 日志 id
   */
  id: string;
  /**
   * 操作人管理员 id（匿名事件如登录失败为 null）
   */
  actorId: string | null;
  /**
   * 操作人账号名（冗余存下来，操作人被删后仍可追溯）
   */
  actorName: string | null;
  /**
   * 操作人角色（super_admin / admin / viewer）
   */
  actorRole: string | null;
  /**
   * 动作（即接口标识 operationId，如 adminRole.patch）
   */
  action: string;
  /**
   * 目标类型：account / role / admin
   */
  targetType: string | null;
  /**
   * 目标 id
   */
  targetId: string | null;
  /**
   * 目标**当前**的名字（按 targetType 关联出来；目标已删则为 null，界面退回显示 id）
   */
  targetName: string | null;
  /**
   * 附加上下文（请求体，已对 password / secret / token / code 一类字段打码；无则 null）
   */
  detail: Record<string, unknown> | null;
  /**
   * 来源 IP（反向代理下需 TRUST_PROXY=true 才准）
   */
  ip: string | null;
  /**
   * HTTP 方法
   */
  method: string | null;
  /**
   * 请求路径
   */
  path: string | null;
  /**
   * HTTP 状态码
   */
  statusCode: number | null;
  /**
   * 是否成功
   */
  success: boolean;
  /**
   * 失败时的业务码
   */
  errorCode: number | null;
  /**
   * 失败原因（可展示的中文）
   */
  errorMessage: string | null;
  /**
   * 发生时间（毫秒）
   */
  createdAt: number;
};

export type AuditLogPage = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
  /**
   * 当前页的操作日志
   */
  list: AuditLog[];
};

export type AuditActionList = {
  /**
   * 动作（operationId）列表
   */
  actions: string[];
};

export type AuditQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字：模糊匹配操作人账号名 / 动作（如 password）/ 目标 id / 请求路径
   */
  keyword?: string;
  /**
   * 只看某个操作人的日志（管理员 id）
   */
  actorId?: string;
  /**
   * 只看某个动作（operationId，取值见 /admin/audit-logs/actions）
   */
  action?: string;
  /**
   * 目标类型筛选
   */
  targetType?: "account" | "role" | "admin";
  /**
   * 只看针对某个目标的日志（目标 id）
   */
  targetId?: string;
  /**
   * 结果筛选：true 只看成功 / false 只看失败
   */
  success?: "true" | "false";
  /**
   * 起始时间（毫秒时间戳，含）
   */
  from?: number;
  /**
   * 结束时间（毫秒时间戳，含）
   */
  to?: number;
};

export type AccountQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字（不同接口含义见其说明）
   */
  keyword?: string;
  /**
   * 状态筛选
   */
  status?: "active" | "disabled";
};

export type RoleQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字（不同接口含义见其说明）
   */
  keyword?: string;
  /**
   * 限定账号 id（查某账号下的全部角色）
   */
  accountId?: string;
  /**
   * 在线状态筛选：true 只看在线（账号当前选中的）角色
   */
  online?: "true" | "false";
  /**
   * 职业筛选
   */
  occupation?: "1" | "2" | "3" | "4";
  /**
   * 性别筛选
   */
  sex?: "1" | "2" | "3";
  /**
   * 最低等级（含）
   */
  minLevel?: number;
  /**
   * 最高等级（含）
   */
  maxLevel?: number;
};

export type AdminQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字（不同接口含义见其说明）
   */
  keyword?: string;
  /**
   * 角色筛选
   */
  role?: "super_admin" | "admin" | "viewer";
};

export type Health = {
  /**
   * 服务状态
   */
  status: string;
  /**
   * 运行环境
   */
  env: string;
  /**
   * 服务端时间戳（毫秒）
   */
  time: number;
};
