/**
 * @generated by tools/gen-api.cjs
 *
 * 来源：server/openapi.json（由服务端代码生成） → 管理端接口文件：routes.ts
 * 重新生成：cd server && npm run gen:api
 * 一致性守卫：node tools/audit-api-generated.cjs（生成物落后于文档即 FAIL）
 *
 * ⚠️ 请勿手改：改接口请改服务端的 DTO / 控制器（含 operationId），再重新生成。
 */

/**
 * 路由表（管理端**唯一的接口路径来源**）
 *
 * 只登记路径，不带 host（host 在 `./config` 的 API_BASE_URL）；请求层拼装时统一加前缀。
 * 本文件由 `tools/gen-api.cjs` 从服务端 OpenAPI 文档生成，**禁止手改**
 * （守卫：`node tools/audit-api-generated.cjs`）。
 */
export const routes = {
  /** adminAccount 模块（8 个接口） */
  adminAccount: {
    /**
     * 账号列表（GET /admin/accounts）
     *
     * keyword 模糊匹配账号名；status 可按状态筛选。
     */
    list: "/admin/accounts",
    /**
     * 删除账号（DELETE /admin/accounts/{id}）
     *
     * 名下角色一并删除（外键级联），不可恢复。
     */
    remove: (id: string) => `/admin/accounts/${encodeURIComponent(id)}`,
    /**
     * 账号详情（GET /admin/accounts/{id}）
     *
     * 返回账号信息 + 名下角色概要列表。
     */
    detail: (id: string) => `/admin/accounts/${encodeURIComponent(id)}`,
    /**
     * 踢下线（清掉账号当前的在线角色）（POST /admin/accounts/{id}/offline）
     *
     * 幂等：本来就不在线时直接返回当前状态。
     */
    kick: (id: string) => `/admin/accounts/${encodeURIComponent(id)}/offline`,
    /**
     * 重置玩家账号的密码（PATCH /admin/accounts/{id}/password）
     *
     * 玩家忘记密码时用这条（客户端没有找回流程）。
     */
    resetPassword: (id: string) => `/admin/accounts/${encodeURIComponent(id)}/password`,
    /**
     * 清空账号下的全部角色（DELETE /admin/accounts/{id}/roles）
     *
     * 账号保留、名下角色全删（重置玩家存档用），不可恢复；作为在线角色的会顺带清掉在线标记。与「删除账号」的区别：账号本身还在，玩家可以重新创建角色。
     */
    purgeRoles: (id: string) => `/admin/accounts/${encodeURIComponent(id)}/roles`,
    /**
     * 封禁 / 解封账号（PATCH /admin/accounts/{id}/status）
     *
     * 改完立刻生效：守卫每次请求都回查账号状态，在线的玩家下一次请求就被拒。
     */
    updateStatus: (id: string) => `/admin/accounts/${encodeURIComponent(id)}/status`,
    /**
     * 概览统计（GET /admin/stats）
     *
     * 账号 / 角色总量、今日新增、当前封禁中账号数、在线账号数、管理员数。
     */
    stats: "/admin/stats",
  },
  /** adminAdmin 模块（4 个接口） */
  adminAdmin: {
    /**
     * 管理员列表（GET /admin/admins）
     *
     * keyword 模糊匹配管理员账号名；role 可按角色筛选。
     */
    list: "/admin/admins",
    /**
     * 删除管理员（DELETE /admin/admins/{id}）
     *
     * 不可恢复；同样保护最后一个启用中的超级管理员。
     */
    remove: (id: string) => `/admin/admins/${encodeURIComponent(id)}`,
    /**
     * 修改管理员（PATCH /admin/admins/{id}）
     *
     * 改角色或启停。允许改自己（超管轮值），但**最后一个启用中的超级管理员**不能被降级 / 停用 —— 避免没人能进后台。改完立即生效。
     */
    update: (id: string) => `/admin/admins/${encodeURIComponent(id)}`,
    /**
     * 重置某个管理员的密码（PATCH /admin/admins/{id}/password）
     *
     * 只有超级管理员能做（`admin:manage`）—— 管理员之间不能互相改密码。
     */
    resetPassword: (id: string) => `/admin/admins/${encodeURIComponent(id)}/password`,
  },
  /** adminAudit 模块（2 个接口） */
  adminAudit: {
    /**
     * 操作日志列表（GET /admin/audit-logs）
     *
     * 按时间倒序返回管理端的写操作记录（含登录成功 / 失败、改密码）。`keyword`（模糊匹配操作人账号名 / 动作 / 目标 id / 请求路径）、`actorId` / `action` / `targetType` / `targetId` / `success` / `from` / `to` 均可选，条件之间是「与」的关系。
     */
    list: "/admin/audit-logs",
    /**
     * 出现过的动作清单（GET /admin/audit-logs/actions）
     *
     * 返回日志里出现过的全部动作（接口标识），供界面的「动作」筛选下拉使用 —— 界面不写死动作清单。
     */
    actions: "/admin/audit-logs/actions",
  },
  /** adminAuth 模块（4 个接口） */
  adminAuth: {
    /**
     * 管理员登录（POST /admin/auth/login）
     *
     * 成功后把返回的 token 放到 `Authorization: Bearer <token>`。
     */
    login: "/admin/auth/login",
    /**
     * 获取当前登录管理员（GET /admin/auth/me）
     *
     * 返回当前管理员的角色与**权限点清单** —— 管理端据此显示 / 隐藏菜单与按钮（服务端仍会独立校验，前端隐藏只是体验）。
     */
    me: "/admin/auth/me",
    /**
     * 修改自己的密码（PATCH /admin/auth/password）
     *
     * 任何已登录管理员都能改**自己**的密码，需要带上原密码（光有令牌不该能改口令）。
     */
    changePassword: "/admin/auth/password",
    /**
     * 注册管理员（POST /admin/auth/register）
     *
     * 服务端配置了 `ADMIN_REGISTER_CODE` 时，registerCode 必须一致，否则拒绝注册。**第一个**注册的管理员自动成为超级管理员，之后注册的一律是普通管理员。
     */
    register: "/admin/auth/register",
  },
  /** adminRole 模块（6 个接口） */
  adminRole: {
    /**
     * 角色列表（GET /admin/roles）
     *
     * keyword 匹配角色名或角色 id；accountId 限定账号；online / occupation / sex / minLevel / maxLevel 做筛选。
     */
    list: "/admin/roles",
    /**
     * 删除角色（DELETE /admin/roles/{id}）
     *
     * 不可恢复；是账号在线角色时一并清掉在线标记。
     */
    remove: (id: string) => `/admin/roles/${encodeURIComponent(id)}`,
    /**
     * 角色详情（GET /admin/roles/{id}）
     *
     * 含完整 data（背包 / 装备等原样返回）。
     */
    detail: (id: string) => `/admin/roles/${encodeURIComponent(id)}`,
    /**
     * 修改角色（PATCH /admin/roles/{id}）
     *
     * 只提交要改的字段，其余原样保留。开放三类：**基础信息**（角色名 / 职业 / 性别 / 等级 / 时装 / 头像 / 所在地图）、**常用数值**（金币 / 绑定元宝 / 银两 / 经验 / 战魂 / 称号 / 军衔）、**运行时数据**（装备穿戴表 / 技能等级表 / 背包格子，结构化编辑，传 `bag: []` 即清空背包）。
     */
    patch: (id: string) => `/admin/roles/${encodeURIComponent(id)}`,
    /**
     * 设为在线角色（POST /admin/roles/{id}/select）
     *
     * 把角色设为所属账号的在线角色（等价于玩家在选角界面选它进游戏）。
     */
    select: (id: string) => `/admin/roles/${encodeURIComponent(id)}/select`,
    /**
     * 批量删除角色（POST /admin/roles/batch-delete）
     *
     * 按 id 列表删除（最多 100 条）。已不存在的 id 静默跳过（幂等）；作为某个账号在线角色的会被顺带清掉在线标记。返回实际删除的条数与涉及的账号 id。
     */
    batchRemove: "/admin/roles/batch-delete",
  },
  /** adminStats 模块（3 个接口） */
  adminStats: {
    /**
     * 分布统计（GET /admin/stats/breakdown）
     *
     * 等级（10 级一档）/ 职业 / 性别 / 所在地图四组分布。
     */
    breakdown: "/admin/stats/breakdown",
    /**
     * 最近动态（GET /admin/stats/recent）
     *
     * 最近若干条写操作（复用操作日志表），概览页用来看「刚才发生了什么」。不含请求体。
     */
    recent: "/admin/stats/recent",
    /**
     * 增长趋势（按天）（GET /admin/stats/trend）
     *
     * 返回最近 N 天的逐日新增账号与新增角色。**没有数据的日期也会返回（值为 0）** —— 前端可以直接画折线，不用自己补。日期按服务器本地时区。
     */
    trend: "/admin/stats/trend",
  },
} as const;
