/**
 * @generated by tools/gen-api.cjs
 *
 * 来源：server/openapi.json（由服务端代码生成） → 客户端接口文件：ApiRoutes.ts
 * 重新生成：cd server && npm run gen:api
 * 一致性守卫：node tools/audit-api-generated.cjs（生成物落后于文档即 FAIL）
 *
 * ⚠️ 请勿手改：改接口请改服务端的 DTO / 控制器（含 operationId），再重新生成。
 */

/**
 * 路由表（客户端**唯一的接口路径来源**）
 *
 * 只登记路径，不带 host（host 在 configs/network）；请求层拼装时统一加前缀。
 * 本文件由 `tools/gen-api.cjs` 从服务端 OpenAPI 文档生成，**禁止手改**
 * （守卫：`node tools/audit-api-generated.cjs`）。
 */
export const ApiRoutes = {
  /** auth 模块（3 个接口） */
  auth: {
    /**
     * 账号登录（POST /auth/login）
     *
     * 账号不存在与密码错误返回同一句提示（不暴露账号是否存在）。
     */
    login: "/auth/login",
    /**
     * 获取当前登录账号（GET /auth/me）
     *
     * 用令牌里的账号 id 查，不接受任何入参指定账号。
     */
    me: "/auth/me",
    /**
     * 注册账号（POST /auth/register）
     *
     * 账号名唯一；注册成功直接返回令牌，无需再登录一次。
     */
    register: "/auth/register",
  },
  /** health 模块（1 个接口） */
  health: {
    /**
     * 健康检查（GET /health）
     *
     * 无需登录；用于客户端 / 管理端确认服务端可达。
     */
    check: "/health",
  },
  /** role 模块（7 个接口） */
  role: {
    /**
     * 角色列表（GET /roles）
     *
     * 按创建时间升序；不含 data（选角列表用）。
     */
    list: "/roles",
    /**
     * 创建角色（POST /roles）
     *
     * data 由客户端按自身配置生成；服务端校验结构、索引字段、数量上限与重名。第一个角色自动设为在线。
     */
    create: "/roles",
    /**
     * 删除角色（DELETE /roles/{id}）
     *
     * 不可恢复；删的正好是在线角色时同时清掉在线标记。
     */
    remove: (id: string) => `/roles/${encodeURIComponent(id)}`,
    /**
     * 角色详情（GET /roles/{id}）
     *
     * 只能查自己账号下的角色（否则 403）。
     */
    detail: (id: string) => `/roles/${encodeURIComponent(id)}`,
    /**
     * 保存角色进度（PUT /roles/{id}）
     *
     * 全量覆盖 data；id 以路径为准（请求体里的 id 会被忽略）。
     */
    save: (id: string) => `/roles/${encodeURIComponent(id)}`,
    /**
     * 选中（进入）角色（POST /roles/{id}/select）
     *
     * 把该角色设为账号的在线角色。
     */
    select: (id: string) => `/roles/${encodeURIComponent(id)}/select`,
    /**
     * 当前在线角色（GET /roles/online）
     *
     * 未选角色 / 在线角色已删时返回 null。
     */
    online: "/roles/online",
  },
} as const;
