/**
 * @generated by tools/gen-api.cjs
 *
 * 来源：server/openapi.json（由服务端代码生成） → 客户端接口文件：Api.ts
 * 重新生成：cd server && npm run gen:api
 * 一致性守卫：node tools/audit-api-generated.cjs（生成物落后于文档即 FAIL）
 *
 * ⚠️ 请勿手改：改接口请改服务端的 DTO / 控制器（含 operationId），再重新生成。
 */

import HttpClient from "./HttpClient";
import type { RequestOptions } from "./HttpClient";
import { ApiRoutes } from "./ApiRoutes";
import type { Account, AuthResult, CreateRole, Health, Login, Register, RoleDetail, RoleSummary, SaveRole } from "./ApiModels";

/**
 * 客户端接口（自动生成，禁止手改）
 *
 * 路径来自 `./ApiRoutes`（生成），类型来自 `./ApiModels`（生成）。
 * 业务层只调这里，不写路径、不拼令牌、不判状态码 —— 那些都在 `./HttpClient` 里统一处理。
 * 令牌失效时 HttpClient 会回调入口注册的处理，见 `ui/Game.ts`。
 */

/**
 * 请求选项：method / path / body 已由生成的方法填好，调用方只管 silent、timeout 之类的开关
 */
type Options = Omit<RequestOptions, "method" | "path" | "body">;

// 模型类型再导出一次：调用方 `import type { RoleSummary } from "./Api"` 这类既有写法仍然可用
export type { Account, AccountDetail, AccountPage, AccountQuery, AdminAuthResult, AdminInfo, AdminLogin, AdminPage, AdminQuery, AdminRegister, AdminRole, AdminRolePage, AdminStats, AdminUpdatePayload, AuditActionList, AuditExport, AuditLog, AuditLogPage, AuditQuery, AuthResult, BatchDeleteResult, BatchDeleteRoles, BatchStatusResult, BatchUpdateAccountStatus, ChangeAdminPassword, CreateRole, Health, Login, PageMeta, PageQuery, Register, ResetAccountPassword, ResetAdminPassword, ResetPasswordResult, RoleBagCell, RoleDetail, RolePatchPayload, RoleQuery, RoleSummary, SaveRole, StatsBreakdown, StatsBreakdownItem, StatsRecentItem, StatsRecentQuery, StatsTrend, StatsTrendPoint, StatsTrendQuery, UpdateAccountStatus } from "./ApiModels";

/** auth 模块的接口（3 个，生成） */
export const AuthApi = {
  /**
   * 账号登录（POST /auth/login）
   *
   * 账号不存在与密码错误返回同一句提示（不暴露账号是否存在）。
   */
  login: (body: Login, options?: Options) => HttpClient.post<AuthResult>(ApiRoutes.auth.login, body, { auth: false, ...options }),
  /**
   * 获取当前登录账号（GET /auth/me）
   *
   * 用令牌里的账号 id 查，不接受任何入参指定账号。
   */
  me: (options?: Options) => HttpClient.get<Account>(ApiRoutes.auth.me, options),
  /**
   * 注册账号（POST /auth/register）
   *
   * 账号名唯一；注册成功直接返回令牌，无需再登录一次。
   */
  register: (body: Register, options?: Options) => HttpClient.post<AuthResult>(ApiRoutes.auth.register, body, { auth: false, ...options }),
};

/** health 模块的接口（1 个，生成） */
export const HealthApi = {
  /**
   * 健康检查（GET /health）
   *
   * 无需登录；用于客户端 / 管理端确认服务端可达。
   */
  check: (options?: Options) => HttpClient.get<Health>(ApiRoutes.health.check, { auth: false, ...options }),
};

/** role 模块的接口（7 个，生成） */
export const RoleApi = {
  /**
   * 角色列表（GET /roles）
   *
   * 按创建时间升序；不含 data（选角列表用）。
   */
  list: (options?: Options) => HttpClient.get<RoleSummary[]>(ApiRoutes.role.list, options),
  /**
   * 创建角色（POST /roles）
   *
   * data 由客户端按自身配置生成；服务端校验结构、索引字段、数量上限与重名。第一个角色自动设为在线。
   */
  create: (body: CreateRole, options?: Options) => HttpClient.post<RoleDetail>(ApiRoutes.role.create, body, options),
  /**
   * 删除角色（DELETE /roles/{id}）
   *
   * 不可恢复；删的正好是在线角色时同时清掉在线标记。
   */
  remove: (id: string, options?: Options) => HttpClient.del<null>(ApiRoutes.role.remove(id), options),
  /**
   * 角色详情（GET /roles/{id}）
   *
   * 只能查自己账号下的角色（否则 403）。
   */
  detail: (id: string, options?: Options) => HttpClient.get<RoleDetail>(ApiRoutes.role.detail(id), options),
  /**
   * 保存角色进度（PUT /roles/{id}）
   *
   * 全量覆盖 data；id 以路径为准（请求体里的 id 会被忽略）。
   */
  save: (id: string, body: SaveRole, options?: Options) => HttpClient.put<RoleDetail>(ApiRoutes.role.save(id), body, options),
  /**
   * 选中（进入）角色（POST /roles/{id}/select）
   *
   * 把该角色设为账号的在线角色。
   */
  select: (id: string, options?: Options) => HttpClient.post<RoleDetail>(ApiRoutes.role.select(id), undefined, options),
  /**
   * 当前在线角色（GET /roles/online）
   *
   * 未选角色 / 在线角色已删时返回 null。
   */
  online: (options?: Options) => HttpClient.get<RoleDetail | null>(ApiRoutes.role.online, options),
};
