/**
 * @generated by tools/gen-api.cjs
 *
 * 来源：server/openapi.json（由服务端代码生成） → 客户端接口文件：ApiModels.ts
 * 重新生成：cd server && npm run gen:api
 * 一致性守卫：node tools/audit-api-generated.cjs（生成物落后于文档即 FAIL）
 *
 * ⚠️ 请勿手改：改接口请改服务端的 DTO / 控制器（含 operationId），再重新生成。
 */

/**
 * 服务端 DTO 的镜像（自动生成，禁止手改）
 *
 * 字段与服务端 `@ApiProperty` 一一对应；这里的每一条都对应 OpenAPI 文档里的一个 schema。
 */

export type Register = {
  /**
   * 游戏账号：3~20 位字母 / 数字 / 下划线
   */
  username: string;
  /**
   * 密码：6~32 位
   */
  password: string;
};

export type Login = {
  /**
   * 游戏账号
   */
  username: string;
  /**
   * 密码
   */
  password: string;
};

export type CreateRole = {
  /**
   * 角色完整数据（客户端 entities/Role 的 JSON；必须含 id / name / occupation / sex / level）
   */
  data: Record<string, unknown>;
};

export type SaveRole = {
  /**
   * 角色完整数据（全量覆盖）
   */
  data: Record<string, unknown>;
  /**
   * 客户端读到的修订号（带上即开启乐观锁：与服务端不一致时返回 20006，需先拉最新数据）
   */
  revision?: number;
};

export type AdminRegister = {
  /**
   * 管理员账号：3~20 位字母 / 数字 / 下划线
   */
  username: string;
  /**
   * 密码：6~32 位
   */
  password: string;
  /**
   * 注册码（服务端配置了 ADMIN_REGISTER_CODE 时必填；未配置且未开 ADMIN_REGISTER_OPEN 时，管理端注册整体关闭）
   */
  registerCode?: string;
};

export type AdminLogin = {
  /**
   * 管理员账号
   */
  username: string;
  /**
   * 密码
   */
  password: string;
};

export type ChangeAdminPassword = {
  /**
   * 当前密码
   */
  oldPassword: string;
  /**
   * 新密码（6~32 位）
   */
  newPassword: string;
};

export type UpdateAccountStatus = {
  /**
   * 目标状态：disabled 封禁 / active 解封（封禁四件套一并清空）
   */
  status?: "active" | "disabled";
  /**
   * 封禁原因：写进操作日志，也会出现在玩家登录被拒的提示里
   */
  reason?: string;
  /**
   * 封禁时长（小时）；不填或 null = 永久。仅在 status=disabled 时有意义
   */
  durationHours?: unknown | null;
};

export type BatchUpdateAccountStatus = {
  /**
   * 目标状态：disabled 封禁 / active 解封（封禁四件套一并清空）
   */
  status?: "active" | "disabled";
  /**
   * 封禁原因：写进操作日志，也会出现在玩家登录被拒的提示里
   */
  reason?: string;
  /**
   * 封禁时长（小时）；不填或 null = 永久。仅在 status=disabled 时有意义
   */
  durationHours?: unknown | null;
  /**
   * 要变更的账号 id 列表（最多 100 条）
   */
  ids: string[];
};

export type ResetAccountPassword = {
  /**
   * 新密码（6~32 位）
   */
  password: string;
};

export type BatchDeleteRoles = {
  /**
   * 要删除的角色 id 列表（最多 100 条）
   */
  ids: string[];
};

export type RoleBagCell = {
  /**
   * 格子行号（0 ~ 63）
   */
  row: number;
  /**
   * 格子列号（0 ~ 63）
   */
  col: number;
  /**
   * 物品 id（客户端 configs/items 的 key）
   */
  id: string;
  /**
   * 数量
   */
  count: number;
};

export type RolePatchPayload = {
  /**
   * 角色名
   */
  name?: string;
  /**
   * 职业（1 战士 / 2 魔法师 / 3 道士 / 4 全职业）
   */
  occupation?: "1" | "2" | "3" | "4";
  /**
   * 性别（1 男 / 2 女 / 3 全性别）
   */
  sex?: "1" | "2" | "3";
  /**
   * 等级
   */
  level?: number;
  /**
   * 金币
   */
  gold?: number;
  /**
   * 绑定元宝
   */
  bindGold?: number;
  /**
   * 银两
   */
  silver?: number;
  /**
   * 经验
   */
  exp?: number;
  /**
   * 战魂等级
   */
  soulOfWar?: number;
  /**
   * 称号等级
   */
  title?: number;
  /**
   * 军衔阶数
   */
  rank?: number;
  /**
   * 时装（外观）id；null = 取消时装
   */
  fashionCloth?: number | null;
  /**
   * 头像编号
   */
  avatar?: number;
  /**
   * 所在地图 id（客户端 configs/map 的 key）
   */
  onMap?: string;
  /**
   * 装备穿戴表（槽位名 → 装备 id；null 或空串表示该槽位空着）
   */
  equipments?: Record<string, string | null>;
  /**
   * 技能等级表（技能 id → 等级）
   */
  skills?: Record<string, number>;
  /**
   * 背包格子（稀疏：行/列/物品 id/数量）；空数组 = 清空背包
   */
  bag?: RoleBagCell[];
};

export type AdminUpdatePayload = {
  /**
   * 目标角色
   */
  role?: "super_admin" | "admin" | "viewer";
  /**
   * 目标状态
   */
  status?: "active" | "disabled";
};

export type ResetAdminPassword = {
  /**
   * 新密码（6~32 位）
   */
  password: string;
};

export type CreateAnnouncement = {
  /**
   * 标题
   */
  title: string;
  /**
   * 正文（纯文本）
   */
  content: string;
  /**
   * 级别，默认 normal
   */
  level?: "normal" | "important";
  /**
   * 是否启用，默认 true
   */
  enabled?: boolean;
  /**
   * 生效开始时间（毫秒时间戳）；不传 = 立即生效
   */
  startsAt?: number;
  /**
   * 生效结束时间（毫秒时间戳，不含）；不传 = 不设截止
   */
  endsAt?: number;
};

export type UpdateAnnouncement = {
  /**
   * 标题（不传则不改）
   */
  title?: string;
  /**
   * 正文（不传则不改）
   */
  content?: string;
  /**
   * 级别（不传则不改）
   */
  level?: "normal" | "important";
  /**
   * 启用 / 停用（不传则不改）
   */
  enabled?: boolean;
  /**
   * 生效开始时间（毫秒）；传 `null` = 改为立即生效，不传则不改
   */
  startsAt?: number | null;
  /**
   * 生效结束时间（毫秒，不含）；传 `null` = 改为不设截止，不传则不改
   */
  endsAt?: number | null;
};

export type SendMail = {
  /**
   * 收件邮箱
   */
  to: string;
  /**
   * 模板 key（custom = 自定义，此时必须传 subject 与 body）
   */
  templateKey: "welcome" | "banNotice" | "maintenance" | "custom";
  /**
   * 关联的玩家账号 id（可选，仅用于追溯）
   */
  accountId?: string;
  /**
   * 模板变量（键是模板声明的变量名，如 username / reason）；缺必填变量会直接拒发
   */
  variables?: Record<string, string>;
  /**
   * 自定义标题（**仅 custom 模板必填**）
   */
  subject?: string;
  /**
   * 自定义正文（**仅 custom 模板必填**，纯文本）
   */
  body?: string;
};

export type PageMeta = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
};

export type PageQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字（不同接口含义见其说明）
   */
  keyword?: string;
  /**
   * 排序字段（取值见各接口说明，未登记的值会退回默认排序）
   */
  sort?: string;
  /**
   * 排序方向：asc 升序 / desc 降序
   */
  order?: "asc" | "desc";
};

export type Account = {
  /**
   * 账号 id
   */
  id: string;
  /**
   * 账号名
   */
  username: string;
  /**
   * 状态：active 正常 / disabled 封禁（临时封禁到期后由服务端扫回 active）
   */
  status: string;
  /**
   * 封禁原因（未封禁为 null）
   */
  banReason: string | null;
  /**
   * 封禁到期时间（毫秒）；null 表示未封禁或永久封禁
   */
  banUntil: number | null;
  /**
   * 执行封禁的管理员账号名（未封禁为 null）
   */
  bannedBy: string | null;
  /**
   * 封禁时间（毫秒；未封禁为 null）
   */
  bannedAt: number | null;
  /**
   * 当前选中的角色 id（未选角色时为 null）
   */
  onlineRoleId: string | null;
  /**
   * 角色数量（列表接口返回）
   */
  roleCount?: number;
  /**
   * 注册时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近更新时间（毫秒）
   */
  updatedAt: number;
  /**
   * 最近登录时间（毫秒，从未登录为 null）
   */
  lastLoginAt: number | null;
};

export type AuthResult = {
  /**
   * 访问令牌（放 Authorization: Bearer <token>）
   */
  token: string;
  /**
   * 令牌有效期（与 JWT_EXPIRES_IN 一致）
   */
  expiresIn: string;
  /**
   * 账号信息
   */
  account: Account;
};

export type RoleSummary = {
  /**
   * 角色 id
   */
  id: string;
  /**
   * 所属账号 id
   */
  accountId: string;
  /**
   * 角色名
   */
  name: string;
  /**
   * 职业：1 战士 / 2 魔法师 / 3 道士 / 4 全职业
   */
  occupation: string;
  /**
   * 性别：1 男 / 2 女 / 3 全性别
   */
  sex: string;
  /**
   * 等级
   */
  level: number;
  /**
   * 是否当前选中（在线）角色
   */
  online: boolean;
  /**
   * 修订号（每次落库 +1；客户端保存进度时带上它做乐观锁）
   */
  revision: number;
  /**
   * 创建时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近更新时间（毫秒）
   */
  updatedAt: number;
};

export type RoleDetail = {
  /**
   * 角色 id
   */
  id: string;
  /**
   * 所属账号 id
   */
  accountId: string;
  /**
   * 角色名
   */
  name: string;
  /**
   * 职业：1 战士 / 2 魔法师 / 3 道士 / 4 全职业
   */
  occupation: string;
  /**
   * 性别：1 男 / 2 女 / 3 全性别
   */
  sex: string;
  /**
   * 等级
   */
  level: number;
  /**
   * 是否当前选中（在线）角色
   */
  online: boolean;
  /**
   * 修订号（每次落库 +1；客户端保存进度时带上它做乐观锁）
   */
  revision: number;
  /**
   * 创建时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近更新时间（毫秒）
   */
  updatedAt: number;
  /**
   * 角色完整数据（客户端 entities/Role 的 JSON 快照，服务端按不透明文档存取；管理端只编辑其中的常用字段）
   */
  data: Record<string, unknown>;
};

export type AdminInfo = {
  /**
   * 管理员 id
   */
  id: string;
  /**
   * 管理员账号名
   */
  username: string;
  /**
   * 状态：active 正常 / disabled 停用
   */
  status: string;
  /**
   * 管理员角色：super_admin 超级管理员 / admin 管理员 / viewer 只读观察员
   */
  role: "super_admin" | "admin" | "viewer";
  /**
   * 角色中文名（界面直接展示）
   */
  roleLabel: string;
  /**
   * 该角色拥有的权限点（管理端据此显示 / 隐藏按钮；服务端仍会独立校验）
   */
  permissions: string[];
  /**
   * 创建时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近登录时间（毫秒，从未登录为 null）
   */
  lastLoginAt: number | null;
};

export type AdminAuthResult = {
  /**
   * 访问令牌（放 Authorization: Bearer <token>）
   */
  token: string;
  /**
   * 令牌有效期
   */
  expiresIn: string;
  /**
   * 管理员信息
   */
  admin: AdminInfo;
};

export type AccountDetail = {
  /**
   * 账号信息
   */
  account: Account;
  /**
   * 该账号的角色列表
   */
  roles: RoleSummary[];
};

export type AdminStats = {
  /**
   * 账号总数
   */
  accountCount: number;
  /**
   * 角色总数
   */
  roleCount: number;
  /**
   * 已选中在线角色的账号数
   */
  onlineAccountCount: number;
  /**
   * 今日新增账号数
   */
  todayNewAccountCount: number;
  /**
   * 今日新增角色数
   */
  todayNewRoleCount: number;
  /**
   * 当前封禁中的账号数（永久封禁与未到期的临时封禁都算）
   */
  bannedAccountCount: number;
  /**
   * 管理员数量
   */
  adminCount: number;
};

export type StatsTrendPoint = {
  /**
   * 日期（服务器本地时区，YYYY-MM-DD）
   */
  day: string;
  /**
   * 当日新增账号数
   */
  newAccounts: number;
  /**
   * 当日新增角色数
   */
  newRoles: number;
};

export type StatsTrend = {
  /**
   * 统计天数
   */
  days: number;
  /**
   * 逐日数据（含没有数据的日期，值为 0）
   */
  points: StatsTrendPoint[];
  /**
   * 区间内新增账号合计
   */
  totalNewAccounts: number;
  /**
   * 区间内新增角色合计
   */
  totalNewRoles: number;
};

export type StatsBreakdownItem = {
  /**
   * 分组键（等级档起点 / 职业 id / 性别 id / 地图 id；空串表示未知）
   */
  key: string;
  /**
   * 数量
   */
  count: number;
};

export type StatsBreakdown = {
  /**
   * 等级分布（10 级一档，key 为区间起点）
   */
  levels: StatsBreakdownItem[];
  /**
   * 职业分布（key 为职业 id）
   */
  occupations: StatsBreakdownItem[];
  /**
   * 性别分布（key 为性别 id）
   */
  sexes: StatsBreakdownItem[];
  /**
   * 所在地图分布（key 为角色快照里的 onMap）
   */
  maps: StatsBreakdownItem[];
};

export type StatsRecentItem = {
  /**
   * 操作时间（毫秒）
   */
  createdAt: number;
  /**
   * 操作人账号名（系统事件为 null）
   */
  actorName: string | null;
  /**
   * 动作（即接口的 operationId）
   */
  action: string;
  /**
   * 目标类型：account | role | admin
   */
  targetType: string | null;
  /**
   * 目标 id
   */
  targetId: string | null;
  /**
   * 是否成功
   */
  success: boolean;
};

export type StatsTrendQuery = {
  /**
   * 统计天数（含今天），最多 90 天
   */
  days?: number;
};

export type StatsRecentQuery = {
  /**
   * 取多少条
   */
  limit?: number;
};

export type AccountPage = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
  /**
   * 当前页的账号列表
   */
  list: Account[];
};

export type AdminPage = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
  /**
   * 当前页的管理员列表
   */
  list: AdminInfo[];
};

export type AdminRole = {
  /**
   * 角色 id
   */
  id: string;
  /**
   * 所属账号 id
   */
  accountId: string;
  /**
   * 角色名
   */
  name: string;
  /**
   * 职业：1 战士 / 2 魔法师 / 3 道士 / 4 全职业
   */
  occupation: string;
  /**
   * 性别：1 男 / 2 女 / 3 全性别
   */
  sex: string;
  /**
   * 等级
   */
  level: number;
  /**
   * 是否当前选中（在线）角色
   */
  online: boolean;
  /**
   * 修订号（每次落库 +1；客户端保存进度时带上它做乐观锁）
   */
  revision: number;
  /**
   * 创建时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近更新时间（毫秒）
   */
  updatedAt: number;
  /**
   * 角色完整数据（客户端 entities/Role 的 JSON 快照，服务端按不透明文档存取；管理端只编辑其中的常用字段）
   */
  data: Record<string, unknown>;
  /**
   * 所属账号名
   */
  accountName: string | null;
};

export type AdminRolePage = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
  /**
   * 当前页的角色列表
   */
  list: AdminRole[];
};

export type BatchDeleteResult = {
  /**
   * 请求删除的条数
   */
  requested: number;
  /**
   * 实际删除的条数（已不存在的 id 不计入）
   */
  deleted: number;
  /**
   * 实际被删掉的角色 id
   */
  ids: string[];
  /**
   * 被顺带清掉在线角色标记的账号 id（删的是在线角色时）
   */
  clearedOnlineAccountIds: string[];
};

export type BatchStatusResult = {
  /**
   * 请求操作的条数（含重复提交的 id）
   */
  requested: number;
  /**
   * 实际改到的条数（已不存在的 id 不计入）
   */
  updated: number;
  /**
   * 实际改到的账号 id
   */
  ids: string[];
  /**
   * 因本次封禁被清掉在线角色的账号 id（解封时为空）
   */
  clearedOnlineAccountIds: string[];
};

export type ResetPasswordResult = {
  /**
   * 被重置的对象 id
   */
  id: string;
  /**
   * 被重置的对象名（账号名 / 管理员名，界面直接展示）
   */
  name: string;
  /**
   * 提示：口令变更后，该对象此前签发的令牌**已全部作废**，需要用它重新登录
   */
  revokedTokens?: boolean;
};

export type AuditLog = {
  /**
   * 日志 id
   */
  id: string;
  /**
   * 操作人管理员 id（匿名事件如登录失败为 null）
   */
  actorId: string | null;
  /**
   * 操作人账号名（冗余存下来，操作人被删后仍可追溯）
   */
  actorName: string | null;
  /**
   * 操作人角色（super_admin / admin / viewer）
   */
  actorRole: string | null;
  /**
   * 动作（即接口标识 operationId，如 adminRole.patch）
   */
  action: string;
  /**
   * 目标类型：account / role / admin / announcement / mail
   */
  targetType: string | null;
  /**
   * 目标 id
   */
  targetId: string | null;
  /**
   * 目标**当前**的名字（按 targetType 关联出来；目标已删则为 null，界面退回显示 id）
   */
  targetName: string | null;
  /**
   * 附加上下文（请求体，已对 password / secret / token / code 一类字段打码；无则 null）
   */
  detail: Record<string, unknown> | null;
  /**
   * 来源 IP（反向代理下需 TRUST_PROXY=true 才准）
   */
  ip: string | null;
  /**
   * HTTP 方法
   */
  method: string | null;
  /**
   * 请求路径
   */
  path: string | null;
  /**
   * HTTP 状态码
   */
  statusCode: number | null;
  /**
   * 是否成功
   */
  success: boolean;
  /**
   * 失败时的业务码
   */
  errorCode: number | null;
  /**
   * 失败原因（可展示的中文）
   */
  errorMessage: string | null;
  /**
   * 发生时间（毫秒）
   */
  createdAt: number;
};

export type AuditLogPage = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
  /**
   * 当前页的操作日志
   */
  list: AuditLog[];
};

export type AuditActionList = {
  /**
   * 动作（operationId）列表
   */
  actions: string[];
};

export type AuditExport = {
  /**
   * 建议的文件名（含本地时间戳）
   */
  filename: string;
  /**
   * CSV 文本（已带 UTF-8 BOM 与表头，行尾 CRLF）
   */
  content: string;
  /**
   * 实际导出的数据行数（不含表头）
   */
  rows: number;
  /**
   * 当前筛选条件下的总条数（可能大于 rows）
   */
  total: number;
  /**
   * 是否因达到导出上限被截断（true 时界面要提示先缩小筛选范围）
   */
  truncated: boolean;
};

export type AuditQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字：模糊匹配操作人账号名 / 动作（如 password）/ 目标 id / 请求路径
   */
  keyword?: string;
  /**
   * 排序字段（取值见各接口说明，未登记的值会退回默认排序）
   */
  sort?: string;
  /**
   * 排序方向：asc 升序 / desc 降序
   */
  order?: "asc" | "desc";
  /**
   * 只看某个操作人的日志（管理员 id）
   */
  actorId?: string;
  /**
   * 只看某个动作（operationId，取值见 /admin/audit-logs/actions）
   */
  action?: string;
  /**
   * 目标类型筛选
   */
  targetType?: "account" | "role" | "admin" | "announcement" | "mail";
  /**
   * 只看针对某个目标的日志（目标 id）
   */
  targetId?: string;
  /**
   * 只看某个来源 IP（**精确匹配**；反向代理下需要 TRUST_PROXY=true 才准）
   */
  ip?: string;
  /**
   * 只看某个操作人角色
   */
  actorRole?: "super_admin" | "admin" | "viewer";
  /**
   * 结果筛选：true 只看成功 / false 只看失败
   */
  success?: "true" | "false";
  /**
   * 起始时间（毫秒时间戳，含）
   */
  from?: number;
  /**
   * 结束时间（毫秒时间戳，含）
   */
  to?: number;
};

export type AccountQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字（不同接口含义见其说明）
   */
  keyword?: string;
  /**
   * 排序字段（取值见各接口说明，未登记的值会退回默认排序）
   */
  sort?: string;
  /**
   * 排序方向：asc 升序 / desc 降序
   */
  order?: "asc" | "desc";
  /**
   * 状态筛选
   */
  status?: "active" | "disabled";
};

export type RoleQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字（不同接口含义见其说明）
   */
  keyword?: string;
  /**
   * 排序字段（取值见各接口说明，未登记的值会退回默认排序）
   */
  sort?: string;
  /**
   * 排序方向：asc 升序 / desc 降序
   */
  order?: "asc" | "desc";
  /**
   * 限定账号 id（查某账号下的全部角色）
   */
  accountId?: string;
  /**
   * 在线状态筛选：true 只看在线（账号当前选中的）角色
   */
  online?: "true" | "false";
  /**
   * 职业筛选
   */
  occupation?: "1" | "2" | "3" | "4";
  /**
   * 性别筛选
   */
  sex?: "1" | "2" | "3";
  /**
   * 最低等级（含）
   */
  minLevel?: number;
  /**
   * 最高等级（含）
   */
  maxLevel?: number;
};

export type AdminQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字（不同接口含义见其说明）
   */
  keyword?: string;
  /**
   * 排序字段（取值见各接口说明，未登记的值会退回默认排序）
   */
  sort?: string;
  /**
   * 排序方向：asc 升序 / desc 降序
   */
  order?: "asc" | "desc";
  /**
   * 角色筛选
   */
  role?: "super_admin" | "admin" | "viewer";
};

export type Health = {
  /**
   * 服务状态
   */
  status: string;
  /**
   * 运行环境
   */
  env: string;
  /**
   * 服务端时间戳（毫秒）
   */
  time: number;
};

export type SystemRuntime = {
  /**
   * 服务端版本（读 server/package.json）
   */
  version: string;
  /**
   * Node 版本
   */
  nodeVersion: string;
  /**
   * 运行环境（NODE_ENV）
   */
  env: string;
  /**
   * 进程 id
   */
  pid: number;
  /**
   * 已运行毫秒数
   */
  uptimeMs: number;
  /**
   * 已运行时长（人读，如「3 天 2 小时」）
   */
  uptimeText: string;
  /**
   * 进程启动时刻（毫秒时间戳）
   */
  startedAt: number;
  /**
   * 操作系统平台
   */
  platform: string;
  /**
   * 操作系统版本
   */
  platformRelease: string;
  /**
   * CPU 架构
   */
  arch: string;
  /**
   * 常驻内存（字节）
   */
  memoryRssBytes: number;
  /**
   * 堆已用内存（字节）
   */
  memoryHeapUsedBytes: number;
};

export type SystemTableCount = {
  /**
   * 表名
   */
  table: string;
  /**
   * 行数
   */
  rows: number;
};

export type SystemDatabase = {
  /**
   * 数据文件路径（`:memory:` = 内存库，无文件）
   */
  path: string;
  /**
   * 数据文件体积（字节）；内存库为 null
   */
  sizeBytes: number | null;
  /**
   * 数据文件最后修改时间（毫秒）；内存库为 null
   */
  modifiedAt: number | null;
  /**
   * 各表行数（动态枚举 sqlite_master，加表不用改这里）
   */
  tables: SystemTableCount[];
};

export type SystemConfigItem = {
  /**
   * 配置项（环境变量名）
   */
  key: string;
  /**
   * 值（或脱敏后的描述）
   */
  value: string;
  /**
   * 是否是脱敏项（值不是原文，只给形态）
   */
  sensitive: boolean;
  /**
   * 是否需要运维注意（如仍在使用默认 JWT 密钥）
   */
  warning: boolean;
};

export type SystemInfo = {
  /**
   * 运行时信息
   */
  runtime: SystemRuntime;
  /**
   * 数据库信息
   */
  database: SystemDatabase;
  /**
   * 脱敏后的配置快照（白名单：不列出 = 不暴露）
   */
  config: SystemConfigItem[];
  /**
   * 服务端时间戳（毫秒）
   */
  time: number;
};

export type ActiveAnnouncement = {
  /**
   * 公告 id
   */
  id: string;
  /**
   * 标题
   */
  title: string;
  /**
   * 正文（纯文本，换行用 \n）
   */
  content: string;
  /**
   * 级别：normal 普通 / important 重要（重要排在前）
   */
  level: "normal" | "important";
  /**
   * 生效开始时间（毫秒）；null = 立即生效
   */
  startsAt: number | null;
  /**
   * 生效结束时间（毫秒，不含）；null = 不设截止
   */
  endsAt: number | null;
};

export type Announcement = {
  /**
   * 公告 id
   */
  id: string;
  /**
   * 标题
   */
  title: string;
  /**
   * 正文（纯文本，换行用 \n）
   */
  content: string;
  /**
   * 级别
   */
  level: "normal" | "important";
  /**
   * 是否启用（手动下线开关；与时间窗是两道独立的闸）
   */
  enabled: boolean;
  /**
   * 生效开始时间（毫秒）；null = 立即生效
   */
  startsAt: number | null;
  /**
   * 生效结束时间（毫秒，不含）；null = 不设截止
   */
  endsAt: number | null;
  /**
   * 发布人管理员账号名（管理员被删后仍可追溯）
   */
  createdBy: string | null;
  /**
   * 创建时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近更新时间（毫秒）
   */
  updatedAt: number;
  /**
   * 当前是否生效中（由服务端判定，界面不要自己算）
   */
  active: boolean;
};

export type AnnouncementPage = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
  /**
   * 当前页的公告
   */
  list: Announcement[];
};

export type AnnouncementQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字：模糊匹配标题与正文
   */
  keyword?: string;
  /**
   * 排序字段（取值见各接口说明，未登记的值会退回默认排序）
   */
  sort?: string;
  /**
   * 排序方向：asc 升序 / desc 降序
   */
  order?: "asc" | "desc";
  /**
   * 级别筛选
   */
  level?: "normal" | "important";
  /**
   * 启用状态筛选：true 只看启用 / false 只看停用
   */
  enabled?: "true" | "false";
  /**
   * 生效状态筛选：true 只看生效中 / false 只看不在生效窗口内（含未开始与已过期）
   */
  active?: "true" | "false";
};

export type MailJob = {
  /**
   * 任务 id
   */
  id: string;
  /**
   * 收件邮箱
   */
  to: string;
  /**
   * 关联的玩家账号 id；null = 未关联账号
   */
  accountId: string | null;
  /**
   * 关联的玩家账号名；账号已被删则为 null
   */
  accountName: string | null;
  /**
   * 模板 key
   */
  templateKey: string;
  /**
   * 模板中文名（模板已被删则退回 key）
   */
  templateName: string;
  /**
   * 渲染后的标题
   */
  subject: string;
  /**
   * 渲染后的正文（重投时发的仍是这份内容，模板改动不影响已入队的任务）
   */
  body: string;
  /**
   * 状态
   */
  status: "pending" | "sending" | "retrying" | "sent" | "failed";
  /**
   * 状态中文名
   */
  statusLabel: string;
  /**
   * 已尝试次数（成功的那次也计入）
   */
  attempts: number;
  /**
   * 下一次重试的时刻（毫秒）；待发送与终态为 null
   */
  nextRetryAt: number | null;
  /**
   * 最近一次失败的原因；成功为 null（界面可直接展示）
   */
  lastError: string | null;
  /**
   * 发起人管理员账号名（管理员被删后仍可追溯）
   */
  createdBy: string | null;
  /**
   * 入队时间（毫秒）
   */
  createdAt: number;
  /**
   * 最近更新时间（毫秒）
   */
  updatedAt: number;
  /**
   * 投递成功的时刻（毫秒）；未成功为 null
   */
  sentAt: number | null;
};

export type MailJobPage = {
  /**
   * 总条数
   */
  total: number;
  /**
   * 当前页码（从 1 开始）
   */
  page: number;
  /**
   * 每页条数
   */
  size: number;
  /**
   * 当前页的投递任务
   */
  list: MailJob[];
};

export type MailQuery = {
  /**
   * 页码，从 1 开始
   */
  page?: number;
  /**
   * 每页条数（1~100）
   */
  size?: number;
  /**
   * 关键字：模糊匹配收件邮箱 / 标题 / 收件账号名
   */
  keyword?: string;
  /**
   * 排序字段（取值见各接口说明，未登记的值会退回默认排序）
   */
  sort?: string;
  /**
   * 排序方向：asc 升序 / desc 降序
   */
  order?: "asc" | "desc";
  /**
   * 状态筛选
   */
  status?: "pending" | "sending" | "retrying" | "sent" | "failed";
};

export type MailTemplate = {
  /**
   * 模板 key
   */
  key: string;
  /**
   * 模板中文名
   */
  name: string;
  /**
   * 用途说明（界面提示运营这封信该填什么）
   */
  hint: string;
  /**
   * 必填变量名；缺一个就拒发
   */
  variables: string[];
  /**
   * 标题模板（含 {{变量}} 占位符；custom 为空串）
   */
  subject: string;
  /**
   * 正文模板（含 {{变量}} 占位符；custom 为空串）
   */
  body: string;
};

export type SendMailResult = {
  /**
   * 投递任务 id
   */
  id: string;
  /**
   * 入队后的状态（恒为 pending：是否真发出去要在投递记录里看）
   */
  status: string;
  /**
   * 渲染后的标题（可以先看一眼，发错了还来得及在记录里查到）
   */
  subject: string;
};
