#!/usr/bin/env node
/**
 * 接口文件生成器（OpenAPI → 客户端 / 管理端）
 *
 * 输入：`server/openapi.json`（由 `cd server && npm run swagger:emit` 从服务端代码生成）
 * 输出（**生成物，禁止手改**）：
 *
 * | 端 | 文件 | 内容 |
 * |----|------|------|
 * | 客户端 assets/ui/utils/net | `ApiRoutes.ts` | 接口路径表（唯一来源） |
 * |                            | `ApiModels.ts` | 响应 / 入参类型（服务端 DTO 的镜像） |
 * |                            | `Api.ts`       | 接口方法（HealthApi / AuthApi / RoleApi） |
 * | 管理端 admin/src/api      | `routes.ts`    | 接口路径表（唯一来源） |
 * |                            | `models.ts`    | 类型（服务端 DTO 的镜像） |
 * |                            | `endpoints.ts` | 接口方法（authApi / accountsApi / adminsApi / rolesApi） |
 *
 * 为什么必须生成而不是手写：三端本来就是「服务端改一个字段、另外两端忘了改」最容易出事的地方。
 * 现在路径、方法名、类型全部从同一份文档产出，服务端改完重新生成，两端立刻拿到新签名 ——
 * 类型对不上就编译不过，而不是等线上出现一个 undefined。
 *
 * 生成器读的机器可读约定（都由服务端的装饰器写进文档）：
 * - `operationId` 形如 `<模块>.<方法>`（如 `role.save`）→ 决定生成到哪个模块的哪个方法；
 * - `x-olua-audience`（public / player / admin）→ 决定是否带令牌（public 走 `auth: false`）；
 * - `x-olua-data-schema` → 响应里 `data` 的类型（缺省 = data 恒为 null）；
 * - `x-olua-data-nullable` → data 是否可能为 null；
 * - `x-olua-query-schema` → query 参数对应的 DTO（据此生成命名的查询类型）；
 * - `x-olua-permissions` → 写进生成物的注释，让人在两端也能看到「这接口要什么权限」。
 *
 * 用法：
 *   node tools/gen-api.cjs            # 生成（写入磁盘）
 *   node tools/gen-api.cjs --check    # 只比对，不写盘（不一致则退出码 1，守卫脚本用）
 *   node tools/gen-api.cjs --json     # 输出 JSON 摘要
 */

"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const OPENAPI_FILE = path.join(ROOT, "server", "openapi.json");

/** 文档里的路径前缀（服务端 setGlobalPrefix 的值）；两端 baseUrl 已含它，生成时剥掉 */
const API_PREFIX = "/api";

/** 生成物头部标记（守卫脚本据此确认「这个文件是生成出来的」） */
const GENERATED_MARK = "@generated by tools/gen-api.cjs";

/**
 * 服务端 DTO 名 → 对外类型名
 *
 * 默认规则是「去掉 Dto 后缀」；这里只登记**沿用两端既有叫法**的几个 ——
 * 改成新名字会牵动一批调用点，而新名字并不更好（比如 `RoleDto` 若生成成 `Role`，
 * 客户端就会和 `entities/Role` 那个游戏实体撞名）。
 */
const TYPE_ALIASES = {
  AuthTokenDto: "AuthResult",
  RoleDto: "RoleDetail",
  AdminDto: "AdminInfo",
  AdminTokenDto: "AdminAuthResult",
  AdminAccountDetailDto: "AccountDetail",
  RoleQueryDto: "RoleQuery",
  AdminPatchRoleDto: "RolePatchPayload",
  AdminUpdateDto: "AdminUpdatePayload",
};

/** 不生成的 schema：统一响应包裹属于请求层传输细节，两端各自手写（避免同名冲突） */
const SKIP_SCHEMAS = new Set(["ApiEnvelopeDto"]);

/**
 * 模块段 → 生成到哪一端、导出成什么名字
 *
 * 这一小张表是「SDK 的形状」：改它等于改两端的调用方式，所以只在这里写一次。
 * 两边名字沿用既有叫法（`RoleApi.list()` / `rolesApi.list()`），生成前后调用点几乎不用动。
 */
const MODULES = {
  health: { target: "client", export: "HealthApi" },
  auth: { target: "client", export: "AuthApi" },
  announcement: { target: "client", export: "AnnouncementApi" },
  role: { target: "client", export: "RoleApi" },
  adminAuth: { target: "admin", export: "authApi" },
  adminAccount: { target: "admin", export: "accountsApi" },
  adminAdmin: { target: "admin", export: "adminsApi" },
  adminRole: { target: "admin", export: "rolesApi" },
  adminAudit: { target: "admin", export: "auditApi" },
  adminStats: { target: "admin", export: "statsApi" },
  adminSystem: { target: "admin", export: "systemApi" },
  adminAnnouncement: { target: "admin", export: "announcementsApi" },
  adminMail: { target: "admin", export: "mailsApi" },
};

/** 生成目标（文件落点与请求层方言） */
const TARGETS = {
  client: {
    key: "client",
    label: "客户端",
    dir: path.join(ROOT, "client", "assets", "ui", "utils", "net"),
    routesFile: "ApiRoutes.ts",
    modelsFile: "ApiModels.ts",
    endpointsFile: "Api.ts",
    routesConst: "ApiRoutes",
    /** 请求层入口（唯一发请求的地方） */
    requestEntry: "HttpClient",
    endpointsDoc: [
      "客户端接口（自动生成，禁止手改）",
      "",
      "路径来自 `./ApiRoutes`（生成），类型来自 `./ApiModels`（生成）。",
      "业务层只调这里，不写路径、不拼令牌、不判状态码 —— 那些都在 `./HttpClient` 里统一处理。",
      "令牌失效时 HttpClient 会回调入口注册的处理，见 `ui/Game.ts`。",
    ],
    routesDoc: [
      "路由表（客户端**唯一的接口路径来源**）",
      "",
      "只登记路径，不带 host（host 在 configs/network）；请求层拼装时统一加前缀。",
      "本文件由 `tools/gen-api.cjs` 从服务端 OpenAPI 文档生成，**禁止手改**",
      "（守卫：`node tools/audit-api-generated.cjs`）。",
    ],
  },
  admin: {
    key: "admin",
    label: "管理端",
    dir: path.join(ROOT, "admin", "src", "api"),
    routesFile: "routes.ts",
    modelsFile: "models.ts",
    endpointsFile: "endpoints.ts",
    routesConst: "routes",
    requestEntry: "http",
    endpointsDoc: [
      "接口方法（管理端唯一调服务端的地方，自动生成，禁止手改）",
      "",
      "路径来自 `./routes`（生成），类型来自 `./models`（生成）。",
      "页面只从 `./index` barrel import，不写路径、不拼令牌、不判状态码。",
    ],
    routesDoc: [
      "路由表（管理端**唯一的接口路径来源**）",
      "",
      "只登记路径，不带 host（host 在 `./config` 的 API_BASE_URL）；请求层拼装时统一加前缀。",
      "本文件由 `tools/gen-api.cjs` 从服务端 OpenAPI 文档生成，**禁止手改**",
      "（守卫：`node tools/audit-api-generated.cjs`）。",
    ],
  },
};

//#region 小工具

function readDoc(file = OPENAPI_FILE) {
  if (!fs.existsSync(file)) {
    throw new Error(`找不到 OpenAPI 文档：${path.relative(ROOT, file)}\n先执行：cd server && npm run swagger:emit`);
  }
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

/** 类型名（去 Dto 后缀 + 别名） */
function typeNameOf(schemaName) {
  return TYPE_ALIASES[schemaName] ?? String(schemaName).replace(/Dto$/, "");
}

/** `#/components/schemas/XxxDto` → `Xxx`（对外类型名） */
function refNameOf(ref) {
  return typeNameOf(String(ref).split("/").pop());
}

const pascal = (text) =>
  String(text)
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

/** JSDoc 安全化（描述里可能出现 `*\/`） */
const safeDoc = (text) => String(text ?? "").replace(/\*\//g, "*\\/");

/** 多行描述 → JSDoc 行数组（去掉首尾空行） */
function docLines(text) {
  if (!text) return [];
  return safeDoc(text)
    .split(/\r?\n/)
    .map((line) => line.trimEnd())
    .filter((line, index, all) => !(line === "" && (index === 0 || index === all.length - 1)));
}

/** 首段摘要（用于接口方法的 JSDoc） */
function firstLine(text) {
  if (!text) return "";
  return (
    String(text)
      .split(/\r?\n/)
      .map((line) => line.trim())
      .find((line) => line && line !== "---") ?? ""
  );
}

/** 注释缩进对齐（生成物里的 JSDoc） */
function emitDoc(indent, lines) {
  if (!lines.length) return [];
  return [`${indent}/**`, ...lines.map((line) => `${indent} * ${line}`.trimEnd()), `${indent} */`];
}

//#endregion

//#region schema → TS 类型

function resolveRef(ref, doc) {
  const name = String(ref).replace("#/components/schemas/", "");
  const schema = doc.components?.schemas?.[name];
  if (!schema) throw new Error(`悬空 $ref：${ref}（文档里没有这个 schema）`);
  return schema;
}

/** 合并 allOf（Nest 一般已把继承拍平，这里兜底：把各段的 properties / required 并起来） */
function mergeAllOf(parts, doc) {
  const merged = { type: "object", properties: {}, required: [], additionalProperties: undefined };
  const absorb = (schema) => {
    if (!schema) return;
    if (schema.$ref) return absorb(resolveRef(schema.$ref, doc));
    if (schema.allOf) return schema.allOf.forEach(absorb);
    Object.assign(merged.properties, schema.properties ?? {});
    if (Array.isArray(schema.required)) merged.required.push(...schema.required);
    if (schema.additionalProperties !== undefined) merged.additionalProperties = schema.additionalProperties;
  };
  parts.forEach(absorb);
  return merged;
}

/** 取「一个对象 schema 的最终形态」（解开 allOf / $ref） */
function objectShape(schema, doc) {
  if (!schema) return { properties: {}, required: [] };
  if (schema.$ref) return objectShape(resolveRef(schema.$ref, doc), doc);
  if (schema.allOf) return mergeAllOf(schema.allOf, doc);
  return { properties: schema.properties ?? {}, required: schema.required ?? [] };
}

/** schema → TS 类型表达式 */
function tsType(schema, doc) {
  if (!schema) return "unknown";
  if (schema.$ref) return refNameOf(schema.$ref);

  let base;
  if (schema.allOf) {
    // Nest 对「字段类型是另一个 DTO」（`@ApiProperty({ type: XxxDto })`）会写成
    // `allOf: [{ $ref }]`；这种就该还原成那个类型名，而不是当成匿名对象
    const refs = schema.allOf.filter((part) => part.$ref);
    const inline = schema.allOf.filter((part) => !part.$ref && (part.properties || part.required));
    if (refs.length === 1 && !inline.length) {
      base = refNameOf(refs[0].$ref);
    } else {
      const merged = mergeAllOf(schema.allOf, doc);
      const entries = Object.entries(merged.properties ?? {});
      base = entries.length ? `{ ${entries.map(([key, value]) => `${key}: ${tsType(value, doc)}`).join("; ")} }` : "Record<string, unknown>";
    }
  } else if (Array.isArray(schema.enum) && schema.enum.length) {
    base = schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  } else if (schema.type === "array") {
    const item = tsType(schema.items, doc);
    base = `${item.includes("|") ? `(${item})` : item}[]`;
  } else if (schema.type === "string") {
    base = "string";
  } else if (schema.type === "number" || schema.type === "integer") {
    base = "number";
  } else if (schema.type === "boolean") {
    base = "boolean";
  } else if (schema.additionalProperties === true) {
    base = "Record<string, unknown>";
  } else if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
    base = `Record<string, ${tsType(schema.additionalProperties, doc)}>`;
  } else {
    // 既没 type 也没 $ref（服务端漏了 type 的 nullable 字段）：只能当未知
    base = "unknown";
  }

  if (schema.nullable && base !== "null") {
    base = base.includes("|") && !base.startsWith("(") ? `(${base}) | null` : `${base} | null`;
  }
  return base;
}

/** 分隔符拆词（用于「这段类型表达式里用到了哪些生成类型」） */
const tokensOf = (text) => String(text ?? "").split(/[^A-Za-z0-9_]+/).filter(Boolean);

//#endregion

//#region 收集接口

function collectOperations(doc) {
  const operations = [];
  const seen = new Map();

  for (const [rawPath, item] of Object.entries(doc.paths ?? {})) {
    for (const method of ["get", "post", "put", "patch", "delete"]) {
      const op = item[method];
      if (!op) continue;

      const operationId = op.operationId;
      if (!operationId) throw new Error(`${method.toUpperCase()} ${rawPath} 缺少 operationId（服务端要用 @ApiXxxDoc 声明）`);
      if (seen.has(operationId)) {
        throw new Error(`operationId 重复：${operationId}（${seen.get(operationId)} 与 ${method.toUpperCase()} ${rawPath}）`);
      }
      seen.set(operationId, `${method.toUpperCase()} ${rawPath}`);

      const dot = operationId.lastIndexOf(".");
      if (dot <= 0) throw new Error(`operationId 需形如「模块.方法」：${operationId}（${method.toUpperCase()} ${rawPath}）`);
      const moduleKey = operationId.slice(0, dot);
      const methodName = operationId.slice(dot + 1);

      const meta = MODULES[moduleKey];
      if (!meta) {
        throw new Error(`operationId 的模块段没登记：${moduleKey}（${operationId}）—— 请在 tools/gen-api.cjs 的 MODULES 里补一条`);
      }

      // 文档路径一般不带全局前缀（服务端 setGlobalPrefix 不会进文档）；带上时也能兼容
      const fullPath = rawPath.startsWith(API_PREFIX) ? rawPath.slice(API_PREFIX.length) : rawPath;
      if (!fullPath.startsWith("/")) throw new Error(`路径不合法：${rawPath}`);

      // 归哪一端只看路径：管理端接口全在 /admin 下（与 Swagger 分组的「管理端」一一对应）
      const expectedTarget = fullPath === "/admin" || fullPath.startsWith("/admin/") ? "admin" : "client";
      if (meta.target !== expectedTarget) {
        throw new Error(`${operationId} 的路径是 ${rawPath}，应归 ${expectedTarget}，但 MODULES 里登记的是 ${meta.target}`);
      }

      const parameters = op.parameters ?? [];
      const templateParams = [...fullPath.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]);
      const declaredPathParams = parameters.filter((param) => param.in === "path").map((param) => param.name);
      for (const name of templateParams) {
        if (!declaredPathParams.includes(name)) throw new Error(`${rawPath} 的路径参数 {${name}} 没有对应的 parameters 声明`);
      }

      const queryParams = parameters
        .filter((param) => param.in === "query")
        .map((param) => ({ name: param.name, required: param.required === true, description: param.description, schema: param.schema ?? {} }));

      const bodySchema = op.requestBody?.content?.["application/json"]?.schema ?? null;
      const synthesizedQueryName = queryParams.length ? `${pascal(moduleKey)}${pascal(methodName)}Query` : null;

      operations.push({
        doc,
        moduleKey,
        methodName,
        export: meta.export,
        target: meta.target,
        method: method.toUpperCase(),
        /** 剥掉 /api 前缀的路径（两端 baseUrl 已含前缀） */
        path: fullPath,
        pathParams: templateParams,
        queryParams,
        querySchemaRef: op["x-olua-query-schema"]?.$ref ?? null,
        queryTypeName: op["x-olua-query-schema"]?.$ref ? refNameOf(op["x-olua-query-schema"].$ref) : synthesizedQueryName,
        synthesizedQueryName,
        bodySchema,
        bodyTypeName: bodySchema?.$ref ? refNameOf(bodySchema.$ref) : null,
        dataSchema: op["x-olua-data-schema"] ?? null,
        dataNullable: op["x-olua-data-nullable"] === true,
        audience: op["x-olua-audience"] ?? "player",
        permissions: op["x-olua-permissions"] ?? [],
        summary: op.summary ?? "",
        description: firstLine(op.description),
        source: `${method.toUpperCase()} ${fullPath}`,
      });
    }
  }

  operations.sort((a, b) => (a.path === b.path ? a.method.localeCompare(b.method) : a.path.localeCompare(b.path)));
  return operations;
}

/** 响应类型表达式（data 的类型） */
function returnTypeOf(op) {
  if (!op.dataSchema) return "null";
  let base = tsType(op.dataSchema, op.doc);
  if (op.dataNullable && !base.includes("null")) base = `${base} | null`;
  return base;
}

//#endregion

//#region 生成：路径表

/** 路径表达式：无参数 → 字符串；有参数 → 箭头函数 */
function pathExpression(op) {
  if (!op.pathParams.length) return JSON.stringify(op.path);
  const template = op.path.replace(/\{([^}]+)\}/g, (_match, name) => `\${encodeURIComponent(${name})}`);
  const args = op.pathParams.map((name) => `${name}: string`).join(", ");
  return `(${args}) => \`${template}\``;
}

function emitRoutesFile(target, operations) {
  const groups = new Map();
  for (const op of operations) {
    if (!groups.has(op.moduleKey)) groups.set(op.moduleKey, []);
    groups.get(op.moduleKey).push(op);
  }

  const lines = [];
  lines.push(...header(target, target.routesFile));
  lines.push("");
  lines.push(...emitDoc("", target.routesDoc));
  lines.push(`export const ${target.routesConst} = {`);
  for (const [moduleKey, group] of groups) {
    lines.push(`  /** ${moduleKey} 模块（${group.length} 个接口） */`);
    lines.push(`  ${moduleKey}: {`);
    for (const op of group) {
      const doc = [`${op.summary || op.methodName}（${op.source}）`];
      if (op.description && op.description !== op.summary) doc.push("", op.description);
      lines.push(...emitDoc("    ", doc));
      lines.push(`    ${op.methodName}: ${pathExpression(op)},`);
    }
    lines.push("  },");
  }
  lines.push("} as const;");
  lines.push("");
  return lines.join("\n");
}

//#endregion

//#region 生成：类型

/**
 * 为什么用 `export type X = {...}` 而不是 `export interface X {...}`
 *
 * interface **没有隐式索引签名**，赋给「`Record<string, ...>` 形状的参数」时会被 TS 拒绝
 * （两端的请求层 query 参数就是这种形状，已有真实报错）。
 * 对象字面量类型别名则有隐式索引签名，省掉一大批 `as Record<...>` 断言。
 * 继承关系在文档里本来就被拍平了，用不上 interface 的 extend / 声明合并。
 */
function emitModelsFile(target, schemas, extraInterfaces) {
  const lines = [];
  lines.push(...header(target, target.modelsFile));
  lines.push("");
  lines.push(
    ...emitDoc("", [
      "服务端 DTO 的镜像（自动生成，禁止手改）",
      "",
      "字段与服务端 `@ApiProperty` 一一对应；这里的每一条都对应 OpenAPI 文档里的一个 schema。",
    ]),
  );

  for (const [name, entry] of schemas) {
    lines.push("");
    const shape = objectShape(entry.schema, entry.doc);
    const required = new Set(shape.required ?? []);
    lines.push(`export type ${name} = {`);
    for (const [prop, propSchema] of Object.entries(shape.properties ?? {})) {
      const propDoc = docLines(propSchema.description);
      if (propDoc.length) lines.push(...emitDoc("  ", propDoc));
      const optional = required.has(prop) ? "" : "?";
      lines.push(`  ${prop}${optional}: ${tsType(propSchema, entry.doc)};`);
    }
    lines.push("};");
  }

  for (const [name, body] of extraInterfaces) {
    lines.push("");
    lines.push(`export type ${name} = {`);
    lines.push(...body);
    lines.push("};");
  }

  lines.push("");
  return lines.join("\n");
}

/** 查询参数 → 合成类型（服务端没给 `x-olua-query-schema` 时的兜底） */
function synthesizeQueryInterfaces(operations) {
  const result = new Map();
  for (const op of operations) {
    if (!op.queryTypeName || !op.synthesizedQueryName) continue;
    if (op.queryTypeName !== op.synthesizedQueryName) continue;
    if (result.has(op.queryTypeName)) continue;
    const body = [];
    for (const param of op.queryParams) {
      const doc = docLines(param.description);
      if (doc.length) body.push(...emitDoc("  ", doc));
      body.push(`  ${param.name}${param.required ? "" : "?"}: ${tsType(param.schema, op.doc)};`);
    }
    result.set(op.queryTypeName, body);
  }
  return result;
}

//#endregion

//#region 生成：接口方法

function argListOf(op) {
  const args = op.pathParams.map((name) => `${name}: string`);
  if (op.bodySchema) args.push(`body: ${op.bodyTypeName ?? "Record<string, unknown>"}`);
  if (op.queryTypeName) args.push(`query: ${op.queryTypeName} = {}`);
  args.push("options?: Options");
  return args;
}

/** 请求选项对象表达式 */
function optionsExpression(op) {
  const parts = [];
  if (op.queryTypeName) parts.push("query");
  if (op.audience === "public") parts.push("auth: false");
  parts.push("...options");
  return parts.length === 1 ? "options" : `{ ${parts.join(", ")} }`;
}

function callExpression(op, target) {
  const ret = returnTypeOf(op);
  const pathExpr = op.pathParams.length
    ? `${target.routesConst}.${op.moduleKey}.${op.methodName}(${op.pathParams.join(", ")})`
    : `${target.routesConst}.${op.moduleKey}.${op.methodName}`;
  const opts = optionsExpression(op);

  if (op.method === "GET" || op.method === "DELETE") {
    const fn = op.method === "GET" ? "get" : "del";
    return `${target.requestEntry}.${fn}<${ret}>(${pathExpr}, ${opts})`;
  }
  const fn = op.method === "POST" ? "post" : op.method === "PUT" ? "put" : "patch";
  return `${target.requestEntry}.${fn}<${ret}>(${pathExpr}, ${op.bodySchema ? "body" : "undefined"}, ${opts})`;
}

function emitEndpointsFile(target, operations, modelNames, allModelNames) {
  const groups = new Map();
  for (const op of operations) {
    if (!groups.has(op.export)) groups.set(op.export, []);
    groups.get(op.export).push(op);
  }

  const isClient = target.key === "client";
  const modelsModule = isClient ? "./ApiModels" : "./models";

  const lines = [];
  lines.push(...header(target, target.endpointsFile));
  lines.push("");
  if (isClient) {
    lines.push('import HttpClient from "./HttpClient";');
    lines.push('import type { RequestOptions } from "./HttpClient";');
  } else {
    lines.push('import { http } from "./http";');
    lines.push('import type { HttpOptions } from "./http";');
  }
  lines.push(`import { ${target.routesConst} } from "./${target.routesFile.replace(/\.ts$/, "")}";`);
  lines.push(`import type { ${modelNames.join(", ")} } from "${modelsModule}";`);
  lines.push("");
  lines.push(...emitDoc("", target.endpointsDoc));
  lines.push("");
  lines.push(...emitDoc("", ["请求选项：method / path / body 已由生成的方法填好，调用方只管 silent、timeout 之类的开关"]));
  lines.push(isClient ? 'type Options = Omit<RequestOptions, "method" | "path" | "body">;' : "type Options = HttpOptions;");
  lines.push("");
  lines.push("// 模型类型再导出一次：调用方 `import type { RoleSummary } from \"./Api\"` 这类既有写法仍然可用");
  lines.push(`export type { ${allModelNames.join(", ")} } from "${modelsModule}";`);
  lines.push("");

  for (const [exportName, group] of groups) {
    lines.push(`/** ${group[0].moduleKey} 模块的接口（${group.length} 个，生成） */`);
    lines.push(`export const ${exportName} = {`);
    for (const op of group) {
      const doc = [op.summary ? `${op.summary}（${op.source}）` : op.source];
      if (op.description && op.description !== op.summary) doc.push("", op.description);
      if (op.permissions.length) doc.push("", `权限点：${op.permissions.join("、")}`);
      lines.push(...emitDoc("  ", doc));
      lines.push(`  ${op.methodName}: (${argListOf(op).join(", ")}) => ${callExpression(op, target)},`);
    }
    lines.push("};");
    lines.push("");
  }
  return lines.join("\n");
}

//#endregion

//#region 组装

function buildOutputs(doc = readDoc()) {
  const operations = collectOperations(doc);

  const schemas = new Map();
  for (const [name, schema] of Object.entries(doc.components?.schemas ?? {})) {
    if (SKIP_SCHEMAS.has(name)) continue;
    schemas.set(typeNameOf(name), { schema, doc });
  }

  const extraInterfaces = synthesizeQueryInterfaces(operations);
  const knownNames = new Set([...schemas.keys(), ...extraInterfaces.keys()]);
  const allModelNames = [...knownNames].sort();

  const outputs = new Map();
  for (const target of Object.values(TARGETS)) {
    const own = operations.filter((op) => op.target === target.key);
    // 只 import「本文件签名里直接出现」的类型名：模型之间互相引用由 models 文件自己解决，
    // 多带入的未使用类型会在 `noUnusedLocals` 下报错
    const referenced = new Set();
    for (const op of own) {
      for (const part of [returnTypeOf(op), op.bodyTypeName, op.queryTypeName]) {
        for (const token of tokensOf(part)) if (knownNames.has(token)) referenced.add(token);
      }
    }

    outputs.set(
      path.join(target.dir, target.modelsFile),
      emitModelsFile(target, schemas, extraInterfaces),
    );
    outputs.set(path.join(target.dir, target.routesFile), emitRoutesFile(target, own));
    outputs.set(path.join(target.dir, target.endpointsFile), emitEndpointsFile(target, own, [...referenced].sort(), allModelNames));
  }

  return { operations, outputs };
}

/** 统一的生成物头 */
function header(target, fileName) {
  return [
    "/**",
    ` * ${GENERATED_MARK}`,
    " *",
    ` * 来源：server/openapi.json（由服务端代码生成） → ${target.label}接口文件：${fileName}`,
    " * 重新生成：cd server && npm run gen:api",
    " * 一致性守卫：node tools/audit-api-generated.cjs（生成物落后于文档即 FAIL）",
    " *",
    " * ⚠️ 请勿手改：改接口请改服务端的 DTO / 控制器（含 operationId），再重新生成。",
    " */",
  ];
}

//#endregion

//#region 写盘 / 校验

/** Cocos 需要每个资源有 .meta；这里给缺失的生成物补一个（uuid 由路径派生，多次运行稳定） */
function ensureMeta(file) {
  const metaFile = `${file}.meta`;
  if (fs.existsSync(metaFile)) return false;
  const digest = crypto.createHash("md5").update(`olua:${path.relative(ROOT, file)}`).digest("hex");
  const uuid = `${digest.slice(0, 8)}-${digest.slice(8, 12)}-4${digest.slice(13, 16)}-a${digest.slice(17, 20)}-${digest.slice(20, 32)}`;
  fs.writeFileSync(
    metaFile,
    `${JSON.stringify({ ver: "4.0.24", importer: "typescript", imported: true, uuid, files: [], subMetas: {}, userData: {} }, null, 2)}\n`,
    "utf8",
  );
  return true;
}

function main() {
  const args = process.argv.slice(2);
  const check = args.includes("--check");
  const asJson = args.includes("--json");

  const { operations, outputs } = buildOutputs();

  const results = [];
  const stale = [];
  const metaRepaired = [];
  for (const [file, content] of outputs) {
    const rel = path.relative(ROOT, file).split(path.sep).join("/");
    const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
    // 只有 Cocos 工程（客户端 assets）需要 .meta；管理端是 Vite 工程，写 .meta 只是垃圾文件
    const isCocosAsset = file.startsWith(path.join(ROOT, "client", "assets"));

    if (current === content) {
      // 内容没变也要保证 .meta 在：新克隆的仓库、meta 被误删时，光靠「内容变了才补」补不回来
      if (isCocosAsset && !check && ensureMeta(file)) metaRepaired.push(rel);
      results.push({ file: rel, status: "same" });
      continue;
    }
    if (check) {
      stale.push({ file: rel, status: current === null ? "missing" : "stale" });
      continue;
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content, "utf8");
    if (isCocosAsset && ensureMeta(file)) metaRepaired.push(rel);
    results.push({ file: rel, status: current === null ? "created" : "updated" });
  }

  if (asJson) {
    console.log(JSON.stringify({ operations: operations.length, files: results, stale }, null, 2));
  } else if (check) {
    console.log("接口文件一致性检查 / api generated audit");
    console.log(`  文档接口 ${operations.length} 个 → 期望产物 ${outputs.size} 个文件`);
    for (const item of stale) console.log(`  ✗ ${item.file}（${item.status === "missing" ? "缺失" : "与文档不一致"}）`);
    if (!stale.length) console.log(`  ✓ ${outputs.size} 个文件都与文档一致`);
  } else {
    console.log("接口文件生成 / api codegen");
    console.log(`  server/openapi.json → ${operations.length} 个接口 / ${outputs.size} 个文件`);
    for (const item of results) console.log(`  ${item.status === "same" ? "·" : "✓"} ${item.file}${item.status === "same" ? "（未变）" : ""}`);
    if (metaRepaired.length) console.log(`  ✓ 补回 ${metaRepaired.length} 个缺失的 .meta：${metaRepaired.join("、")}`);
  }

  if (check && stale.length) {
    console.log("");
    console.log(`FAIL：${stale.length} 个文件不是最新 —— 执行 \`cd server && npm run gen:api\` 重新生成`);
    process.exit(1);
  }
  if (check) console.log("\nPASS：生成物与 OpenAPI 文档一致");
}

module.exports = { buildOutputs, collectOperations, readDoc, typeNameOf, TARGETS, MODULES, GENERATED_MARK, OPENAPI_FILE, API_PREFIX };

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(`生成失败：${error.message}`);
    process.exit(1);
  }
}
