import { Drug, GOOD_TYPE } from "../types/good";

/**
 * 药品配置（物品大类 GOOD_TYPE.DRUG）
 * icon 取自 resources/item，effects 为使用效果（可扩展回血/回蓝/增益等）
 */
export const drugs: Drug[] = [
  {
    id: "drug_hp_1",
    type: GOOD_TYPE.DRUG,
    label: "金创药（小）",
    level: 1,
    description: "外伤药，使用后恢复 30 点生命值。",
    icon: "item/fs_2",
    sellPirce: 5,
    stackable: true,
    maxStack: 99,
    effects: [{ hp: 30 }],
    cooldown: 1,
  },
  {
    id: "drug_hp_2",
    type: GOOD_TYPE.DRUG,
    label: "金创药（中）",
    level: 5,
    description: "外伤药，使用后恢复 60 点生命值。",
    icon: "item/fs_3",
    sellPirce: 12,
    stackable: true,
    maxStack: 99,
    effects: [{ hp: 60 }],
    cooldown: 1,
  },
  {
    id: "drug_hp_3",
    type: GOOD_TYPE.DRUG,
    label: "金创药（大）",
    level: 10,
    description: "外伤药，使用后恢复 120 点生命值。",
    icon: "item/fs_4",
    sellPirce: 25,
    stackable: true,
    maxStack: 99,
    effects: [{ hp: 120 }],
    cooldown: 1,
  },
  {
    id: "drug_mp_1",
    type: GOOD_TYPE.DRUG,
    label: "魔法药（小）",
    level: 1,
    description: "使用后恢复 20 点魔法值。",
    icon: "item/sz_2",
    sellPirce: 5,
    stackable: true,
    maxStack: 99,
    effects: [{ mp: 20 }],
    cooldown: 1,
  },
  {
    id: "drug_mp_2",
    type: GOOD_TYPE.DRUG,
    label: "魔法药（中）",
    level: 5,
    description: "使用后恢复 50 点魔法值。",
    icon: "item/sz_3",
    sellPirce: 12,
    stackable: true,
    maxStack: 99,
    effects: [{ mp: 50 }],
    cooldown: 1,
  },
  {
    id: "drug_sun",
    type: GOOD_TYPE.DRUG,
    label: "太阳水",
    level: 1,
    description: "使用后同时恢复 50 点生命值与 30 点魔法值。",
    icon: "item/tz_2",
    sellPirce: 30,
    stackable: true,
    maxStack: 99,
    effects: [{ hp: 50, mp: 30 }],
    cooldown: 1,
  },
];
