import { Vec2 } from "cc";
import { Equipment, EQUIPMENT_TYPE, EquipmentSlot, GOOD_TYPE } from "../types/good";
import { OECCUPATION, SEX } from "../types/role";

// 角色弹窗中装备槽map
export const equipmentSlots = new Map<EQUIPMENT_TYPE, EquipmentSlot>();
equipmentSlots.set(EQUIPMENT_TYPE.OTHER1, { label: "其他1", imageSrc: "slots/other", position: "bottom" });
equipmentSlots.set(EQUIPMENT_TYPE.CLOTH, { label: "衣服", imageSrc: "slots/cloth", position: "bottom" });
equipmentSlots.set(EQUIPMENT_TYPE.OTHER2, { label: "其他2", imageSrc: "slots/other", position: "bottom" });

equipmentSlots.set(EQUIPMENT_TYPE.WEAPON, { label: "武器", imageSrc: "slots/weapon", position: "left" });
equipmentSlots.set(EQUIPMENT_TYPE.NECKLACE, { label: "项链", imageSrc: "slots/necklace", position: "left" });
equipmentSlots.set(EQUIPMENT_TYPE.RING, { label: "戒指", imageSrc: "slots/ring", position: "left" });
equipmentSlots.set(EQUIPMENT_TYPE.ACCESSORIES, { label: "饰品", imageSrc: "slots/accessories", position: "left" });
equipmentSlots.set(EQUIPMENT_TYPE.SHINGUARD, { label: "护腿", imageSrc: "slots/shinguard", position: "left" });

equipmentSlots.set(EQUIPMENT_TYPE.HELMET, { label: "头盔", imageSrc: "slots/helmet", position: "right" });
equipmentSlots.set(EQUIPMENT_TYPE.SCAPULAR, { label: "肩胛", imageSrc: "slots/scapular", position: "right" });
equipmentSlots.set(EQUIPMENT_TYPE.BELT, { label: "腰带", imageSrc: "slots/belt", position: "right" });
equipmentSlots.set(EQUIPMENT_TYPE.WRISTBAND, { label: "护腕", imageSrc: "slots/wristband", position: "right" });
equipmentSlots.set(EQUIPMENT_TYPE.SHOES, { label: "鞋子", imageSrc: "slots/shoes", position: "right" });

// 衣服
export const clothes: Equipment[] = [
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.CLOTH,
    occupation: OECCUPATION.ALL,
    label: "* 唯一深爱(衣) *",
    sex: SEX.ALL,
    level: 1,
    description: "葬爱家族专属衣服，穿上此装备，开启你的旅程吧！",
    sellPirce: 0,
    icon: "clothes/icon/005",
    in: "clothes/in/005",
    out: "clothes/out/005",
    physicalAttack: [0, 100],
    magicAttack: [0, 100],
    taoistAttack: [0, 100],
    physicalDefense: [0, 50],
    magicDefense: [0, 50],
    taoistDefense: [0, 50],
    maxHp: 3000,
    inPosition: new Vec2(-72.5, 48),
    tags: ["第一大陆"],
    prefix: "葬爱",
    suffix: "魂级",
    inScaleX: 1.3,
    inScaleY: 1.3,
    outScale: 1,
    outPosition: new Vec2(7.3, 34.2),
  },
];

// 武器（label/description/icon/in/out 按 resources/weapons 的图标与内外观资源拟定，战斗数值待补）
export const weapons: Equipment[] = [
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "定海神针",
    sex: SEX.ALL,
    level: 1,
    description: "东海龙王的宝物，送给新手冒险家的第一件武器。握紧它，开启你的旅程吧！",
    sellPirce: 0,
    icon: "weapons/icon/001",
    in: "weapons/in/001",
    out: "weapons/out/001",
    physicalAttack: [0, 10],
    magicAttack: [0, 1],
    taoistAttack: [0, 1],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-205.5, 194),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "暗夜雷光剑",
    sex: SEX.ALL,
    level: 1,
    description: "漆黑的剑身中封存着一道白色雷霆，挥动之时雷光乍现，暗夜如昼。",
    sellPirce: 0,
    icon: "weapons/icon/002",
    in: "weapons/in/002",
    out: "weapons/out/002",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-151.5, 111),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "圣天使之剑",
    sex: SEX.ALL,
    level: 1,
    description: "剑柄生有天使之翼，护手处镶着一颗心形红宝石，传说是圣天使留给凡间的馈赠。",
    sellPirce: 0,
    icon: "weapons/icon/003",
    in: "weapons/in/003",
    out: "weapons/out/003",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-178, 137),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "青龙破军剑",
    sex: SEX.ALL,
    level: 1,
    description: "青碧剑身上盘绕着金龙与流火，出鞘之时隐有龙吟，破军之锋所指之处皆为坦途。",
    sellPirce: 0,
    icon: "weapons/icon/004",
    in: "weapons/in/004",
    out: "weapons/out/004",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-170.5, 150),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  /**   {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "炎狱狂刀",
    sex: SEX.ALL,
    level: 1,
    description: "布满锯齿的重刃燃烧着狱蓝色的火焰，戾气极重，凡人难以掌控。",
    sellPirce: 0,
    icon: "weapons/icon/005",
    in: "weapons/in/005",
    out: "", // resources/weapons/out/005 缺失，暂无外观
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(0, 0),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  }, */
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "焚天赤金刃",
    sex: SEX.ALL,
    level: 1,
    description: "通体赤金的宝刃，刀身终年缠绕着不灭的烈焰，可焚天下之物。",
    sellPirce: 0,
    icon: "weapons/icon/006",
    in: "weapons/in/006",
    out: "weapons/out/006",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-141, 86),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "玄铁惊雷剑",
    sex: SEX.ALL,
    level: 1,
    description: "以玄铁铸就的重剑，剑锋常年缠绕惊雷，挥落之时如雷鸣贯耳。",
    sellPirce: 0,
    icon: "weapons/icon/007",
    in: "weapons/in/007",
    out: "weapons/out/007",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-185, 102),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "嗜血魔刃",
    sex: SEX.ALL,
    level: 1,
    description: "暗红的剑身上浮现着古老的血色符文，饮血而愈，愈战愈勇。",
    sellPirce: 0,
    icon: "weapons/icon/008",
    in: "weapons/in/008",
    out: "weapons/out/008",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-164, 146),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "紫电青霜剑",
    sex: SEX.ALL,
    level: 1,
    description: "紫蓝雷光在水晶剑身上流转，出剑快如闪电，剑气冷若寒霜。",
    sellPirce: 0,
    icon: "weapons/icon/009",
    in: "weapons/in/009",
    out: "weapons/out/009",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-139, -9.5),
    inRotate: 260,
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "朱雀羽刃",
    sex: SEX.ALL,
    level: 1,
    description: "刀如凤凰展翅，燃着朱雀神火，传说蕴含浴火重生之力。",
    sellPirce: 0,
    icon: "weapons/icon/010",
    in: "weapons/in/010",
    out: "weapons/out/010",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-125, -13.5),
    inRotate: 280,
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "炽焰双头杖",
    sex: SEX.ALL,
    level: 1,
    description: "两端燃着不灭火焰的秘法长杖，是火系法师梦寐以求的宝物。",
    sellPirce: 0,
    icon: "weapons/icon/011",
    in: "weapons/in/011",
    out: "weapons/out/011",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-68, 15.5),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "圣光十字剑",
    sex: SEX.ALL,
    level: 1,
    description: "金色十字剑柄辉映着湛蓝圣光，可破一切黑暗邪祟。",
    sellPirce: 0,
    icon: "weapons/icon/012",
    in: "weapons/in/012",
    out: "weapons/out/012",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-139, 42),
    inRotate: 240,
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "炎皇圣剑",
    sex: SEX.ALL,
    level: 1,
    description: "剑身铭刻上古炎皇纹章，中央的赤红宝石封存着焚世之力。",
    sellPirce: 0,
    icon: "weapons/icon/013",
    in: "weapons/in/013",
    out: "weapons/out/013",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-79, 17),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  /**   {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "紫翼金冠刃",
    sex: SEX.ALL,
    level: 1,
    description: "形似金冠、缀以紫翼的奇门兵器，唯有王者方可驾驭。",
    sellPirce: 0,
    icon: "weapons/icon/014",
    in: "weapons/in/014",
    out: "weapons/out/014",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(0, 0),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  }, */
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "屠龙金纹剑",
    sex: SEX.ALL,
    level: 1,
    description: "剑身铭满屠龙金纹，曾是斩杀上古魔龙的英雄佩剑。",
    sellPirce: 0,
    icon: "weapons/icon/015",
    in: "weapons/in/015",
    out: "weapons/out/015",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-76, 80),
    inRotate: 280,
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "青莲业火剑",
    sex: SEX.ALL,
    level: 1,
    description: "剑身燃着青莲业火，焚尽业障，可斩虚空。",
    sellPirce: 0,
    icon: "weapons/icon/016",
    in: "weapons/in/016",
    out: "weapons/out/016",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-80, 80),
    inRotate: 280,
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "紫晶魔剑",
    sex: SEX.ALL,
    level: 1,
    description: "由整块紫晶雕琢而成的魔剑，剑气所过之处空间震裂。",
    sellPirce: 0,
    icon: "weapons/icon/017",
    in: "weapons/in/017",
    out: "weapons/out/017",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-222, 231),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "紫翼神冠刃",
    sex: SEX.ALL,
    level: 1,
    description: "紫翼金冠的真正形态，觉醒之后可撕裂苍穹。",
    sellPirce: 0,
    icon: "weapons/icon/018",
    in: "weapons/in/018",
    out: "weapons/out/018",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-80, 48),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "燃金圣剑",
    sex: SEX.ALL,
    level: 1,
    description: "圣剑通体由燃金铸成，剑焰不熄，光照千里。",
    sellPirce: 0,
    icon: "weapons/icon/019",
    in: "weapons/in/019",
    out: "weapons/out/019",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-225, 230),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "焚世巨剑",
    sex: SEX.ALL,
    level: 1,
    description: "传闻此剑一挥，可焚尽一世。唯有真正的强者敢将它握在手中。",
    sellPirce: 0,
    icon: "weapons/icon/020",
    in: "weapons/in/020",
    out: "weapons/out/020",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(-172, 143),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
  /**   {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.WEAPON,
    occupation: OECCUPATION.ALL,
    label: "赤炎飞刃",
    sex: SEX.ALL,
    level: 1,
    description: "小巧却灼热无比的火焰飞刃，出手只在眨眼之间。",
    sellPirce: 0,
    icon: "weapons/icon/021",
    in: "", // resources/weapons/in/021 缺失，暂无内观
    out: "weapons/out/021",
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    inPosition: new Vec2(0, 0),
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  }, */
];

// 戒指
export const rings: Equipment[] = [
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.RING,
    occupation: OECCUPATION.ALL,
    sex: SEX.ALL,
    in: "",
    inPosition: new Vec2(),
    out: "",
    label: "新手戒指",
    level: 1,
    description: "新手戒指，穿上此装备，开启你的旅程吧！",
    icon: "item/2010210",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 1],
    taoistAttack: [0, 1],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
];

// 项链
export const nicklaces: Equipment[] = [
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.NECKLACE,
    occupation: OECCUPATION.ALL,
    sex: SEX.ALL,
    in: "",
    inPosition: new Vec2(),
    out: "",
    label: "新手项链",
    level: 1,
    description: "新手项链，穿上此装备，开启你的旅程吧！",
    icon: "item/2010310",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 1],
    taoistAttack: [0, 1],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 0,
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
];

// 鞋子
export const shoes: Equipment[] = [
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.SHOES,
    occupation: OECCUPATION.ALL,
    sex: SEX.ALL,
    in: "",
    inPosition: new Vec2(),
    out: "",
    label: "新手鞋子",
    level: 1,
    description: "新手鞋子，穿上此装备，开启你的旅程吧！",
    icon: "item/2030410",
    sellPirce: 0,
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 5],
    magicDefense: [0, 5],
    taoistDefense: [0, 5],
    maxHp: 5,
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
];

// 头盔
export const helmets: Equipment[] = [
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.HELMET,
    occupation: OECCUPATION.ALL,
    sex: SEX.ALL,
    in: "",
    inPosition: new Vec2(),
    out: "",
    label: "新手头盔",
    level: 1,
    description: "新手头盔，穿上此装备，开启你的旅程吧！",
    icon: "item/2030702",
    sellPirce: 0,
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 5],
    magicDefense: [0, 5],
    taoistDefense: [0, 5],
    maxHp: 5,
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
];

// 腰带
export const belts: Equipment[] = [
  {
    type: GOOD_TYPE.EQUIPMENT,
    slot: EQUIPMENT_TYPE.BELT,
    occupation: OECCUPATION.ALL,
    sex: SEX.ALL,
    in: "",
    inPosition: new Vec2(),
    out: "",
    label: "新手腰带",
    level: 1,
    description: "新手腰带，穿上此装备，开启你的旅程吧！",
    icon: "item/2030810",
    sellPirce: 0,
    physicalAttack: [0, 0],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 5],
    magicDefense: [0, 5],
    taoistDefense: [0, 5],
    maxHp: 5,
    tags: [],
    prefix: "",
    suffix: "",
    outScale: 1,
    outPosition: new Vec2(),
  },
];
