import { Size, Vec2 } from "cc";
import { ACTION } from "../types/animation";
import { MonsterConfig } from "../types/monster";

export const monsters = new Map<string, MonsterConfig>();

/**
 * 怪物 AI 参数（全局共用）
 * 单只怪物的「移动速度 / 是否主动攻击 / 检测范围」写在各自配置里（moveSpeed / aggressive / detectRange），
 * 这里放所有怪物共用的行为节奏：普攻相关、待在原地时的换动作与随机走动
 * 行为由 MonsterAI 每帧驱动：主动攻击的怪物发现玩家进入检测范围就追人，追到普攻距离停下开打，
 * 玩家离开检测范围即停在原地（停留点作为原地随机走动的活动中心）
 */
export const monsterAI = {
  /** 普攻间隔（毫秒）——怪物只会普攻，没有技能，技能以后再考虑 */
  attackInterval: 2000,
  /** 普攻距离（像素）：追到这个距离就停下出手 */
  attackRange: 60,
  /** 普攻动作时长（毫秒）：出手期间站定不移动，动作播完才结算伤害 */
  attackActionTime: 600,
  /** 待机时可随机切换的动作池（想加动作往这里加，例如 ACTION.RUN / ACTION.A1） */
  idleActions: [ACTION.STAND, ACTION.WALK] as ACTION[],
  /** 待机时更换动作的随机间隔（毫秒） */
  idleAnimationInterval: [2000, 5000] as [number, number],
  /** 待机时触发一次随机走动的随机间隔（毫秒） */
  idleMoveInterval: [4000, 9000] as [number, number],
  /** 每次随机走动的持续时间（毫秒） */
  idleMoveDuration: [300, 800] as [number, number],
  /** 随机走动的速度倍率（相对怪物自身 moveSpeed，比追击慢一点） */
  idleMoveSpeedScale: 0.5,
  /** 随机走动的活动半径（像素）：离停留点超过这个距离就往回走，避免越走越远 */
  wanderRadius: 60,
  /**
   * 击退默认时长（毫秒）：技能击退是场上唯一能推动位置的途径，
   * 技能配置里只写距离时用这个时长换算击退速度（距离 / 时长），改这里可统一调整击退手感
   */
  pushDuration: 200,
};

monsters.set("1", {
  icon: "monster/icon/1",
  out: "monster/out/1",
  outOffset: new Vec2(),
  label: "赤焰斗鸡",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  drops: "common",
  level: 1,
  description: "赤焰斗鸡",
  sellPirce: 0,
  physicalAttack: [0, 10],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 100,
  contentSize: new Size(100, 100),
  speedRate: {
    [ACTION.STAND]: 1,
    [ACTION.WALK]: 1,
    [ACTION.RUN]: 1,
    [ACTION.ATTACK_NEAR]: 1,
    [ACTION.ATTACK_SKILL_1]: 1,
    [ACTION.TEST3]: 1,
    [ACTION.ATTACK_FAR]: 1,
    [ACTION.INJURED]: 1,
    [ACTION.A1]: 1,
    [ACTION.DIE]: 1,
    [ACTION.TEST1]: 1,
  },
});
monsters.set("2", {
  icon: "monster/icon/2",
  out: "monster/out/2",
  outOffset: new Vec2(),
  label: "金斑雄鹿",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  drops: "common",
  level: 2,
  description: "金斑雄鹿",
  sellPirce: 0,
  physicalAttack: [0, 50],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 500,
  contentSize: new Size(100, 100),
  speedRate: {
    [ACTION.STAND]: 1,
    [ACTION.WALK]: 1,
    [ACTION.RUN]: 1,
    [ACTION.ATTACK_NEAR]: 1,
    [ACTION.ATTACK_SKILL_1]: 1,
    [ACTION.TEST3]: 1,
    [ACTION.ATTACK_FAR]: 1,
    [ACTION.INJURED]: 1,
    [ACTION.A1]: 1,
    [ACTION.DIE]: 1,
    [ACTION.TEST1]: 1,
  },
});
monsters.set("3", {
  icon: "monster/icon/3",
  out: "monster/out/3",
  outOffset: new Vec2(),
  label: "干尸行者",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 5,
  description: "干尸行者",
  sellPirce: 0,
  physicalAttack: [0, 200],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 50],
  magicDefense: [0, 50],
  taoistDefense: [0, 50],
  maxHp: 1000,
  contentSize: new Size(50, 100),
  speedRate: {
    [ACTION.STAND]: 1,
    [ACTION.WALK]: 1,
    [ACTION.RUN]: 1,
    [ACTION.ATTACK_NEAR]: 1,
    [ACTION.ATTACK_SKILL_1]: 1,
    [ACTION.TEST3]: 1,
    [ACTION.ATTACK_FAR]: 1,
    [ACTION.INJURED]: 1,
    [ACTION.A1]: 1,
    [ACTION.DIE]: 1,
    [ACTION.TEST1]: 1,
  },
});
monsters.set("4", {
  icon: "monster/icon/4",
  out: "monster/out/4",
  outOffset: new Vec2(),
  label: "豺狼人巫师",
  moveSpeed: 2,
  aggressive: true,
  detectRange: 200,
  level: 10,
  description: "豺狼人巫师",
  sellPirce: 0,
  physicalAttack: [0, 500],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 500],
  magicDefense: [0, 500],
  taoistDefense: [0, 500],
  maxHp: 5000,
  contentSize: new Size(100, 100),
  speedRate: {
    [ACTION.STAND]: 1,
    [ACTION.WALK]: 1,
    [ACTION.RUN]: 1,
    [ACTION.ATTACK_NEAR]: 1,
    [ACTION.ATTACK_SKILL_1]: 1,
    [ACTION.TEST3]: 1,
    [ACTION.ATTACK_FAR]: 1,
    [ACTION.INJURED]: 1,
    [ACTION.A1]: 1,
    [ACTION.DIE]: 1,
    [ACTION.TEST1]: 1,
  },
});
monsters.set("5", {
  icon: "monster/icon/5",
  out: "monster/out/5",
  outOffset: new Vec2(),
  label: "狮头人术士",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "狮头人术士",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("6", {
  icon: "monster/icon/6",
  out: "monster/out/6",
  outOffset: new Vec2(),
  label: "巨疣蟾蜍",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "巨疣蟾蜍",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("7", {
  icon: "monster/icon/7",
  out: "monster/out/7",
  outOffset: new Vec2(),
  label: "碎骨残骸",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "碎骨残骸",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("8", {
  icon: "monster/icon/8",
  out: "monster/out/8",
  outOffset: new Vec2(),
  label: "牛角骷髅将",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "牛角骷髅将",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("9", {
  icon: "monster/icon/9",
  out: "monster/out/9",
  outOffset: new Vec2(),
  label: "骨锤蛮兵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "骨锤蛮兵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("10", {
  icon: "monster/icon/10",
  out: "monster/out/10",
  outOffset: new Vec2(),
  label: "血赤骷髅",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血赤骷髅",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("11", {
  icon: "monster/icon/11",
  out: "monster/out/11",
  outOffset: new Vec2(),
  label: "龟甲忍士",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "龟甲忍士",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("12", {
  icon: "monster/icon/12",
  out: "monster/out/12",
  outOffset: new Vec2(),
  label: "雪岭野人",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "雪岭野人",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("13", {
  icon: "monster/icon/13",
  out: "monster/out/13",
  outOffset: new Vec2(),
  label: "黑猿妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黑猿妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("14", {
  icon: "monster/icon/14",
  out: "monster/out/14",
  outOffset: new Vec2(),
  label: "猛犸巨象",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "猛犸巨象",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("15", {
  icon: "monster/icon/15",
  out: "monster/out/15",
  outOffset: new Vec2(),
  label: "黑翼巨蝠",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黑翼巨蝠",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("16", {
  icon: "monster/icon/16",
  out: "monster/out/16",
  outOffset: new Vec2(),
  label: "海螺精",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "海螺精",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("17", {
  icon: "monster/icon/17",
  out: "monster/out/17",
  outOffset: new Vec2(),
  label: "金甲独角仙",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金甲独角仙",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("18", {
  icon: "monster/icon/18",
  out: "monster/out/18",
  outOffset: new Vec2(),
  label: "金翅灵鸟",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金翅灵鸟",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("19", {
  icon: "monster/icon/19",
  out: "monster/out/19",
  outOffset: new Vec2(),
  label: "沙岗蠕虫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "沙岗蠕虫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("20", {
  icon: "monster/icon/20",
  out: "monster/out/20",
  outOffset: new Vec2(),
  label: "野狼",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "野狼",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("21", {
  icon: "monster/icon/21",
  out: "monster/out/21",
  outOffset: new Vec2(),
  label: "盘角羚羊",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "盘角羚羊",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("22", {
  icon: "monster/icon/22",
  out: "monster/out/22",
  outOffset: new Vec2(),
  label: "灰壳蛞蝓",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "灰壳蛞蝓",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("23", {
  icon: "monster/icon/23",
  out: "monster/out/23",
  outOffset: new Vec2(),
  label: "独腿尸兵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "独腿尸兵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("24", {
  icon: "monster/icon/24",
  out: "monster/out/24",
  outOffset: new Vec2(),
  label: "血污行尸",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血污行尸",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("25", {
  icon: "monster/icon/25",
  out: "monster/out/25",
  outOffset: new Vec2(),
  label: "枯叶飞虫群",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "枯叶飞虫群",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("26", {
  icon: "monster/icon/26",
  out: "monster/out/26",
  outOffset: new Vec2(),
  label: "枯行僧尸",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "枯行僧尸",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("27", {
  icon: "monster/icon/27",
  out: "monster/out/27",
  outOffset: new Vec2(),
  label: "食人妖花",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "食人妖花",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("28", {
  icon: "monster/icon/28",
  out: "monster/out/28",
  outOffset: new Vec2(),
  label: "金环蛇",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金环蛇",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("29", {
  icon: "monster/icon/29",
  out: "monster/out/29",
  outOffset: new Vec2(),
  label: "赤练蛇",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤练蛇",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("30", {
  icon: "monster/icon/30",
  out: "monster/out/30",
  outOffset: new Vec2(),
  label: "枯树妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "枯树妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("31", {
  icon: "monster/icon/31",
  out: "monster/out/31",
  outOffset: new Vec2(),
  label: "蘑菇精",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "蘑菇精",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("32", {
  icon: "monster/icon/32",
  out: "monster/out/32",
  outOffset: new Vec2(),
  label: "黄甲多足虫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黄甲多足虫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("33", {
  icon: "monster/icon/33",
  out: "monster/out/33",
  outOffset: new Vec2(),
  label: "铜甲巨蝎",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "铜甲巨蝎",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("34", {
  icon: "monster/icon/34",
  out: "monster/out/34",
  outOffset: new Vec2(),
  label: "碎尸爬虫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "碎尸爬虫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("35", {
  icon: "monster/icon/35",
  out: "monster/out/35",
  outOffset: new Vec2(),
  label: "赤蜈蚣",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤蜈蚣",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("36", {
  icon: "monster/icon/36",
  out: "monster/out/36",
  outOffset: new Vec2(),
  label: "黄蜂妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黄蜂妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("37", {
  icon: "monster/icon/37",
  out: "monster/out/37",
  outOffset: new Vec2(),
  label: "蜣螂精",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "蜣螂精",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("38", {
  icon: "monster/icon/38",
  out: "monster/out/38",
  outOffset: new Vec2(),
  label: "虾兵怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "虾兵怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("39", {
  icon: "monster/icon/39",
  out: "monster/out/39",
  outOffset: new Vec2(),
  label: "银甲蝎蛉",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "银甲蝎蛉",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("40", {
  icon: "monster/icon/40",
  out: "monster/out/40",
  outOffset: new Vec2(),
  label: "青竹大蜈蚣",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "青竹大蜈蚣",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("41", {
  icon: "monster/icon/41",
  out: "monster/out/41",
  outOffset: new Vec2(),
  label: "金沙傀儡",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金沙傀儡",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("42", {
  icon: "monster/icon/42",
  out: "monster/out/42",
  outOffset: new Vec2(),
  label: "绿袍兽人武者",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "绿袍兽人武者",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("43", {
  icon: "monster/icon/43",
  out: "monster/out/43",
  outOffset: new Vec2(),
  label: "牛角兽人斧手",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "牛角兽人斧手",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("44", {
  icon: "monster/icon/44",
  out: "monster/out/44",
  outOffset: new Vec2(),
  label: "白衣幽魂",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白衣幽魂",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("45", {
  icon: "monster/icon/45",
  out: "monster/out/45",
  outOffset: new Vec2(),
  label: "幽冥触手魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "幽冥触手魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("46", {
  icon: "monster/icon/46",
  out: "monster/out/46",
  outOffset: new Vec2(),
  label: "金色海星妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金色海星妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("47", {
  icon: "monster/icon/47",
  out: "monster/out/47",
  outOffset: new Vec2(),
  label: "灰毛猩猩兽",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "灰毛猩猩兽",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("48", {
  icon: "monster/icon/48",
  out: "monster/out/48",
  outOffset: new Vec2(),
  label: "车轮骨妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "车轮骨妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("49", {
  icon: "monster/icon/49",
  out: "monster/out/49",
  outOffset: new Vec2(),
  label: "链锤夜叉",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "链锤夜叉",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("50", {
  icon: "monster/icon/50",
  out: "monster/out/50",
  outOffset: new Vec2(),
  label: "赤炎小恶魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤炎小恶魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("51", {
  icon: "monster/icon/51",
  out: "monster/out/51",
  outOffset: new Vec2(),
  label: "双斧狼卫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "双斧狼卫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("52", {
  icon: "monster/icon/52",
  out: "monster/out/52",
  outOffset: new Vec2(),
  label: "绿眼飞蛾妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "绿眼飞蛾妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("53", {
  icon: "monster/icon/53",
  out: "monster/out/53",
  outOffset: new Vec2(),
  label: "滑翔飞蜥",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "滑翔飞蜥",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("54", {
  icon: "monster/icon/54",
  out: "monster/out/54",
  outOffset: new Vec2(),
  label: "坠马骸骑兵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "坠马骸骑兵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("55", {
  icon: "monster/icon/55",
  out: "monster/out/55",
  outOffset: new Vec2(),
  label: "持戟猪首人",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "持戟猪首人",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("56", {
  icon: "monster/icon/56",
  out: "monster/out/56",
  outOffset: new Vec2(),
  label: "雷锤铁卫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "雷锤铁卫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("57", {
  icon: "monster/icon/57",
  out: "monster/out/57",
  outOffset: new Vec2(),
  label: "赤膊狂猿",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤膊狂猿",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("58", {
  icon: "monster/icon/58",
  out: "monster/out/58",
  outOffset: new Vec2(),
  label: "黑熊罴怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黑熊罴怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("59", {
  icon: "monster/icon/59",
  out: "monster/out/59",
  outOffset: new Vec2(),
  label: "赤须龙蜈",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤须龙蜈",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("60", {
  icon: "monster/icon/60",
  out: "monster/out/60",
  outOffset: new Vec2(),
  label: "黑鳞龙裔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黑鳞龙裔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("61", {
  icon: "monster/icon/61",
  out: "monster/out/61",
  outOffset: new Vec2(),
  label: "骨角黄巨魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "骨角黄巨魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("62", {
  icon: "monster/icon/62",
  out: "monster/out/62",
  outOffset: new Vec2(),
  label: "灰肤巨魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "灰肤巨魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("63", {
  icon: "monster/icon/63",
  out: "monster/out/63",
  outOffset: new Vec2(),
  label: "赤鳞怪胎",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤鳞怪胎",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("64", {
  icon: "monster/icon/64",
  out: "monster/out/64",
  outOffset: new Vec2(),
  label: "青鳞怪胎",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "青鳞怪胎",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("65", {
  icon: "monster/icon/65",
  out: "monster/out/65",
  outOffset: new Vec2(),
  label: "紫黑蟹蛛",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "紫黑蟹蛛",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("66", {
  icon: "monster/icon/66",
  out: "monster/out/66",
  outOffset: new Vec2(),
  label: "金斑飞蝎",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金斑飞蝎",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("67", {
  icon: "monster/icon/67",
  out: "monster/out/67",
  outOffset: new Vec2(),
  label: "沙尘鬼",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "沙尘鬼",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("68", {
  icon: "monster/icon/68",
  out: "monster/out/68",
  outOffset: new Vec2(),
  label: "金牛甲士",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金牛甲士",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("69", {
  icon: "monster/icon/69",
  out: "monster/out/69",
  outOffset: new Vec2(),
  label: "紫甲双锤兵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "紫甲双锤兵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("70", {
  icon: "monster/icon/70",
  out: "monster/out/70",
  outOffset: new Vec2(),
  label: "黑甲长斧魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黑甲长斧魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("71", {
  icon: "monster/icon/71",
  out: "monster/out/71",
  outOffset: new Vec2(),
  label: "银甲月刃枪卫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "银甲月刃枪卫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("72", {
  icon: "monster/icon/72",
  out: "monster/out/72",
  outOffset: new Vec2(),
  label: "红袍蛇杖法老",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "红袍蛇杖法老",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("73", {
  icon: "monster/icon/73",
  out: "monster/out/73",
  outOffset: new Vec2(),
  label: "陷坑野牛魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "陷坑野牛魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("74", {
  icon: "monster/icon/74",
  out: "monster/out/74",
  outOffset: new Vec2(),
  label: "土狼妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "土狼妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("75", {
  icon: "monster/icon/75",
  out: "monster/out/75",
  outOffset: new Vec2(),
  label: "青锋刀客",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "青锋刀客",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("76", {
  icon: "monster/icon/76",
  out: "monster/out/76",
  outOffset: new Vec2(),
  label: "青蛙斗士",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "青蛙斗士",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("77", {
  icon: "monster/icon/77",
  out: "monster/out/77",
  outOffset: new Vec2(),
  label: "独眼触手魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "独眼触手魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("78", {
  icon: "monster/icon/78",
  out: "monster/out/78",
  outOffset: new Vec2(),
  label: "碧爪蛛母",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "碧爪蛛母",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("79", {
  icon: "monster/icon/79",
  out: "monster/out/79",
  outOffset: new Vec2(),
  label: "碎金甲兵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "碎金甲兵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("80", {
  icon: "monster/icon/80",
  out: "monster/out/80",
  outOffset: new Vec2(),
  label: "黄袍圣甲虫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黄袍圣甲虫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("81", {
  icon: "monster/icon/81",
  out: "monster/out/81",
  outOffset: new Vec2(),
  label: "黄蜂后",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黄蜂后",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("82", {
  icon: "monster/icon/82",
  out: "monster/out/82",
  outOffset: new Vec2(),
  label: "铁壳蝼蛄",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "铁壳蝼蛄",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("83", {
  icon: "monster/icon/83",
  out: "monster/out/83",
  outOffset: new Vec2(),
  label: "犀甲巨蚁",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "犀甲巨蚁",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("84", {
  icon: "monster/icon/84",
  out: "monster/out/84",
  outOffset: new Vec2(),
  label: "白骨披甲将",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白骨披甲将",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("85", {
  icon: "monster/icon/85",
  out: "monster/out/85",
  outOffset: new Vec2(),
  label: "焰翅魔将",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "焰翅魔将",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("86", {
  icon: "monster/icon/86",
  out: "monster/out/86",
  outOffset: new Vec2(),
  label: "战旗兽人",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "战旗兽人",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("87", {
  icon: "monster/icon/87",
  out: "monster/out/87",
  outOffset: new Vec2(),
  label: "碎铁石堆怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "碎铁石堆怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("88", {
  icon: "monster/icon/88",
  out: "monster/out/88",
  outOffset: new Vec2(),
  label: "血晶碎块怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血晶碎块怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("89", {
  icon: "monster/icon/89",
  out: "monster/out/89",
  outOffset: new Vec2(),
  label: "骨翅飞妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "骨翅飞妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("90", {
  icon: "monster/icon/90",
  out: "monster/out/90",
  outOffset: new Vec2(),
  label: "骨爪爬魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "骨爪爬魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("91", {
  icon: "monster/icon/91",
  out: "monster/out/91",
  outOffset: new Vec2(),
  label: "碎石傀儡",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "碎石傀儡",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("92", {
  icon: "monster/icon/92",
  out: "monster/out/92",
  outOffset: new Vec2(),
  label: "妖娆花魁女妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "妖娆花魁女妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("93", {
  icon: "monster/icon/93",
  out: "monster/out/93",
  outOffset: new Vec2(),
  label: "青翼仙子",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "青翼仙子",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("94", {
  icon: "monster/icon/94",
  out: "monster/out/94",
  outOffset: new Vec2(),
  label: "金冠飞刀侠",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金冠飞刀侠",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("95", {
  icon: "monster/icon/95",
  out: "monster/out/95",
  outOffset: new Vec2(),
  label: "金甲持锤武圣",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金甲持锤武圣",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("96", {
  icon: "monster/icon/96",
  out: "monster/out/96",
  outOffset: new Vec2(),
  label: "蓝翼法灵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "蓝翼法灵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("97", {
  icon: "monster/icon/97",
  out: "monster/out/97",
  outOffset: new Vec2(),
  label: "白甲弓手",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白甲弓手",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("98", {
  icon: "monster/icon/98",
  out: "monster/out/98",
  outOffset: new Vec2(),
  label: "银甲白狼灵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "银甲白狼灵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("99", {
  icon: "monster/icon/99",
  out: "monster/out/99",
  outOffset: new Vec2(),
  label: "枯骨废墟堆",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "枯骨废墟堆",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("100", {
  icon: "monster/icon/100",
  out: "monster/out/100",
  outOffset: new Vec2(),
  label: "白袍行者",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白袍行者",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("101", {
  icon: "monster/icon/101",
  out: "monster/out/101",
  outOffset: new Vec2(),
  label: "黑铁锁链魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黑铁锁链魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("102", {
  icon: "monster/icon/102",
  out: "monster/out/102",
  outOffset: new Vec2(),
  label: "金斧矮人酋长",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金斧矮人酋长",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("103", {
  icon: "monster/icon/103",
  out: "monster/out/103",
  outOffset: new Vec2(),
  label: "白骨蛇",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白骨蛇",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("104", {
  icon: "monster/icon/104",
  out: "monster/out/104",
  outOffset: new Vec2(),
  label: "独眼巨魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "独眼巨魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("105", {
  icon: "monster/icon/105",
  out: "monster/out/105",
  outOffset: new Vec2(),
  label: "骨翼蝠魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "骨翼蝠魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("106", {
  icon: "monster/icon/106",
  out: "monster/out/106",
  outOffset: new Vec2(),
  label: "棕毛跳猿兽",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "棕毛跳猿兽",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("107", {
  icon: "monster/icon/107",
  out: "monster/out/107",
  outOffset: new Vec2(),
  label: "白毛狼牙锤怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白毛狼牙锤怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("108", {
  icon: "monster/icon/108",
  out: "monster/out/108",
  outOffset: new Vec2(),
  label: "电光双鞭将",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "电光双鞭将",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("109", {
  icon: "monster/icon/109",
  out: "monster/out/109",
  outOffset: new Vec2(),
  label: "金冠弯刀卫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金冠弯刀卫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("110", {
  icon: "monster/icon/110",
  out: "monster/out/110",
  outOffset: new Vec2(),
  label: "血蛛后",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血蛛后",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});

monsters.set("111", {
  icon: "monster/icon/111",
  out: "monster/out/111",
  outOffset: new Vec2(),
  label: "碎金残兵堆",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "碎金残兵堆",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("112", {
  icon: "monster/icon/112",
  out: "monster/out/112",
  outOffset: new Vec2(),
  label: "骨杖蛮巫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "骨杖蛮巫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("113", {
  icon: "monster/icon/113",
  out: "monster/out/113",
  outOffset: new Vec2(),
  label: "牛角红袍祭司",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "牛角红袍祭司",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("114", {
  icon: "monster/icon/114",
  out: "monster/out/114",
  outOffset: new Vec2(),
  label: "冰晶翼灵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "冰晶翼灵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("115", {
  icon: "monster/icon/115",
  out: "monster/out/115",
  outOffset: new Vec2(),
  label: "赤肌血魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤肌血魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("116", {
  icon: "monster/icon/116",
  out: "monster/out/116",
  outOffset: new Vec2(),
  label: "金环武僧",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金环武僧",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("117", {
  icon: "monster/icon/117",
  out: "monster/out/117",
  outOffset: new Vec2(),
  label: "机关木偶",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "机关木偶",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("118", {
  icon: "monster/icon/118",
  out: "monster/out/118",
  outOffset: new Vec2(),
  label: "红袍披风鬼将",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "红袍披风鬼将",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("119", {
  icon: "monster/icon/119",
  out: "monster/out/119",
  outOffset: new Vec2(),
  label: "悬空剑灵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "悬空剑灵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("120", {
  icon: "monster/icon/120",
  out: "monster/out/120",
  outOffset: new Vec2(),
  label: "金莲法阵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金莲法阵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("121", {
  icon: "monster/icon/121",
  out: "monster/out/121",
  outOffset: new Vec2(),
  label: "断戟残卒堆",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "断戟残卒堆",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("122", {
  icon: "monster/icon/122",
  out: "monster/out/122",
  outOffset: new Vec2(),
  label: "赤凰翔灵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤凰翔灵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("123", {
  icon: "monster/icon/123",
  out: "monster/out/123",
  outOffset: new Vec2(),
  label: "蓝冰晶簇",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "蓝冰晶簇",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("124", {
  icon: "monster/icon/124",
  out: "monster/out/124",
  outOffset: new Vec2(),
  label: "金冠法王",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金冠法王",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("125", {
  icon: "monster/icon/125",
  out: "monster/out/125",
  outOffset: new Vec2(),
  label: "藤蔓树魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "藤蔓树魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("126", {
  icon: "monster/icon/126",
  out: "monster/out/126",
  outOffset: new Vec2(),
  label: "缟素女鬼",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "缟素女鬼",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("127", {
  icon: "monster/icon/127",
  out: "monster/out/127",
  outOffset: new Vec2(),
  label: "巨翼骨蝠王",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "巨翼骨蝠王",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("128", {
  icon: "monster/icon/128",
  out: "monster/out/128",
  outOffset: new Vec2(),
  label: "皮甲猎弓手",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "皮甲猎弓手",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("129", {
  icon: "monster/icon/129",
  out: "monster/out/129",
  outOffset: new Vec2(),
  label: "金甲长枪灵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金甲长枪灵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("130", {
  icon: "monster/icon/130",
  out: "monster/out/130",
  outOffset: new Vec2(),
  label: "双锤牛魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "双锤牛魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("131", {
  icon: "monster/icon/131",
  out: "monster/out/131",
  outOffset: new Vec2(),
  label: "尸骸兵器冢",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "尸骸兵器冢",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("132", {
  icon: "monster/icon/132",
  out: "monster/out/132",
  outOffset: new Vec2(),
  label: "焰发女妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "焰发女妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("133", {
  icon: "monster/icon/133",
  out: "monster/out/133",
  outOffset: new Vec2(),
  label: "金链骷髅阵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金链骷髅阵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("134", {
  icon: "monster/icon/134",
  out: "monster/out/134",
  outOffset: new Vec2(),
  label: "粉晶机关兽",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "粉晶机关兽",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("135", {
  icon: "monster/icon/135",
  out: "monster/out/135",
  outOffset: new Vec2(),
  label: "金蟾精",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金蟾精",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("136", {
  icon: "monster/icon/136",
  out: "monster/out/136",
  outOffset: new Vec2(),
  label: "冰杖法童",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "冰杖法童",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("137", {
  icon: "monster/icon/137",
  out: "monster/out/137",
  outOffset: new Vec2(),
  label: "提灯行商怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "提灯行商怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("138", {
  icon: "monster/icon/138",
  out: "monster/out/138",
  outOffset: new Vec2(),
  label: "绿杖树精",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "绿杖树精",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("139", {
  icon: "monster/icon/139",
  out: "monster/out/139",
  outOffset: new Vec2(),
  label: "双筒火铳魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "双筒火铳魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("140", {
  icon: "monster/icon/140",
  out: "monster/out/140",
  outOffset: new Vec2(),
  label: "白狐少女妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白狐少女妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("141", {
  icon: "monster/icon/141",
  out: "monster/out/141",
  outOffset: new Vec2(),
  label: "金轮骨僧",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金轮骨僧",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("142", {
  icon: "monster/icon/142",
  out: "monster/out/142",
  outOffset: new Vec2(),
  label: "碧鳞蛟龙",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "碧鳞蛟龙",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("143", {
  icon: "monster/icon/143",
  out: "monster/out/143",
  outOffset: new Vec2(),
  label: "金纹道人",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金纹道人",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("144", {
  icon: "monster/icon/144",
  out: "monster/out/144",
  outOffset: new Vec2(),
  label: "枯骨翼妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "枯骨翼妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("145", {
  icon: "monster/icon/145",
  out: "monster/out/145",
  outOffset: new Vec2(),
  label: "黑棘龙兽",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黑棘龙兽",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("146", {
  icon: "monster/icon/146",
  out: "monster/out/146",
  outOffset: new Vec2(),
  label: "紫电武魂",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "紫电武魂",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("147", {
  icon: "monster/icon/147",
  out: "monster/out/147",
  outOffset: new Vec2(),
  label: "莲台鲛人",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "莲台鲛人",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("148", {
  icon: "monster/icon/148",
  out: "monster/out/148",
  outOffset: new Vec2(),
  label: "血刃狂魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血刃狂魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("149", {
  icon: "monster/icon/149",
  out: "monster/out/149",
  outOffset: new Vec2(),
  label: "骨幡妖将",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "骨幡妖将",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("150", {
  icon: "monster/icon/150",
  out: "monster/out/150",
  outOffset: new Vec2(),
  label: "翠纹飞蜥",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "翠纹飞蜥",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("151", {
  icon: "monster/icon/151",
  out: "monster/out/151",
  outOffset: new Vec2(),
  label: "血翼蝠群",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血翼蝠群",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("152", {
  icon: "monster/icon/152",
  out: "monster/out/152",
  outOffset: new Vec2(),
  label: "金鬃瑞狮",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金鬃瑞狮",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("153", {
  icon: "monster/icon/153",
  out: "monster/out/153",
  outOffset: new Vec2(),
  label: "独眼锤魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "独眼锤魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("154", {
  icon: "monster/icon/154",
  out: "monster/out/154",
  outOffset: new Vec2(),
  label: "长尾铁蝎",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "长尾铁蝎",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("155", {
  icon: "monster/icon/155",
  out: "monster/out/155",
  outOffset: new Vec2(),
  label: "血羽战鹰",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血羽战鹰",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("156", {
  icon: "monster/icon/156",
  out: "monster/out/156",
  outOffset: new Vec2(),
  label: "血雾散魂",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血雾散魂",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("157", {
  icon: "monster/icon/157",
  out: "monster/out/157",
  outOffset: new Vec2(),
  label: "金甲骁将",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金甲骁将",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("158", {
  icon: "monster/icon/158",
  out: "monster/out/158",
  outOffset: new Vec2(),
  label: "赤尾巨蝎",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤尾巨蝎",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("159", {
  icon: "monster/icon/159",
  out: "monster/out/159",
  outOffset: new Vec2(),
  label: "橙腹长脚蛛",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "橙腹长脚蛛",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("160", {
  icon: "monster/icon/160",
  out: "monster/out/160",
  outOffset: new Vec2(),
  label: "缚链石魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "缚链石魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("161", {
  icon: "monster/icon/161",
  out: "monster/out/161",
  outOffset: new Vec2(),
  label: "伏地金蟾",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "伏地金蟾",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("162", {
  icon: "monster/icon/162",
  out: "monster/out/162",
  outOffset: new Vec2(),
  label: "吐钱金蟾",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "吐钱金蟾",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("163", {
  icon: "monster/icon/163",
  out: "monster/out/163",
  outOffset: new Vec2(),
  label: "倾覆货车怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "倾覆货车怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("164", {
  icon: "monster/icon/164",
  out: "monster/out/164",
  outOffset: new Vec2(),
  label: "翻车货担怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "翻车货担怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("165", {
  icon: "monster/icon/165",
  out: "monster/out/165",
  outOffset: new Vec2(),
  label: "侧翻车厢怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "侧翻车厢怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("166", {
  icon: "monster/icon/166",
  out: "monster/out/166",
  outOffset: new Vec2(),
  label: "攻城战车怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "攻城战车怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("167", {
  icon: "monster/icon/167",
  out: "monster/out/167",
  outOffset: new Vec2(),
  label: "冲车机关怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "冲车机关怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("168", {
  icon: "monster/icon/168",
  out: "monster/out/168",
  outOffset: new Vec2(),
  label: "赤羽斗鸡",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤羽斗鸡",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("169", {
  icon: "monster/icon/169",
  out: "monster/out/169",
  outOffset: new Vec2(),
  label: "金斑幼鹿",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金斑幼鹿",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("170", {
  icon: "monster/icon/170",
  out: "monster/out/170",
  outOffset: new Vec2(),
  label: "枯瘦黄衣行者",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "枯瘦黄衣行者",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("171", {
  icon: "monster/icon/171",
  out: "monster/out/171",
  outOffset: new Vec2(),
  label: "举臂长毛猿",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "举臂长毛猿",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("172", {
  icon: "monster/icon/172",
  out: "monster/out/172",
  outOffset: new Vec2(),
  label: "藤杖猴妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "藤杖猴妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("173", {
  icon: "monster/icon/173",
  out: "monster/out/173",
  outOffset: new Vec2(),
  label: "象鼻地獾",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "象鼻地獾",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("174", {
  icon: "monster/icon/174",
  out: "monster/out/174",
  outOffset: new Vec2(),
  label: "白骨行尸",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白骨行尸",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("175", {
  icon: "monster/icon/175",
  out: "monster/out/175",
  outOffset: new Vec2(),
  label: "持斧骷髅卫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "持斧骷髅卫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("176", {
  icon: "monster/icon/176",
  out: "monster/out/176",
  outOffset: new Vec2(),
  label: "持锄白毛猿",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "持锄白毛猿",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("177", {
  icon: "monster/icon/177",
  out: "monster/out/177",
  outOffset: new Vec2(),
  label: "血爪夜叉",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血爪夜叉",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("178", {
  icon: "monster/icon/178",
  out: "monster/out/178",
  outOffset: new Vec2(),
  label: "灰甲蝼蛄",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "灰甲蝼蛄",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("179", {
  icon: "monster/icon/179",
  out: "monster/out/179",
  outOffset: new Vec2(),
  label: "金龟甲虫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金龟甲虫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("180", {
  icon: "monster/icon/180",
  out: "monster/out/180",
  outOffset: new Vec2(),
  label: "金翎鸟灵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金翎鸟灵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("181", {
  icon: "monster/icon/181",
  out: "monster/out/181",
  outOffset: new Vec2(),
  label: "黄斑腐尸",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黄斑腐尸",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("182", {
  icon: "monster/icon/182",
  out: "monster/out/182",
  outOffset: new Vec2(),
  label: "破衲行者",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "破衲行者",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("183", {
  icon: "monster/icon/183",
  out: "monster/out/183",
  outOffset: new Vec2(),
  label: "螺蛳灰虫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "螺蛳灰虫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("184", {
  icon: "monster/icon/184",
  out: "monster/out/184",
  outOffset: new Vec2(),
  label: "金环灵蛇",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金环灵蛇",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("185", {
  icon: "monster/icon/185",
  out: "monster/out/185",
  outOffset: new Vec2(),
  label: "赤信蛇妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "赤信蛇妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("186", {
  icon: "monster/icon/186",
  out: "monster/out/186",
  outOffset: new Vec2(),
  label: "金毛鬃兽",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金毛鬃兽",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("187", {
  icon: "monster/icon/187",
  out: "monster/out/187",
  outOffset: new Vec2(),
  label: "黄肚蛙将",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "黄肚蛙将",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("188", {
  icon: "monster/icon/188",
  out: "monster/out/188",
  outOffset: new Vec2(),
  label: "骨刺橙蜈蚣",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "骨刺橙蜈蚣",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("189", {
  icon: "monster/icon/189",
  out: "monster/out/189",
  outOffset: new Vec2(),
  label: "银角仙蜕",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "银角仙蜕",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("190", {
  icon: "monster/icon/190",
  out: "monster/out/190",
  outOffset: new Vec2(),
  label: "白骨团怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白骨团怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("191", {
  icon: "monster/icon/191",
  out: "monster/out/191",
  outOffset: new Vec2(),
  label: "铁甲双钳虫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "铁甲双钳虫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("192", {
  icon: "monster/icon/192",
  out: "monster/out/192",
  outOffset: new Vec2(),
  label: "银针骨虫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "银针骨虫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("193", {
  icon: "monster/icon/193",
  out: "monster/out/193",
  outOffset: new Vec2(),
  label: "泥沼爬行兽",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "泥沼爬行兽",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("194", {
  icon: "monster/icon/194",
  out: "monster/out/194",
  outOffset: new Vec2(),
  label: "石肤鬼王",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "石肤鬼王",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("195", {
  icon: "monster/icon/195",
  out: "monster/out/195",
  outOffset: new Vec2(),
  label: "持叉狼妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "持叉狼妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("196", {
  icon: "monster/icon/196",
  out: "monster/out/196",
  outOffset: new Vec2(),
  label: "骨刺链锤魔",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "骨刺链锤魔",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("197", {
  icon: "monster/icon/197",
  out: "monster/out/197",
  outOffset: new Vec2(),
  label: "血翼魔王",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血翼魔王",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("198", {
  icon: "monster/icon/198",
  out: "monster/out/198",
  outOffset: new Vec2(),
  label: "坠马铁骨怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "坠马铁骨怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("199", {
  icon: "monster/icon/199",
  out: "monster/out/199",
  outOffset: new Vec2(),
  label: "骨翼小飞龙",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "骨翼小飞龙",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("200", {
  icon: "monster/icon/200",
  out: "monster/out/200",
  outOffset: new Vec2(),
  label: "长尾跳鼠怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "长尾跳鼠怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("201", {
  icon: "monster/icon/201",
  out: "monster/out/201",
  outOffset: new Vec2(),
  label: "白骨弓手",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白骨弓手",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("202", {
  icon: "monster/icon/202",
  out: "monster/out/202",
  outOffset: new Vec2(),
  label: "铁甲长戟卫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "铁甲长戟卫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("203", {
  icon: "monster/icon/203",
  out: "monster/out/203",
  outOffset: new Vec2(),
  label: "断臂独锤兵",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "断臂独锤兵",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("204", {
  icon: "monster/icon/204",
  out: "monster/out/204",
  outOffset: new Vec2(),
  label: "红肤举锤巨人",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "红肤举锤巨人",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("205", {
  icon: "monster/icon/205",
  out: "monster/out/205",
  outOffset: new Vec2(),
  label: "狼头黑锤妖",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "狼头黑锤妖",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("206", {
  icon: "monster/icon/206",
  out: "monster/out/206",
  outOffset: new Vec2(),
  label: "铁节钢蜈蚣",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "铁节钢蜈蚣",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("207", {
  icon: "monster/icon/207",
  out: "monster/out/207",
  outOffset: new Vec2(),
  label: "雪白羊怪",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "雪白羊怪",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("208", {
  icon: "monster/icon/208",
  out: "monster/out/208",
  outOffset: new Vec2(),
  label: "荆棘刺球兽",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "荆棘刺球兽",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("209", {
  icon: "monster/icon/209",
  out: "monster/out/209",
  outOffset: new Vec2(),
  label: "土黄瘦狐",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "土黄瘦狐",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("210", {
  icon: "monster/icon/210",
  out: "monster/out/210",
  outOffset: new Vec2(),
  label: "白袍布衣道人",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白袍布衣道人",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("211", {
  icon: "monster/icon/211",
  out: "monster/out/211",
  outOffset: new Vec2(),
  label: "血背金龟虫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "血背金龟虫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("212", {
  icon: "monster/icon/212",
  out: "monster/out/212",
  outOffset: new Vec2(),
  label: "青绿毛毛虫",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "青绿毛毛虫",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("213", {
  icon: "monster/icon/213",
  out: "monster/out/213",
  outOffset: new Vec2(),
  label: "白骨腐尸",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "白骨腐尸",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("214", {
  icon: "monster/icon/214",
  out: "monster/out/214",
  outOffset: new Vec2(),
  label: "铁尾黑蝎",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "铁尾黑蝎",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("215", {
  icon: "monster/icon/215",
  out: "monster/out/215",
  outOffset: new Vec2(),
  label: "褐翼黑蝙蝠",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "褐翼黑蝙蝠",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("216", {
  icon: "monster/icon/216",
  out: "monster/out/216",
  outOffset: new Vec2(),
  label: "银斧圆盾矮人",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "银斧圆盾矮人",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("217", {
  icon: "monster/icon/217",
  out: "monster/out/217",
  outOffset: new Vec2(),
  label: "绿皮蟾人",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "绿皮蟾人",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("218", {
  icon: "monster/icon/218",
  out: "monster/out/218",
  outOffset: new Vec2(),
  label: "金鬃狻猊",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  level: 1,
  description: "金鬃狻猊",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("219", {
  icon: "monster/icon/219",
  out: "monster/out/219",
  outOffset: new Vec2(),
  label: "铁钩海盗",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  drops: "elite",
  level: 1,
  description: "铁钩海盗",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});
monsters.set("220", {
  icon: "monster/icon/220",
  out: "monster/out/220",
  outOffset: new Vec2(),
  label: "牛角石肤巨人",
  moveSpeed: 2,
  aggressive: false,
  detectRange: 200,
  drops: "boss",
  level: 1,
  description: "牛角石肤巨人",
  sellPirce: 0,
  physicalAttack: [0, 1],
  magicAttack: [0, 0],
  taoistAttack: [0, 0],
  physicalDefense: [0, 0],
  magicDefense: [0, 0],
  taoistDefense: [0, 0],
  maxHp: 10,
  contentSize: new Size(),
  speedRate: undefined,
});

export default monsters;
