import { Size, Vec2 } from "cc";
import { ACTION } from "../types/animation";
import { MonsterConfig, MonsterData } from "../types/monster";
import { monsterStats } from "./growth";

/**
 * 怪物数据表
 *
 * **key 只做关联**：地图对象组里的 id、掉落 / 技能 / AI 要引用同一只怪时都用 key，
 * 它可以是任意字符串（"1"、"goblin_chief" 都行），**不参与任何数值计算**。
 * 数值全部按**等级**从 configs/growth 的成长曲线取：
 * - level：这只怪自己的等级（唯一定级入口，想调强弱就改它）
 * - tier：定位 normal / elite / boss（不写 = normal），决定同等级下的强度倍率（见 configs/growth 的 monsterTierScale）
 * - 六项攻防与 maxHp：由 monsterStats(level, tier) 按等级生成，不用手写
 *   · 想单独改某只怪（法系怪要魔法攻击、特殊怪要更高血量）→ 直接在条目里覆盖同名字段
 *   · 想整体调手感（怪更耐打 / 打人更疼）→ 改 configs/growth 的 monsterBalance / roleGrowth
 */

/**
 * 怪物 AI 参数（全局共用）
 * 单只怪物的「移动速度 / 是否主动攻击 / 检测范围」写在各自配置里（moveSpeed / aggressive / detectRange），
 * 这里放所有怪物共用的行为节奏：普攻相关、待在原地时的换动作与随机走动
 * 行为由 MonsterAI 每帧驱动：主动攻击的怪物发现玩家进入检测范围就追人，追到普攻距离停下开打，
 * 玩家离开检测范围即停在原地（停留点作为原地随机走动的活动中心）
 */
export const monsterAI = {
  /** 普攻间隔（毫秒）——怪物只会普攻，没有技能，技能以后再考虑 */
  attackInterval: 2000,
  /** 普攻距离（像素）：追到这个距离就停下出手 */
  attackRange: 60,
  /** 普攻动作时长（毫秒）：出手期间站定不移动，动作播完才结算伤害 */
  attackActionTime: 600,
  /** 待机时可随机切换的动作池（想加动作往这里加，例如 ACTION.RUN / ACTION.A1） */
  idleActions: [ACTION.STAND, ACTION.WALK] as ACTION[],
  /** 待机时更换动作的随机间隔（毫秒） */
  idleAnimationInterval: [2000, 5000] as [number, number],
  /** 待机时触发一次随机走动的随机间隔（毫秒） */
  idleMoveInterval: [4000, 9000] as [number, number],
  /** 每次随机走动的持续时间（毫秒） */
  idleMoveDuration: [300, 800] as [number, number],
  /** 随机走动的速度倍率（相对怪物自身 moveSpeed，比追击慢一点） */
  idleMoveSpeedScale: 0.5,
  /** 随机走动的活动半径（像素）：离停留点超过这个距离就往回走，避免越走越远 */
  wanderRadius: 60,
  /**
   * 击退默认时长（毫秒）：技能击退是场上唯一能推动位置的途径，
   * 技能配置里只写距离时用这个时长换算击退速度（距离 / 时长），改这里可统一调整击退手感
   */
  pushDuration: 200,
};

const monsterData: MonsterData[] = [
  {
    key: "1",
    level: 1,
    icon: "monster/icon/1_00000",
    out: "monster/out/1",
    outOffset: new Vec2(),
    label: "赤焰斗鸡",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "common",
    description: "赤焰斗鸡",
    sellPirce: 0,
    contentSize: new Size(100, 100),
    speedRate: {
      [ACTION.STAND]: 1,
      [ACTION.WALK]: 1,
      [ACTION.RUN]: 1,
      [ACTION.ATTACK_NEAR]: 1,
      [ACTION.ATTACK_SKILL_1]: 1,
      [ACTION.TEST3]: 1,
      [ACTION.ATTACK_FAR]: 1,
      [ACTION.INJURED]: 1,
      [ACTION.A1]: 1,
      [ACTION.DIE]: 1,
      [ACTION.TEST1]: 1,
    },
  },
  {
    key: "2",
    level: 1,
    icon: "monster/icon/2_00000",
    out: "monster/out/2",
    outOffset: new Vec2(),
    label: "金斑雄鹿",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "common",
    description: "金斑雄鹿",
    sellPirce: 0,
    contentSize: new Size(100, 100),
    speedRate: {
      [ACTION.STAND]: 1,
      [ACTION.WALK]: 1,
      [ACTION.RUN]: 1,
      [ACTION.ATTACK_NEAR]: 1,
      [ACTION.ATTACK_SKILL_1]: 1,
      [ACTION.TEST3]: 1,
      [ACTION.ATTACK_FAR]: 1,
      [ACTION.INJURED]: 1,
      [ACTION.A1]: 1,
      [ACTION.DIE]: 1,
      [ACTION.TEST1]: 1,
    },
  },
  {
    key: "3",
    level: 2,
    icon: "monster/icon/3_00000",
    out: "monster/out/3",
    outOffset: new Vec2(),
    label: "干尸行者",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "干尸行者",
    sellPirce: 0,
    contentSize: new Size(50, 100),
    speedRate: {
      [ACTION.STAND]: 1,
      [ACTION.WALK]: 1,
      [ACTION.RUN]: 1,
      [ACTION.ATTACK_NEAR]: 1,
      [ACTION.ATTACK_SKILL_1]: 1,
      [ACTION.TEST3]: 1,
      [ACTION.ATTACK_FAR]: 1,
      [ACTION.INJURED]: 1,
      [ACTION.A1]: 1,
      [ACTION.DIE]: 1,
      [ACTION.TEST1]: 1,
    },
  },
  {
    key: "4",
    level: 2,
    icon: "monster/icon/4_00000",
    out: "monster/out/4",
    outOffset: new Vec2(),
    label: "豺狼人巫师",
    moveSpeed: 2,
    aggressive: true,
    detectRange: 200,
    description: "豺狼人巫师",
    sellPirce: 0,
    contentSize: new Size(100, 100),
    speedRate: {
      [ACTION.STAND]: 1,
      [ACTION.WALK]: 1,
      [ACTION.RUN]: 1,
      [ACTION.ATTACK_NEAR]: 1,
      [ACTION.ATTACK_SKILL_1]: 1,
      [ACTION.TEST3]: 1,
      [ACTION.ATTACK_FAR]: 1,
      [ACTION.INJURED]: 1,
      [ACTION.A1]: 1,
      [ACTION.DIE]: 1,
      [ACTION.TEST1]: 1,
    },
  },
  {
    key: "5",
    level: 2,
    icon: "monster/icon/5_00000",
    out: "monster/out/5",
    outOffset: new Vec2(),
    label: "狮头人术士",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "狮头人术士",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "6",
    level: 2,
    icon: "monster/icon/6_00000",
    out: "monster/out/6",
    outOffset: new Vec2(),
    label: "巨疣蟾蜍",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "巨疣蟾蜍",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "7",
    level: 3,
    icon: "monster/icon/7_00000",
    out: "monster/out/7",
    outOffset: new Vec2(),
    label: "碎骨残骸",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "碎骨残骸",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "8",
    level: 3,
    icon: "monster/icon/8_00000",
    out: "monster/out/8",
    outOffset: new Vec2(),
    label: "牛角骷髅将",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "牛角骷髅将",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "9",
    level: 3,
    icon: "monster/icon/9_00000",
    out: "monster/out/9",
    outOffset: new Vec2(),
    label: "骨锤蛮兵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "骨锤蛮兵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "10",
    level: 4,
    icon: "monster/icon/10_00000",
    out: "monster/out/10",
    outOffset: new Vec2(),
    label: "血赤骷髅",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "血赤骷髅",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "11",
    level: 4,
    icon: "monster/icon/11_00000",
    out: "monster/out/11",
    outOffset: new Vec2(),
    label: "龟甲忍士",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "龟甲忍士",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "12",
    level: 4,
    icon: "monster/icon/12_00000",
    out: "monster/out/12",
    outOffset: new Vec2(),
    label: "雪岭野人",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "雪岭野人",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "13",
    level: 5,
    icon: "monster/icon/13_00000",
    out: "monster/out/13",
    outOffset: new Vec2(),
    label: "黑猿妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黑猿妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "14",
    level: 5,
    icon: "monster/icon/14_00000",
    out: "monster/out/14",
    outOffset: new Vec2(),
    label: "猛犸巨象",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "猛犸巨象",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "15",
    level: 5,
    icon: "monster/icon/15_00000",
    out: "monster/out/15",
    outOffset: new Vec2(),
    label: "黑翼巨蝠",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黑翼巨蝠",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "16",
    level: 5,
    icon: "monster/icon/16_00000",
    out: "monster/out/16",
    outOffset: new Vec2(),
    label: "海螺精",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "海螺精",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "17",
    level: 6,
    icon: "monster/icon/17_00000",
    out: "monster/out/17",
    outOffset: new Vec2(),
    label: "金甲独角仙",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金甲独角仙",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "18",
    level: 6,
    icon: "monster/icon/18_00000",
    out: "monster/out/18",
    outOffset: new Vec2(),
    label: "金翅灵鸟",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金翅灵鸟",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "19",
    level: 6,
    icon: "monster/icon/19_00000",
    out: "monster/out/19",
    outOffset: new Vec2(),
    label: "沙岗蠕虫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "沙岗蠕虫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "20",
    level: 7,
    icon: "monster/icon/20_00000",
    out: "monster/out/20",
    outOffset: new Vec2(),
    label: "野狼",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "野狼",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "21",
    level: 7,
    icon: "monster/icon/21_00000",
    out: "monster/out/21",
    outOffset: new Vec2(),
    label: "盘角羚羊",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "盘角羚羊",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "22",
    level: 7,
    icon: "monster/icon/22_00000",
    out: "monster/out/22",
    outOffset: new Vec2(),
    label: "灰壳蛞蝓",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "灰壳蛞蝓",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "23",
    level: 8,
    icon: "monster/icon/23_00000",
    out: "monster/out/23",
    outOffset: new Vec2(),
    label: "独腿尸兵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "独腿尸兵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "24",
    level: 8,
    icon: "monster/icon/24_00000",
    out: "monster/out/24",
    outOffset: new Vec2(),
    label: "血污行尸",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "血污行尸",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "25",
    level: 8,
    icon: "monster/icon/25_00000",
    out: "monster/out/25",
    outOffset: new Vec2(),
    label: "枯叶飞虫群",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "枯叶飞虫群",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "26",
    level: 8,
    icon: "monster/icon/26_00000",
    out: "monster/out/26",
    outOffset: new Vec2(),
    label: "枯行僧尸",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "枯行僧尸",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "27",
    level: 9,
    icon: "monster/icon/27_00000",
    out: "monster/out/27",
    outOffset: new Vec2(),
    label: "食人妖花",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "食人妖花",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "28",
    level: 9,
    icon: "monster/icon/28_00000",
    out: "monster/out/28",
    outOffset: new Vec2(),
    label: "金环蛇",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金环蛇",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "29",
    level: 9,
    icon: "monster/icon/29_00000",
    out: "monster/out/29",
    outOffset: new Vec2(),
    label: "赤练蛇",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤练蛇",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "30",
    level: 10,
    icon: "monster/icon/30_00000",
    out: "monster/out/30",
    outOffset: new Vec2(),
    label: "枯树妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "枯树妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "31",
    level: 10,
    icon: "monster/icon/31_00000",
    out: "monster/out/31",
    outOffset: new Vec2(),
    label: "蘑菇精",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "蘑菇精",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "32",
    level: 10,
    icon: "monster/icon/32_00000",
    out: "monster/out/32",
    outOffset: new Vec2(),
    label: "黄甲多足虫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黄甲多足虫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "33",
    level: 11,
    icon: "monster/icon/33_00000",
    out: "monster/out/33",
    outOffset: new Vec2(),
    label: "铜甲巨蝎",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "铜甲巨蝎",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "34",
    level: 11,
    icon: "monster/icon/34_00000",
    out: "monster/out/34",
    outOffset: new Vec2(),
    label: "碎尸爬虫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "碎尸爬虫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "35",
    level: 11,
    icon: "monster/icon/35_00000",
    out: "monster/out/35",
    outOffset: new Vec2(),
    label: "赤蜈蚣",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤蜈蚣",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "36",
    level: 11,
    icon: "monster/icon/36_00000",
    out: "monster/out/36",
    outOffset: new Vec2(),
    label: "黄蜂妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黄蜂妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "37",
    level: 12,
    icon: "monster/icon/37_00000",
    out: "monster/out/37",
    outOffset: new Vec2(),
    label: "蜣螂精",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "蜣螂精",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "38",
    level: 12,
    icon: "monster/icon/38_00000",
    out: "monster/out/38",
    outOffset: new Vec2(),
    label: "虾兵怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "虾兵怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "39",
    level: 12,
    icon: "monster/icon/39_00000",
    out: "monster/out/39",
    outOffset: new Vec2(),
    label: "银甲蝎蛉",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "银甲蝎蛉",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "40",
    level: 13,
    icon: "monster/icon/40_00000",
    out: "monster/out/40",
    outOffset: new Vec2(),
    label: "青竹大蜈蚣",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "青竹大蜈蚣",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "41",
    level: 13,
    icon: "monster/icon/41_00000",
    out: "monster/out/41",
    outOffset: new Vec2(),
    label: "金沙傀儡",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金沙傀儡",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "42",
    level: 13,
    icon: "monster/icon/42_00000",
    out: "monster/out/42",
    outOffset: new Vec2(),
    label: "绿袍兽人武者",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "绿袍兽人武者",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "43",
    level: 14,
    icon: "monster/icon/43_00000",
    out: "monster/out/43",
    outOffset: new Vec2(),
    label: "牛角兽人斧手",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "牛角兽人斧手",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "44",
    level: 14,
    icon: "monster/icon/44_00000",
    out: "monster/out/44",
    outOffset: new Vec2(),
    label: "白衣幽魂",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "白衣幽魂",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "45",
    level: 14,
    icon: "monster/icon/45_00000",
    out: "monster/out/45",
    outOffset: new Vec2(),
    label: "幽冥触手魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "幽冥触手魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "46",
    level: 14,
    icon: "monster/icon/46_00000",
    out: "monster/out/46",
    outOffset: new Vec2(),
    label: "金色海星妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金色海星妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "47",
    level: 15,
    icon: "monster/icon/47_00000",
    out: "monster/out/47",
    outOffset: new Vec2(),
    label: "灰毛猩猩兽",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "灰毛猩猩兽",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "48",
    level: 15,
    icon: "monster/icon/48_00000",
    out: "monster/out/48",
    outOffset: new Vec2(),
    label: "车轮骨妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "车轮骨妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "49",
    level: 15,
    icon: "monster/icon/49_00000",
    out: "monster/out/49",
    outOffset: new Vec2(),
    label: "链锤夜叉",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "链锤夜叉",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "50",
    level: 16,
    icon: "monster/icon/50_00000",
    out: "monster/out/50",
    outOffset: new Vec2(),
    label: "赤炎小恶魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤炎小恶魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "51",
    level: 16,
    icon: "monster/icon/51_00000",
    out: "monster/out/51",
    outOffset: new Vec2(),
    label: "双斧狼卫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "双斧狼卫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "52",
    level: 16,
    icon: "monster/icon/52_00000",
    out: "monster/out/52",
    outOffset: new Vec2(),
    label: "绿眼飞蛾妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "绿眼飞蛾妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "53",
    level: 16,
    icon: "monster/icon/53_00000",
    out: "monster/out/53",
    outOffset: new Vec2(),
    label: "滑翔飞蜥",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "滑翔飞蜥",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "54",
    level: 17,
    icon: "monster/icon/54_00000",
    out: "monster/out/54",
    outOffset: new Vec2(),
    label: "坠马骸骑兵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "坠马骸骑兵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "55",
    level: 17,
    icon: "monster/icon/55_00000",
    out: "monster/out/55",
    outOffset: new Vec2(),
    label: "持戟猪首人",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "持戟猪首人",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "56",
    level: 17,
    icon: "monster/icon/56_00000",
    out: "monster/out/56",
    outOffset: new Vec2(),
    label: "雷锤铁卫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "雷锤铁卫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "57",
    level: 18,
    icon: "monster/icon/57_00000",
    out: "monster/out/57",
    outOffset: new Vec2(),
    label: "赤膊狂猿",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤膊狂猿",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "58",
    level: 18,
    icon: "monster/icon/58_00000",
    out: "monster/out/58",
    outOffset: new Vec2(),
    label: "黑熊罴怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黑熊罴怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "59",
    level: 18,
    icon: "monster/icon/59_00000",
    out: "monster/out/59",
    outOffset: new Vec2(),
    label: "赤须龙蜈",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤须龙蜈",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "60",
    level: 19,
    icon: "monster/icon/60_00000",
    out: "monster/out/60",
    outOffset: new Vec2(),
    label: "黑鳞龙裔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黑鳞龙裔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "61",
    level: 19,
    icon: "monster/icon/61_00000",
    out: "monster/out/61",
    outOffset: new Vec2(),
    label: "骨角黄巨魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "骨角黄巨魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "62",
    level: 19,
    icon: "monster/icon/62_00000",
    out: "monster/out/62",
    outOffset: new Vec2(),
    label: "灰肤巨魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "灰肤巨魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "63",
    level: 19,
    icon: "monster/icon/63_00000",
    out: "monster/out/63",
    outOffset: new Vec2(),
    label: "赤鳞怪胎",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤鳞怪胎",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "64",
    level: 20,
    icon: "monster/icon/64_00000",
    out: "monster/out/64",
    outOffset: new Vec2(),
    label: "青鳞怪胎",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "青鳞怪胎",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "65",
    level: 20,
    icon: "monster/icon/65_00000",
    out: "monster/out/65",
    outOffset: new Vec2(),
    label: "紫黑蟹蛛",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "紫黑蟹蛛",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "66",
    level: 20,
    icon: "monster/icon/66_00000",
    out: "monster/out/66",
    outOffset: new Vec2(),
    label: "金斑飞蝎",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金斑飞蝎",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "67",
    level: 21,
    icon: "monster/icon/67_00000",
    out: "monster/out/67",
    outOffset: new Vec2(),
    label: "沙尘鬼",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "沙尘鬼",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "68",
    level: 21,
    icon: "monster/icon/68_00000",
    out: "monster/out/68",
    outOffset: new Vec2(),
    label: "金牛甲士",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金牛甲士",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "69",
    level: 21,
    icon: "monster/icon/69_00000",
    out: "monster/out/69",
    outOffset: new Vec2(),
    label: "紫甲双锤兵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "紫甲双锤兵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "70",
    level: 22,
    icon: "monster/icon/70_00000",
    out: "monster/out/70",
    outOffset: new Vec2(),
    label: "黑甲长斧魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黑甲长斧魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "71",
    level: 22,
    icon: "monster/icon/71_00000",
    out: "monster/out/71",
    outOffset: new Vec2(),
    label: "银甲月刃枪卫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "银甲月刃枪卫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "72",
    level: 22,
    icon: "monster/icon/72_00000",
    out: "monster/out/72",
    outOffset: new Vec2(),
    label: "红袍蛇杖法老",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "红袍蛇杖法老",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "73",
    level: 22,
    icon: "monster/icon/73_00000",
    out: "monster/out/73",
    outOffset: new Vec2(),
    label: "陷坑野牛魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "陷坑野牛魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "74",
    level: 23,
    icon: "monster/icon/74_00000",
    out: "monster/out/74",
    outOffset: new Vec2(),
    label: "土狼妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "土狼妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "75",
    level: 23,
    icon: "monster/icon/75_00000",
    out: "monster/out/75",
    outOffset: new Vec2(),
    label: "青锋刀客",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "青锋刀客",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "76",
    level: 23,
    icon: "monster/icon/76_00000",
    out: "monster/out/76",
    outOffset: new Vec2(),
    label: "青蛙斗士",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "青蛙斗士",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "77",
    level: 24,
    icon: "monster/icon/77_00000",
    out: "monster/out/77",
    outOffset: new Vec2(),
    label: "独眼触手魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "独眼触手魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "78",
    level: 24,
    icon: "monster/icon/78_00000",
    out: "monster/out/78",
    outOffset: new Vec2(),
    label: "碧爪蛛母",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "碧爪蛛母",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "79",
    level: 24,
    icon: "monster/icon/79_00000",
    out: "monster/out/79",
    outOffset: new Vec2(),
    label: "碎金甲兵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "碎金甲兵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "80",
    level: 25,
    icon: "monster/icon/80_00000",
    out: "monster/out/80",
    outOffset: new Vec2(),
    label: "黄袍圣甲虫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黄袍圣甲虫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "81",
    level: 25,
    icon: "monster/icon/81_00000",
    out: "monster/out/81",
    outOffset: new Vec2(),
    label: "黄蜂后",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黄蜂后",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "82",
    level: 25,
    icon: "monster/icon/82_00000",
    out: "monster/out/82",
    outOffset: new Vec2(),
    label: "铁壳蝼蛄",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "铁壳蝼蛄",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "83",
    level: 25,
    icon: "monster/icon/83_00000",
    out: "monster/out/83",
    outOffset: new Vec2(),
    label: "犀甲巨蚁",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "犀甲巨蚁",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "84",
    level: 26,
    icon: "monster/icon/84_00000",
    out: "monster/out/84",
    outOffset: new Vec2(),
    label: "白骨披甲将",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "白骨披甲将",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "85",
    level: 26,
    icon: "monster/icon/85_00000",
    out: "monster/out/85",
    outOffset: new Vec2(),
    label: "焰翅魔将",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "焰翅魔将",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "86",
    level: 26,
    icon: "monster/icon/86_00000",
    out: "monster/out/86",
    outOffset: new Vec2(),
    label: "战旗兽人",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "战旗兽人",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "87",
    level: 27,
    icon: "monster/icon/87_00000",
    out: "monster/out/87",
    outOffset: new Vec2(),
    label: "碎铁石堆怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "碎铁石堆怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "88",
    level: 27,
    icon: "monster/icon/88_00000",
    out: "monster/out/88",
    outOffset: new Vec2(),
    label: "血晶碎块怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "血晶碎块怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "89",
    level: 27,
    icon: "monster/icon/89_00000",
    out: "monster/out/89",
    outOffset: new Vec2(),
    label: "骨翅飞妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "骨翅飞妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "90",
    level: 28,
    icon: "monster/icon/90_00000",
    out: "monster/out/90",
    outOffset: new Vec2(),
    label: "骨爪爬魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "骨爪爬魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "91",
    level: 28,
    icon: "monster/icon/91_00000",
    out: "monster/out/91",
    outOffset: new Vec2(),
    label: "碎石傀儡",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "碎石傀儡",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "92",
    level: 28,
    icon: "monster/icon/92_00000",
    out: "monster/out/92",
    outOffset: new Vec2(),
    label: "妖娆花魁女妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "妖娆花魁女妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "93",
    level: 28,
    icon: "monster/icon/93_00000",
    out: "monster/out/93",
    outOffset: new Vec2(),
    label: "青翼仙子",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "青翼仙子",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "94",
    level: 29,
    icon: "monster/icon/94_00000",
    out: "monster/out/94",
    outOffset: new Vec2(),
    label: "金冠飞刀侠",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金冠飞刀侠",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "95",
    level: 29,
    icon: "monster/icon/95_00000",
    out: "monster/out/95",
    outOffset: new Vec2(),
    label: "金甲持锤武圣",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金甲持锤武圣",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "96",
    level: 29,
    icon: "monster/icon/96_00000",
    out: "monster/out/96",
    outOffset: new Vec2(),
    label: "蓝翼法灵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "蓝翼法灵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "97",
    level: 30,
    icon: "monster/icon/97_00000",
    out: "monster/out/97",
    outOffset: new Vec2(),
    label: "白甲弓手",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "白甲弓手",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "98",
    level: 30,
    icon: "monster/icon/98_00000",
    out: "monster/out/98",
    outOffset: new Vec2(),
    label: "银甲白狼灵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "银甲白狼灵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "99",
    level: 30,
    icon: "monster/icon/99_00000",
    out: "monster/out/99",
    outOffset: new Vec2(),
    label: "枯骨废墟堆",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "枯骨废墟堆",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "100",
    level: 31,
    icon: "monster/icon/100_00000",
    out: "monster/out/100",
    outOffset: new Vec2(),
    label: "白袍行者",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "白袍行者",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "101",
    level: 31,
    icon: "monster/icon/101_00000",
    out: "monster/out/101",
    outOffset: new Vec2(),
    label: "黑铁锁链魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黑铁锁链魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "102",
    level: 31,
    icon: "monster/icon/102_00000",
    out: "monster/out/102",
    outOffset: new Vec2(),
    label: "金斧矮人酋长",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金斧矮人酋长",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "103",
    level: 31,
    icon: "monster/icon/103_00000",
    out: "monster/out/103",
    outOffset: new Vec2(),
    label: "白骨蛇",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "白骨蛇",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "104",
    level: 32,
    icon: "monster/icon/104_00000",
    out: "monster/out/104",
    outOffset: new Vec2(),
    label: "独眼巨魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "独眼巨魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "105",
    level: 32,
    icon: "monster/icon/105_00000",
    out: "monster/out/105",
    outOffset: new Vec2(),
    label: "骨翼蝠魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "骨翼蝠魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "106",
    level: 32,
    icon: "monster/icon/106_00000",
    out: "monster/out/106",
    outOffset: new Vec2(),
    label: "棕毛跳猿兽",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "棕毛跳猿兽",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "107",
    level: 33,
    icon: "monster/icon/107_00000",
    out: "monster/out/107",
    outOffset: new Vec2(),
    label: "白毛狼牙锤怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "白毛狼牙锤怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "108",
    level: 33,
    icon: "monster/icon/108_00000",
    out: "monster/out/108",
    outOffset: new Vec2(),
    label: "电光双鞭将",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "电光双鞭将",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "109",
    level: 33,
    icon: "monster/icon/109_00000",
    out: "monster/out/109",
    outOffset: new Vec2(),
    label: "金冠弯刀卫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金冠弯刀卫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "110",
    level: 33,
    icon: "monster/icon/110_00000",
    out: "monster/out/110",
    outOffset: new Vec2(),
    label: "血蛛后",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "血蛛后",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },

  {
    key: "111",
    level: 34,
    icon: "monster/icon/111_00000",
    out: "monster/out/111",
    outOffset: new Vec2(),
    label: "碎金残兵堆",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "碎金残兵堆",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "112",
    level: 34,
    icon: "monster/icon/112_00000",
    out: "monster/out/112",
    outOffset: new Vec2(),
    label: "骨杖蛮巫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "骨杖蛮巫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "113",
    level: 34,
    icon: "monster/icon/113_00000",
    out: "monster/out/113",
    outOffset: new Vec2(),
    label: "牛角红袍祭司",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "牛角红袍祭司",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "114",
    level: 35,
    icon: "monster/icon/114_00000",
    out: "monster/out/114",
    outOffset: new Vec2(),
    label: "冰晶翼灵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "冰晶翼灵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "115",
    level: 35,
    icon: "monster/icon/115_00000",
    out: "monster/out/115",
    outOffset: new Vec2(),
    label: "赤肌血魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤肌血魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "116",
    level: 35,
    icon: "monster/icon/116_00000",
    out: "monster/out/116",
    outOffset: new Vec2(),
    label: "金环武僧",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金环武僧",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "117",
    level: 36,
    icon: "monster/icon/117_00000",
    out: "monster/out/117",
    outOffset: new Vec2(),
    label: "机关木偶",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "机关木偶",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "118",
    level: 36,
    icon: "monster/icon/118_00000",
    out: "monster/out/118",
    outOffset: new Vec2(),
    label: "红袍披风鬼将",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "红袍披风鬼将",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "119",
    level: 36,
    icon: "monster/icon/119_00000",
    out: "monster/out/119",
    outOffset: new Vec2(),
    label: "悬空剑灵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "悬空剑灵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "120",
    level: 36,
    icon: "monster/icon/120_00000",
    out: "monster/out/120",
    outOffset: new Vec2(),
    label: "金莲法阵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金莲法阵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "121",
    level: 37,
    icon: "monster/icon/121_00000",
    out: "monster/out/121",
    outOffset: new Vec2(),
    label: "断戟残卒堆",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "断戟残卒堆",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "122",
    level: 37,
    icon: "monster/icon/122_00000",
    out: "monster/out/122",
    outOffset: new Vec2(),
    label: "赤凰翔灵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤凰翔灵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "123",
    level: 37,
    icon: "monster/icon/123_00000",
    out: "monster/out/123",
    outOffset: new Vec2(),
    label: "蓝冰晶簇",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "蓝冰晶簇",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "124",
    level: 38,
    icon: "monster/icon/124_00000",
    out: "monster/out/124",
    outOffset: new Vec2(),
    label: "金冠法王",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金冠法王",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "125",
    level: 38,
    icon: "monster/icon/125_00000",
    out: "monster/out/125",
    outOffset: new Vec2(),
    label: "藤蔓树魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "藤蔓树魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "126",
    level: 38,
    icon: "monster/icon/126_00000",
    out: "monster/out/126",
    outOffset: new Vec2(),
    label: "缟素女鬼",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "缟素女鬼",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "127",
    level: 39,
    icon: "monster/icon/127_00000",
    out: "monster/out/127",
    outOffset: new Vec2(),
    label: "巨翼骨蝠王",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "巨翼骨蝠王",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "128",
    level: 39,
    icon: "monster/icon/128_00000",
    out: "monster/out/128",
    outOffset: new Vec2(),
    label: "皮甲猎弓手",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "皮甲猎弓手",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "129",
    level: 39,
    icon: "monster/icon/129_00000",
    out: "monster/out/129",
    outOffset: new Vec2(),
    label: "金甲长枪灵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金甲长枪灵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "130",
    level: 39,
    icon: "monster/icon/130_00000",
    out: "monster/out/130",
    outOffset: new Vec2(),
    label: "双锤牛魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "双锤牛魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "131",
    level: 40,
    icon: "monster/icon/131_00000",
    out: "monster/out/131",
    outOffset: new Vec2(),
    label: "尸骸兵器冢",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "尸骸兵器冢",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "132",
    level: 40,
    icon: "monster/icon/132_00000",
    out: "monster/out/132",
    outOffset: new Vec2(),
    label: "焰发女妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "焰发女妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "133",
    level: 40,
    icon: "monster/icon/133_00000",
    out: "monster/out/133",
    outOffset: new Vec2(),
    label: "金链骷髅阵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金链骷髅阵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "134",
    level: 41,
    icon: "monster/icon/134_00000",
    out: "monster/out/134",
    outOffset: new Vec2(),
    label: "粉晶机关兽",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "粉晶机关兽",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "135",
    level: 41,
    icon: "monster/icon/135_00000",
    out: "monster/out/135",
    outOffset: new Vec2(),
    label: "金蟾精",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金蟾精",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "136",
    level: 41,
    icon: "monster/icon/136_00000",
    out: "monster/out/136",
    outOffset: new Vec2(),
    label: "冰杖法童",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "冰杖法童",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "137",
    level: 42,
    icon: "monster/icon/137_00000",
    out: "monster/out/137",
    outOffset: new Vec2(),
    label: "提灯行商怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "提灯行商怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "138",
    level: 42,
    icon: "monster/icon/138_00000",
    out: "monster/out/138",
    outOffset: new Vec2(),
    label: "绿杖树精",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "绿杖树精",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "139",
    level: 42,
    icon: "monster/icon/139_00000",
    out: "monster/out/139",
    outOffset: new Vec2(),
    label: "双筒火铳魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "双筒火铳魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "140",
    level: 42,
    icon: "monster/icon/140_00000",
    out: "monster/out/140",
    outOffset: new Vec2(),
    label: "白狐少女妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "白狐少女妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "141",
    level: 43,
    icon: "monster/icon/141_00000",
    out: "monster/out/141",
    outOffset: new Vec2(),
    label: "金轮骨僧",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金轮骨僧",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "142",
    level: 43,
    icon: "monster/icon/142_00000",
    out: "monster/out/142",
    outOffset: new Vec2(),
    label: "碧鳞蛟龙",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "碧鳞蛟龙",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "143",
    level: 43,
    icon: "monster/icon/143_00000",
    out: "monster/out/143",
    outOffset: new Vec2(),
    label: "金纹道人",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金纹道人",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "144",
    level: 44,
    icon: "monster/icon/144_00000",
    out: "monster/out/144",
    outOffset: new Vec2(),
    label: "枯骨翼妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "枯骨翼妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "145",
    level: 44,
    icon: "monster/icon/145_00000",
    out: "monster/out/145",
    outOffset: new Vec2(),
    label: "黑棘龙兽",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黑棘龙兽",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "146",
    level: 44,
    icon: "monster/icon/146_00000",
    out: "monster/out/146",
    outOffset: new Vec2(),
    label: "紫电武魂",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "紫电武魂",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "147",
    level: 45,
    icon: "monster/icon/147_00000",
    out: "monster/out/147",
    outOffset: new Vec2(),
    label: "莲台鲛人",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "莲台鲛人",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "148",
    level: 45,
    icon: "monster/icon/148_00000",
    out: "monster/out/148",
    outOffset: new Vec2(),
    label: "血刃狂魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "血刃狂魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "149",
    level: 45,
    icon: "monster/icon/149_00000",
    out: "monster/out/149",
    outOffset: new Vec2(),
    label: "骨幡妖将",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "骨幡妖将",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "150",
    level: 45,
    icon: "monster/icon/150_00000",
    out: "monster/out/150",
    outOffset: new Vec2(),
    label: "翠纹飞蜥",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "翠纹飞蜥",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "151",
    level: 46,
    icon: "monster/icon/151_00000",
    out: "monster/out/151",
    outOffset: new Vec2(),
    label: "血翼蝠群",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "血翼蝠群",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "152",
    level: 46,
    icon: "monster/icon/152_00000",
    out: "monster/out/152",
    outOffset: new Vec2(),
    label: "金鬃瑞狮",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金鬃瑞狮",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "153",
    level: 46,
    icon: "monster/icon/153_00000",
    out: "monster/out/153",
    outOffset: new Vec2(),
    label: "独眼锤魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "独眼锤魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "154",
    level: 47,
    icon: "monster/icon/154_00000",
    out: "monster/out/154",
    outOffset: new Vec2(),
    label: "长尾铁蝎",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "长尾铁蝎",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "155",
    level: 47,
    icon: "monster/icon/155_00000",
    out: "monster/out/155",
    outOffset: new Vec2(),
    label: "血羽战鹰",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "血羽战鹰",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "156",
    level: 47,
    icon: "monster/icon/156_00000",
    out: "monster/out/156",
    outOffset: new Vec2(),
    label: "血雾散魂",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "血雾散魂",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "157",
    level: 47,
    icon: "monster/icon/157_00000",
    out: "monster/out/157",
    outOffset: new Vec2(),
    label: "金甲骁将",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金甲骁将",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "158",
    level: 48,
    icon: "monster/icon/158_00000",
    out: "monster/out/158",
    outOffset: new Vec2(),
    label: "赤尾巨蝎",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤尾巨蝎",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "159",
    level: 48,
    icon: "monster/icon/159_00000",
    out: "monster/out/159",
    outOffset: new Vec2(),
    label: "橙腹长脚蛛",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "橙腹长脚蛛",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "160",
    level: 48,
    icon: "monster/icon/160_00000",
    out: "monster/out/160",
    outOffset: new Vec2(),
    label: "缚链石魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "缚链石魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "161",
    level: 49,
    icon: "monster/icon/161_00000",
    out: "monster/out/161",
    outOffset: new Vec2(),
    label: "伏地金蟾",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "伏地金蟾",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "162",
    level: 49,
    icon: "monster/icon/162_00000",
    out: "monster/out/162",
    outOffset: new Vec2(),
    label: "吐钱金蟾",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "吐钱金蟾",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "163",
    level: 49,
    icon: "monster/icon/163_00000",
    out: "monster/out/163",
    outOffset: new Vec2(),
    label: "倾覆货车怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "倾覆货车怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "164",
    level: 50,
    icon: "monster/icon/164_00000",
    out: "monster/out/164",
    outOffset: new Vec2(),
    label: "翻车货担怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "翻车货担怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "165",
    level: 50,
    icon: "monster/icon/165_00000",
    out: "monster/out/165",
    outOffset: new Vec2(),
    label: "侧翻车厢怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "侧翻车厢怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "166",
    level: 50,
    icon: "monster/icon/166_00000",
    out: "monster/out/166",
    outOffset: new Vec2(),
    label: "攻城战车怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "攻城战车怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "167",
    level: 50,
    icon: "monster/icon/167_00000",
    out: "monster/out/167",
    outOffset: new Vec2(),
    label: "冲车机关怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "冲车机关怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "168",
    level: 51,
    icon: "monster/icon/168_00000",
    out: "monster/out/168",
    outOffset: new Vec2(),
    label: "赤羽斗鸡",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤羽斗鸡",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "169",
    level: 51,
    icon: "monster/icon/169_00000",
    out: "monster/out/169",
    outOffset: new Vec2(),
    label: "金斑幼鹿",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金斑幼鹿",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "170",
    level: 51,
    icon: "monster/icon/170_00000",
    out: "monster/out/170",
    outOffset: new Vec2(),
    label: "枯瘦黄衣行者",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "枯瘦黄衣行者",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "171",
    level: 52,
    icon: "monster/icon/171_00000",
    out: "monster/out/171",
    outOffset: new Vec2(),
    label: "举臂长毛猿",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "举臂长毛猿",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "172",
    level: 52,
    icon: "monster/icon/172_00000",
    out: "monster/out/172",
    outOffset: new Vec2(),
    label: "藤杖猴妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "藤杖猴妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "173",
    level: 52,
    icon: "monster/icon/173_00000",
    out: "monster/out/173",
    outOffset: new Vec2(),
    label: "象鼻地獾",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "象鼻地獾",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "174",
    level: 53,
    icon: "monster/icon/174_00000",
    out: "monster/out/174",
    outOffset: new Vec2(),
    label: "白骨行尸",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "白骨行尸",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "175",
    level: 53,
    icon: "monster/icon/175_00000",
    out: "monster/out/175",
    outOffset: new Vec2(),
    label: "持斧骷髅卫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "持斧骷髅卫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "176",
    level: 53,
    icon: "monster/icon/176_00000",
    out: "monster/out/176",
    outOffset: new Vec2(),
    label: "持锄白毛猿",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "持锄白毛猿",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "177",
    level: 53,
    icon: "monster/icon/177_00000",
    out: "monster/out/177",
    outOffset: new Vec2(),
    label: "血爪夜叉",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "血爪夜叉",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "178",
    level: 54,
    icon: "monster/icon/178_00000",
    out: "monster/out/178",
    outOffset: new Vec2(),
    label: "灰甲蝼蛄",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "灰甲蝼蛄",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "179",
    level: 54,
    icon: "monster/icon/179_00000",
    out: "monster/out/179",
    outOffset: new Vec2(),
    label: "金龟甲虫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金龟甲虫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "180",
    level: 54,
    icon: "monster/icon/180_00000",
    out: "monster/out/180",
    outOffset: new Vec2(),
    label: "金翎鸟灵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金翎鸟灵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "181",
    level: 55,
    icon: "monster/icon/181_00000",
    out: "monster/out/181",
    outOffset: new Vec2(),
    label: "黄斑腐尸",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黄斑腐尸",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "182",
    level: 55,
    icon: "monster/icon/182_00000",
    out: "monster/out/182",
    outOffset: new Vec2(),
    label: "破衲行者",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "破衲行者",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "183",
    level: 55,
    icon: "monster/icon/183_00000",
    out: "monster/out/183",
    outOffset: new Vec2(),
    label: "螺蛳灰虫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "螺蛳灰虫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "184",
    level: 56,
    icon: "monster/icon/184_00000",
    out: "monster/out/184",
    outOffset: new Vec2(),
    label: "金环灵蛇",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金环灵蛇",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "185",
    level: 56,
    icon: "monster/icon/185_00000",
    out: "monster/out/185",
    outOffset: new Vec2(),
    label: "赤信蛇妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "赤信蛇妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "186",
    level: 56,
    icon: "monster/icon/186_00000",
    out: "monster/out/186",
    outOffset: new Vec2(),
    label: "金毛鬃兽",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "金毛鬃兽",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "187",
    level: 56,
    icon: "monster/icon/187_00000",
    out: "monster/out/187",
    outOffset: new Vec2(),
    label: "黄肚蛙将",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "黄肚蛙将",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "188",
    level: 57,
    icon: "monster/icon/188_00000",
    out: "monster/out/188",
    outOffset: new Vec2(),
    label: "骨刺橙蜈蚣",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "骨刺橙蜈蚣",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "189",
    level: 57,
    icon: "monster/icon/189_00000",
    out: "monster/out/189",
    outOffset: new Vec2(),
    label: "银角仙蜕",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "银角仙蜕",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "190",
    level: 57,
    icon: "monster/icon/190_00000",
    out: "monster/out/190",
    outOffset: new Vec2(),
    label: "白骨团怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "白骨团怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "191",
    level: 58,
    icon: "monster/icon/191_00000",
    out: "monster/out/191",
    outOffset: new Vec2(),
    label: "铁甲双钳虫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "铁甲双钳虫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "192",
    level: 58,
    icon: "monster/icon/192_00000",
    out: "monster/out/192",
    outOffset: new Vec2(),
    label: "银针骨虫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "银针骨虫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "193",
    level: 58,
    icon: "monster/icon/193_00000",
    out: "monster/out/193",
    outOffset: new Vec2(),
    label: "泥沼爬行兽",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "泥沼爬行兽",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "194",
    level: 59,
    icon: "monster/icon/194_00000",
    out: "monster/out/194",
    outOffset: new Vec2(),
    label: "石肤鬼王",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "石肤鬼王",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "195",
    level: 59,
    icon: "monster/icon/195_00000",
    out: "monster/out/195",
    outOffset: new Vec2(),
    label: "持叉狼妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "持叉狼妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "196",
    level: 59,
    icon: "monster/icon/196_00000",
    out: "monster/out/196",
    outOffset: new Vec2(),
    label: "骨刺链锤魔",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "骨刺链锤魔",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "197",
    level: 59,
    icon: "monster/icon/197_00000",
    out: "monster/out/197",
    outOffset: new Vec2(),
    label: "血翼魔王",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "血翼魔王",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "198",
    level: 60,
    icon: "monster/icon/198_00000",
    out: "monster/out/198",
    outOffset: new Vec2(),
    label: "坠马铁骨怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "坠马铁骨怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "199",
    level: 60,
    icon: "monster/icon/199_00000",
    out: "monster/out/199",
    outOffset: new Vec2(),
    label: "骨翼小飞龙",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    description: "骨翼小飞龙",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "200",
    level: 10,
    tier: "boss",
    icon: "monster/icon/200_00000",
    out: "monster/out/200",
    outOffset: new Vec2(),
    label: "长尾跳鼠怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "长尾跳鼠怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "201",
    level: 13,
    tier: "boss",
    icon: "monster/icon/201_00000",
    out: "monster/out/201",
    outOffset: new Vec2(),
    label: "白骨弓手",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "白骨弓手",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "202",
    level: 15,
    tier: "boss",
    icon: "monster/icon/202_00000",
    out: "monster/out/202",
    outOffset: new Vec2(),
    label: "铁甲长戟卫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "铁甲长戟卫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "203",
    level: 18,
    tier: "boss",
    icon: "monster/icon/203_00000",
    out: "monster/out/203",
    outOffset: new Vec2(),
    label: "断臂独锤兵",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "断臂独锤兵",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "204",
    level: 20,
    tier: "boss",
    icon: "monster/icon/204_00000",
    out: "monster/out/204",
    outOffset: new Vec2(),
    label: "红肤举锤巨人",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "红肤举锤巨人",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "205",
    level: 23,
    tier: "boss",
    icon: "monster/icon/205_00000",
    out: "monster/out/205",
    outOffset: new Vec2(),
    label: "狼头黑锤妖",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "狼头黑锤妖",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "206",
    level: 25,
    tier: "boss",
    icon: "monster/icon/206_00000",
    out: "monster/out/206",
    outOffset: new Vec2(),
    label: "铁节钢蜈蚣",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "铁节钢蜈蚣",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "207",
    level: 28,
    tier: "boss",
    icon: "monster/icon/207_00000",
    out: "monster/out/207",
    outOffset: new Vec2(),
    label: "雪白羊怪",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "雪白羊怪",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "208",
    level: 30,
    tier: "boss",
    icon: "monster/icon/208_00000",
    out: "monster/out/208",
    outOffset: new Vec2(),
    label: "荆棘刺球兽",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "荆棘刺球兽",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "209",
    level: 33,
    tier: "boss",
    icon: "monster/icon/209_00000",
    out: "monster/out/209",
    outOffset: new Vec2(),
    label: "土黄瘦狐",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "土黄瘦狐",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "210",
    level: 35,
    tier: "boss",
    icon: "monster/icon/210_00000",
    out: "monster/out/210",
    outOffset: new Vec2(),
    label: "白袍布衣道人",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "白袍布衣道人",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "211",
    level: 38,
    tier: "boss",
    icon: "monster/icon/211_00000",
    out: "monster/out/211",
    outOffset: new Vec2(),
    label: "血背金龟虫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "血背金龟虫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "212",
    level: 40,
    tier: "boss",
    icon: "monster/icon/212_00000",
    out: "monster/out/212",
    outOffset: new Vec2(),
    label: "青绿毛毛虫",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "青绿毛毛虫",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "213",
    level: 43,
    tier: "boss",
    icon: "monster/icon/213_00000",
    out: "monster/out/213",
    outOffset: new Vec2(),
    label: "白骨腐尸",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "白骨腐尸",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "214",
    level: 45,
    tier: "boss",
    icon: "monster/icon/214_00000",
    out: "monster/out/214",
    outOffset: new Vec2(),
    label: "铁尾黑蝎",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "铁尾黑蝎",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "215",
    level: 48,
    tier: "boss",
    icon: "monster/icon/215_00000",
    out: "monster/out/215",
    outOffset: new Vec2(),
    label: "褐翼黑蝙蝠",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "褐翼黑蝙蝠",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "216",
    level: 50,
    tier: "boss",
    icon: "monster/icon/216_00000",
    out: "monster/out/216",
    outOffset: new Vec2(),
    label: "银斧圆盾矮人",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "银斧圆盾矮人",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "217",
    level: 53,
    tier: "boss",
    icon: "monster/icon/217_00000",
    out: "monster/out/217",
    outOffset: new Vec2(),
    label: "绿皮蟾人",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "绿皮蟾人",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "218",
    level: 55,
    tier: "boss",
    icon: "monster/icon/218_00000",
    out: "monster/out/218",
    outOffset: new Vec2(),
    label: "金鬃狻猊",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "金鬃狻猊",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "219",
    level: 58,
    tier: "boss",
    icon: "monster/icon/219_00000",
    out: "monster/out/219",
    outOffset: new Vec2(),
    label: "铁钩海盗",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "elite",
    description: "铁钩海盗",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
  {
    key: "220",
    level: 60,
    tier: "boss",
    icon: "monster/icon/220_00000",
    out: "monster/out/220",
    outOffset: new Vec2(),
    label: "牛角石肤巨人",
    moveSpeed: 2,
    aggressive: false,
    detectRange: 200,
    drops: "boss",
    description: "牛角石肤巨人",
    sellPirce: 0,
    contentSize: new Size(),
    speedRate: undefined,
  },
];

/** 怪物配置（key → 配置）：等级取自条目里的 level，属性由 monsterStats(level, tier) 按等级生成 */
export const monsters = new Map<string, MonsterConfig>();
for (const data of monsterData) {
  const { key, tier, ...rest } = data;
  monsters.set(key, { ...monsterStats(data.level, tier), ...rest });
}

export default monsters;
