import { Vec2 } from "cc";
import { MonsterConfig } from "../types/common";

export const monsters = new Map<string, MonsterConfig>();

monsters.set("1", {
    icon: "monster/icon/1",
    in: "monster/in/1",
    inOffset: new Vec2(),
    out: "monster/out/1",
    outOffset: new Vec2(),
    label: "赤焰斗鸡",
    level: 1,
    description: "赤焰斗鸡",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("2", {
    icon: "monster/icon/2",
    in: "monster/in/2",
    inOffset: new Vec2(),
    out: "monster/out/2",
    outOffset: new Vec2(),
    label: "金斑雄鹿",
    level: 1,
    description: "金斑雄鹿",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("3", {
    icon: "monster/icon/3",
    in: "monster/in/3",
    inOffset: new Vec2(),
    out: "monster/out/3",
    outOffset: new Vec2(),
    label: "干尸行者",
    level: 1,
    description: "干尸行者",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("4", {
    icon: "monster/icon/4",
    in: "monster/in/4",
    inOffset: new Vec2(),
    out: "monster/out/4",
    outOffset: new Vec2(),
    label: "豺狼人巫师",
    level: 1,
    description: "豺狼人巫师",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("5", {
    icon: "monster/icon/5",
    in: "monster/in/5",
    inOffset: new Vec2(),
    out: "monster/out/5",
    outOffset: new Vec2(),
    label: "狮头人术士",
    level: 1,
    description: "狮头人术士",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("6", {
    icon: "monster/icon/6",
    in: "monster/in/6",
    inOffset: new Vec2(),
    out: "monster/out/6",
    outOffset: new Vec2(),
    label: "巨疣蟾蜍",
    level: 1,
    description: "巨疣蟾蜍",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("7", {
    icon: "monster/icon/7",
    in: "monster/in/7",
    inOffset: new Vec2(),
    out: "monster/out/7",
    outOffset: new Vec2(),
    label: "碎骨残骸",
    level: 1,
    description: "碎骨残骸",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("8", {
    icon: "monster/icon/8",
    in: "monster/in/8",
    inOffset: new Vec2(),
    out: "monster/out/8",
    outOffset: new Vec2(),
    label: "牛角骷髅将",
    level: 1,
    description: "牛角骷髅将",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("9", {
    icon: "monster/icon/9",
    in: "monster/in/9",
    inOffset: new Vec2(),
    out: "monster/out/9",
    outOffset: new Vec2(),
    label: "骨锤蛮兵",
    level: 1,
    description: "骨锤蛮兵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("10", {
    icon: "monster/icon/10",
    in: "monster/in/10",
    inOffset: new Vec2(),
    out: "monster/out/10",
    outOffset: new Vec2(),
    label: "血赤骷髅",
    level: 1,
    description: "血赤骷髅",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("11", {
    icon: "monster/icon/11",
    in: "monster/in/11",
    inOffset: new Vec2(),
    out: "monster/out/11",
    outOffset: new Vec2(),
    label: "龟甲忍士",
    level: 1,
    description: "龟甲忍士",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("12", {
    icon: "monster/icon/12",
    in: "monster/in/12",
    inOffset: new Vec2(),
    out: "monster/out/12",
    outOffset: new Vec2(),
    label: "雪岭野人",
    level: 1,
    description: "雪岭野人",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("13", {
    icon: "monster/icon/13",
    in: "monster/in/13",
    inOffset: new Vec2(),
    out: "monster/out/13",
    outOffset: new Vec2(),
    label: "黑猿妖",
    level: 1,
    description: "黑猿妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("14", {
    icon: "monster/icon/14",
    in: "monster/in/14",
    inOffset: new Vec2(),
    out: "monster/out/14",
    outOffset: new Vec2(),
    label: "猛犸巨象",
    level: 1,
    description: "猛犸巨象",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("15", {
    icon: "monster/icon/15",
    in: "monster/in/15",
    inOffset: new Vec2(),
    out: "monster/out/15",
    outOffset: new Vec2(),
    label: "黑翼巨蝠",
    level: 1,
    description: "黑翼巨蝠",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("16", {
    icon: "monster/icon/16",
    in: "monster/in/16",
    inOffset: new Vec2(),
    out: "monster/out/16",
    outOffset: new Vec2(),
    label: "海螺精",
    level: 1,
    description: "海螺精",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("17", {
    icon: "monster/icon/17",
    in: "monster/in/17",
    inOffset: new Vec2(),
    out: "monster/out/17",
    outOffset: new Vec2(),
    label: "金甲独角仙",
    level: 1,
    description: "金甲独角仙",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("18", {
    icon: "monster/icon/18",
    in: "monster/in/18",
    inOffset: new Vec2(),
    out: "monster/out/18",
    outOffset: new Vec2(),
    label: "金翅灵鸟",
    level: 1,
    description: "金翅灵鸟",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("19", {
    icon: "monster/icon/19",
    in: "monster/in/19",
    inOffset: new Vec2(),
    out: "monster/out/19",
    outOffset: new Vec2(),
    label: "沙岗蠕虫",
    level: 1,
    description: "沙岗蠕虫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("20", {
    icon: "monster/icon/20",
    in: "monster/in/20",
    inOffset: new Vec2(),
    out: "monster/out/20",
    outOffset: new Vec2(),
    label: "野狼",
    level: 1,
    description: "野狼",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("21", {
    icon: "monster/icon/21",
    in: "monster/in/21",
    inOffset: new Vec2(),
    out: "monster/out/21",
    outOffset: new Vec2(),
    label: "盘角羚羊",
    level: 1,
    description: "盘角羚羊",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("22", {
    icon: "monster/icon/22",
    in: "monster/in/22",
    inOffset: new Vec2(),
    out: "monster/out/22",
    outOffset: new Vec2(),
    label: "灰壳蛞蝓",
    level: 1,
    description: "灰壳蛞蝓",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("23", {
    icon: "monster/icon/23",
    in: "monster/in/23",
    inOffset: new Vec2(),
    out: "monster/out/23",
    outOffset: new Vec2(),
    label: "独腿尸兵",
    level: 1,
    description: "独腿尸兵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("24", {
    icon: "monster/icon/24",
    in: "monster/in/24",
    inOffset: new Vec2(),
    out: "monster/out/24",
    outOffset: new Vec2(),
    label: "血污行尸",
    level: 1,
    description: "血污行尸",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("25", {
    icon: "monster/icon/25",
    in: "monster/in/25",
    inOffset: new Vec2(),
    out: "monster/out/25",
    outOffset: new Vec2(),
    label: "枯叶飞虫群",
    level: 1,
    description: "枯叶飞虫群",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("26", {
    icon: "monster/icon/26",
    in: "monster/in/26",
    inOffset: new Vec2(),
    out: "monster/out/26",
    outOffset: new Vec2(),
    label: "枯行僧尸",
    level: 1,
    description: "枯行僧尸",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("27", {
    icon: "monster/icon/27",
    in: "monster/in/27",
    inOffset: new Vec2(),
    out: "monster/out/27",
    outOffset: new Vec2(),
    label: "食人妖花",
    level: 1,
    description: "食人妖花",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("28", {
    icon: "monster/icon/28",
    in: "monster/in/28",
    inOffset: new Vec2(),
    out: "monster/out/28",
    outOffset: new Vec2(),
    label: "金环蛇",
    level: 1,
    description: "金环蛇",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("29", {
    icon: "monster/icon/29",
    in: "monster/in/29",
    inOffset: new Vec2(),
    out: "monster/out/29",
    outOffset: new Vec2(),
    label: "赤练蛇",
    level: 1,
    description: "赤练蛇",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("30", {
    icon: "monster/icon/30",
    in: "monster/in/30",
    inOffset: new Vec2(),
    out: "monster/out/30",
    outOffset: new Vec2(),
    label: "枯树妖",
    level: 1,
    description: "枯树妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("31", {
    icon: "monster/icon/31",
    in: "monster/in/31",
    inOffset: new Vec2(),
    out: "monster/out/31",
    outOffset: new Vec2(),
    label: "蘑菇精",
    level: 1,
    description: "蘑菇精",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("32", {
    icon: "monster/icon/32",
    in: "monster/in/32",
    inOffset: new Vec2(),
    out: "monster/out/32",
    outOffset: new Vec2(),
    label: "黄甲多足虫",
    level: 1,
    description: "黄甲多足虫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("33", {
    icon: "monster/icon/33",
    in: "monster/in/33",
    inOffset: new Vec2(),
    out: "monster/out/33",
    outOffset: new Vec2(),
    label: "铜甲巨蝎",
    level: 1,
    description: "铜甲巨蝎",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("34", {
    icon: "monster/icon/34",
    in: "monster/in/34",
    inOffset: new Vec2(),
    out: "monster/out/34",
    outOffset: new Vec2(),
    label: "碎尸爬虫",
    level: 1,
    description: "碎尸爬虫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("35", {
    icon: "monster/icon/35",
    in: "monster/in/35",
    inOffset: new Vec2(),
    out: "monster/out/35",
    outOffset: new Vec2(),
    label: "赤蜈蚣",
    level: 1,
    description: "赤蜈蚣",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("36", {
    icon: "monster/icon/36",
    in: "monster/in/36",
    inOffset: new Vec2(),
    out: "monster/out/36",
    outOffset: new Vec2(),
    label: "黄蜂妖",
    level: 1,
    description: "黄蜂妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("37", {
    icon: "monster/icon/37",
    in: "monster/in/37",
    inOffset: new Vec2(),
    out: "monster/out/37",
    outOffset: new Vec2(),
    label: "蜣螂精",
    level: 1,
    description: "蜣螂精",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("38", {
    icon: "monster/icon/38",
    in: "monster/in/38",
    inOffset: new Vec2(),
    out: "monster/out/38",
    outOffset: new Vec2(),
    label: "虾兵怪",
    level: 1,
    description: "虾兵怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("39", {
    icon: "monster/icon/39",
    in: "monster/in/39",
    inOffset: new Vec2(),
    out: "monster/out/39",
    outOffset: new Vec2(),
    label: "银甲蝎蛉",
    level: 1,
    description: "银甲蝎蛉",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("40", {
    icon: "monster/icon/40",
    in: "monster/in/40",
    inOffset: new Vec2(),
    out: "monster/out/40",
    outOffset: new Vec2(),
    label: "青竹大蜈蚣",
    level: 1,
    description: "青竹大蜈蚣",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("41", {
    icon: "monster/icon/41",
    in: "monster/in/41",
    inOffset: new Vec2(),
    out: "monster/out/41",
    outOffset: new Vec2(),
    label: "金沙傀儡",
    level: 1,
    description: "金沙傀儡",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("42", {
    icon: "monster/icon/42",
    in: "monster/in/42",
    inOffset: new Vec2(),
    out: "monster/out/42",
    outOffset: new Vec2(),
    label: "绿袍兽人武者",
    level: 1,
    description: "绿袍兽人武者",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("43", {
    icon: "monster/icon/43",
    in: "monster/in/43",
    inOffset: new Vec2(),
    out: "monster/out/43",
    outOffset: new Vec2(),
    label: "牛角兽人斧手",
    level: 1,
    description: "牛角兽人斧手",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("44", {
    icon: "monster/icon/44",
    in: "monster/in/44",
    inOffset: new Vec2(),
    out: "monster/out/44",
    outOffset: new Vec2(),
    label: "白衣幽魂",
    level: 1,
    description: "白衣幽魂",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("45", {
    icon: "monster/icon/45",
    in: "monster/in/45",
    inOffset: new Vec2(),
    out: "monster/out/45",
    outOffset: new Vec2(),
    label: "幽冥触手魔",
    level: 1,
    description: "幽冥触手魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("46", {
    icon: "monster/icon/46",
    in: "monster/in/46",
    inOffset: new Vec2(),
    out: "monster/out/46",
    outOffset: new Vec2(),
    label: "金色海星妖",
    level: 1,
    description: "金色海星妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("47", {
    icon: "monster/icon/47",
    in: "monster/in/47",
    inOffset: new Vec2(),
    out: "monster/out/47",
    outOffset: new Vec2(),
    label: "灰毛猩猩兽",
    level: 1,
    description: "灰毛猩猩兽",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("48", {
    icon: "monster/icon/48",
    in: "monster/in/48",
    inOffset: new Vec2(),
    out: "monster/out/48",
    outOffset: new Vec2(),
    label: "车轮骨妖",
    level: 1,
    description: "车轮骨妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("49", {
    icon: "monster/icon/49",
    in: "monster/in/49",
    inOffset: new Vec2(),
    out: "monster/out/49",
    outOffset: new Vec2(),
    label: "链锤夜叉",
    level: 1,
    description: "链锤夜叉",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("50", {
    icon: "monster/icon/50",
    in: "monster/in/50",
    inOffset: new Vec2(),
    out: "monster/out/50",
    outOffset: new Vec2(),
    label: "赤炎小恶魔",
    level: 1,
    description: "赤炎小恶魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("51", {
    icon: "monster/icon/51",
    in: "monster/in/51",
    inOffset: new Vec2(),
    out: "monster/out/51",
    outOffset: new Vec2(),
    label: "双斧狼卫",
    level: 1,
    description: "双斧狼卫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("52", {
    icon: "monster/icon/52",
    in: "monster/in/52",
    inOffset: new Vec2(),
    out: "monster/out/52",
    outOffset: new Vec2(),
    label: "绿眼飞蛾妖",
    level: 1,
    description: "绿眼飞蛾妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("53", {
    icon: "monster/icon/53",
    in: "monster/in/53",
    inOffset: new Vec2(),
    out: "monster/out/53",
    outOffset: new Vec2(),
    label: "滑翔飞蜥",
    level: 1,
    description: "滑翔飞蜥",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("54", {
    icon: "monster/icon/54",
    in: "monster/in/54",
    inOffset: new Vec2(),
    out: "monster/out/54",
    outOffset: new Vec2(),
    label: "坠马骸骑兵",
    level: 1,
    description: "坠马骸骑兵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("55", {
    icon: "monster/icon/55",
    in: "monster/in/55",
    inOffset: new Vec2(),
    out: "monster/out/55",
    outOffset: new Vec2(),
    label: "持戟猪首人",
    level: 1,
    description: "持戟猪首人",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("56", {
    icon: "monster/icon/56",
    in: "monster/in/56",
    inOffset: new Vec2(),
    out: "monster/out/56",
    outOffset: new Vec2(),
    label: "雷锤铁卫",
    level: 1,
    description: "雷锤铁卫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("57", {
    icon: "monster/icon/57",
    in: "monster/in/57",
    inOffset: new Vec2(),
    out: "monster/out/57",
    outOffset: new Vec2(),
    label: "赤膊狂猿",
    level: 1,
    description: "赤膊狂猿",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("58", {
    icon: "monster/icon/58",
    in: "monster/in/58",
    inOffset: new Vec2(),
    out: "monster/out/58",
    outOffset: new Vec2(),
    label: "黑熊罴怪",
    level: 1,
    description: "黑熊罴怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("59", {
    icon: "monster/icon/59",
    in: "monster/in/59",
    inOffset: new Vec2(),
    out: "monster/out/59",
    outOffset: new Vec2(),
    label: "赤须龙蜈",
    level: 1,
    description: "赤须龙蜈",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("60", {
    icon: "monster/icon/60",
    in: "monster/in/60",
    inOffset: new Vec2(),
    out: "monster/out/60",
    outOffset: new Vec2(),
    label: "黑鳞龙裔",
    level: 1,
    description: "黑鳞龙裔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("61", {
    icon: "monster/icon/61",
    in: "monster/in/61",
    inOffset: new Vec2(),
    out: "monster/out/61",
    outOffset: new Vec2(),
    label: "骨角黄巨魔",
    level: 1,
    description: "骨角黄巨魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("62", {
    icon: "monster/icon/62",
    in: "monster/in/62",
    inOffset: new Vec2(),
    out: "monster/out/62",
    outOffset: new Vec2(),
    label: "灰肤巨魔",
    level: 1,
    description: "灰肤巨魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("63", {
    icon: "monster/icon/63",
    in: "monster/in/63",
    inOffset: new Vec2(),
    out: "monster/out/63",
    outOffset: new Vec2(),
    label: "赤鳞怪胎",
    level: 1,
    description: "赤鳞怪胎",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("64", {
    icon: "monster/icon/64",
    in: "monster/in/64",
    inOffset: new Vec2(),
    out: "monster/out/64",
    outOffset: new Vec2(),
    label: "青鳞怪胎",
    level: 1,
    description: "青鳞怪胎",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("65", {
    icon: "monster/icon/65",
    in: "monster/in/65",
    inOffset: new Vec2(),
    out: "monster/out/65",
    outOffset: new Vec2(),
    label: "紫黑蟹蛛",
    level: 1,
    description: "紫黑蟹蛛",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("66", {
    icon: "monster/icon/66",
    in: "monster/in/66",
    inOffset: new Vec2(),
    out: "monster/out/66",
    outOffset: new Vec2(),
    label: "金斑飞蝎",
    level: 1,
    description: "金斑飞蝎",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("67", {
    icon: "monster/icon/67",
    in: "monster/in/67",
    inOffset: new Vec2(),
    out: "monster/out/67",
    outOffset: new Vec2(),
    label: "沙尘鬼",
    level: 1,
    description: "沙尘鬼",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("68", {
    icon: "monster/icon/68",
    in: "monster/in/68",
    inOffset: new Vec2(),
    out: "monster/out/68",
    outOffset: new Vec2(),
    label: "金牛甲士",
    level: 1,
    description: "金牛甲士",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("69", {
    icon: "monster/icon/69",
    in: "monster/in/69",
    inOffset: new Vec2(),
    out: "monster/out/69",
    outOffset: new Vec2(),
    label: "紫甲双锤兵",
    level: 1,
    description: "紫甲双锤兵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("70", {
    icon: "monster/icon/70",
    in: "monster/in/70",
    inOffset: new Vec2(),
    out: "monster/out/70",
    outOffset: new Vec2(),
    label: "黑甲长斧魔",
    level: 1,
    description: "黑甲长斧魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("71", {
    icon: "monster/icon/71",
    in: "monster/in/71",
    inOffset: new Vec2(),
    out: "monster/out/71",
    outOffset: new Vec2(),
    label: "银甲月刃枪卫",
    level: 1,
    description: "银甲月刃枪卫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("72", {
    icon: "monster/icon/72",
    in: "monster/in/72",
    inOffset: new Vec2(),
    out: "monster/out/72",
    outOffset: new Vec2(),
    label: "红袍蛇杖法老",
    level: 1,
    description: "红袍蛇杖法老",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("73", {
    icon: "monster/icon/73",
    in: "monster/in/73",
    inOffset: new Vec2(),
    out: "monster/out/73",
    outOffset: new Vec2(),
    label: "陷坑野牛魔",
    level: 1,
    description: "陷坑野牛魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("74", {
    icon: "monster/icon/74",
    in: "monster/in/74",
    inOffset: new Vec2(),
    out: "monster/out/74",
    outOffset: new Vec2(),
    label: "土狼妖",
    level: 1,
    description: "土狼妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("75", {
    icon: "monster/icon/75",
    in: "monster/in/75",
    inOffset: new Vec2(),
    out: "monster/out/75",
    outOffset: new Vec2(),
    label: "青锋刀客",
    level: 1,
    description: "青锋刀客",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("76", {
    icon: "monster/icon/76",
    in: "monster/in/76",
    inOffset: new Vec2(),
    out: "monster/out/76",
    outOffset: new Vec2(),
    label: "青蛙斗士",
    level: 1,
    description: "青蛙斗士",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("77", {
    icon: "monster/icon/77",
    in: "monster/in/77",
    inOffset: new Vec2(),
    out: "monster/out/77",
    outOffset: new Vec2(),
    label: "独眼触手魔",
    level: 1,
    description: "独眼触手魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("78", {
    icon: "monster/icon/78",
    in: "monster/in/78",
    inOffset: new Vec2(),
    out: "monster/out/78",
    outOffset: new Vec2(),
    label: "碧爪蛛母",
    level: 1,
    description: "碧爪蛛母",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("79", {
    icon: "monster/icon/79",
    in: "monster/in/79",
    inOffset: new Vec2(),
    out: "monster/out/79",
    outOffset: new Vec2(),
    label: "碎金甲兵",
    level: 1,
    description: "碎金甲兵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("80", {
    icon: "monster/icon/80",
    in: "monster/in/80",
    inOffset: new Vec2(),
    out: "monster/out/80",
    outOffset: new Vec2(),
    label: "黄袍圣甲虫",
    level: 1,
    description: "黄袍圣甲虫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("81", {
    icon: "monster/icon/81",
    in: "monster/in/81",
    inOffset: new Vec2(),
    out: "monster/out/81",
    outOffset: new Vec2(),
    label: "黄蜂后",
    level: 1,
    description: "黄蜂后",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("82", {
    icon: "monster/icon/82",
    in: "monster/in/82",
    inOffset: new Vec2(),
    out: "monster/out/82",
    outOffset: new Vec2(),
    label: "铁壳蝼蛄",
    level: 1,
    description: "铁壳蝼蛄",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("83", {
    icon: "monster/icon/83",
    in: "monster/in/83",
    inOffset: new Vec2(),
    out: "monster/out/83",
    outOffset: new Vec2(),
    label: "犀甲巨蚁",
    level: 1,
    description: "犀甲巨蚁",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("84", {
    icon: "monster/icon/84",
    in: "monster/in/84",
    inOffset: new Vec2(),
    out: "monster/out/84",
    outOffset: new Vec2(),
    label: "白骨披甲将",
    level: 1,
    description: "白骨披甲将",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("85", {
    icon: "monster/icon/85",
    in: "monster/in/85",
    inOffset: new Vec2(),
    out: "monster/out/85",
    outOffset: new Vec2(),
    label: "焰翅魔将",
    level: 1,
    description: "焰翅魔将",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("86", {
    icon: "monster/icon/86",
    in: "monster/in/86",
    inOffset: new Vec2(),
    out: "monster/out/86",
    outOffset: new Vec2(),
    label: "战旗兽人",
    level: 1,
    description: "战旗兽人",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("87", {
    icon: "monster/icon/87",
    in: "monster/in/87",
    inOffset: new Vec2(),
    out: "monster/out/87",
    outOffset: new Vec2(),
    label: "碎铁石堆怪",
    level: 1,
    description: "碎铁石堆怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("88", {
    icon: "monster/icon/88",
    in: "monster/in/88",
    inOffset: new Vec2(),
    out: "monster/out/88",
    outOffset: new Vec2(),
    label: "血晶碎块怪",
    level: 1,
    description: "血晶碎块怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("89", {
    icon: "monster/icon/89",
    in: "monster/in/89",
    inOffset: new Vec2(),
    out: "monster/out/89",
    outOffset: new Vec2(),
    label: "骨翅飞妖",
    level: 1,
    description: "骨翅飞妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("90", {
    icon: "monster/icon/90",
    in: "monster/in/90",
    inOffset: new Vec2(),
    out: "monster/out/90",
    outOffset: new Vec2(),
    label: "骨爪爬魔",
    level: 1,
    description: "骨爪爬魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("91", {
    icon: "monster/icon/91",
    in: "monster/in/91",
    inOffset: new Vec2(),
    out: "monster/out/91",
    outOffset: new Vec2(),
    label: "碎石傀儡",
    level: 1,
    description: "碎石傀儡",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("92", {
    icon: "monster/icon/92",
    in: "monster/in/92",
    inOffset: new Vec2(),
    out: "monster/out/92",
    outOffset: new Vec2(),
    label: "妖娆花魁女妖",
    level: 1,
    description: "妖娆花魁女妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("93", {
    icon: "monster/icon/93",
    in: "monster/in/93",
    inOffset: new Vec2(),
    out: "monster/out/93",
    outOffset: new Vec2(),
    label: "青翼仙子",
    level: 1,
    description: "青翼仙子",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("94", {
    icon: "monster/icon/94",
    in: "monster/in/94",
    inOffset: new Vec2(),
    out: "monster/out/94",
    outOffset: new Vec2(),
    label: "金冠飞刀侠",
    level: 1,
    description: "金冠飞刀侠",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("95", {
    icon: "monster/icon/95",
    in: "monster/in/95",
    inOffset: new Vec2(),
    out: "monster/out/95",
    outOffset: new Vec2(),
    label: "金甲持锤武圣",
    level: 1,
    description: "金甲持锤武圣",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("96", {
    icon: "monster/icon/96",
    in: "monster/in/96",
    inOffset: new Vec2(),
    out: "monster/out/96",
    outOffset: new Vec2(),
    label: "蓝翼法灵",
    level: 1,
    description: "蓝翼法灵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("97", {
    icon: "monster/icon/97",
    in: "monster/in/97",
    inOffset: new Vec2(),
    out: "monster/out/97",
    outOffset: new Vec2(),
    label: "白甲弓手",
    level: 1,
    description: "白甲弓手",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("98", {
    icon: "monster/icon/98",
    in: "monster/in/98",
    inOffset: new Vec2(),
    out: "monster/out/98",
    outOffset: new Vec2(),
    label: "银甲白狼灵",
    level: 1,
    description: "银甲白狼灵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("99", {
    icon: "monster/icon/99",
    in: "monster/in/99",
    inOffset: new Vec2(),
    out: "monster/out/99",
    outOffset: new Vec2(),
    label: "枯骨废墟堆",
    level: 1,
    description: "枯骨废墟堆",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("100", {
    icon: "monster/icon/100",
    in: "monster/in/100",
    inOffset: new Vec2(),
    out: "monster/out/100",
    outOffset: new Vec2(),
    label: "白袍行者",
    level: 1,
    description: "白袍行者",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("101", {
    icon: "monster/icon/101",
    in: "monster/in/101",
    inOffset: new Vec2(),
    out: "monster/out/101",
    outOffset: new Vec2(),
    label: "黑铁锁链魔",
    level: 1,
    description: "黑铁锁链魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("102", {
    icon: "monster/icon/102",
    in: "monster/in/102",
    inOffset: new Vec2(),
    out: "monster/out/102",
    outOffset: new Vec2(),
    label: "金斧矮人酋长",
    level: 1,
    description: "金斧矮人酋长",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("103", {
    icon: "monster/icon/103",
    in: "monster/in/103",
    inOffset: new Vec2(),
    out: "monster/out/103",
    outOffset: new Vec2(),
    label: "白骨蛇",
    level: 1,
    description: "白骨蛇",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("104", {
    icon: "monster/icon/104",
    in: "monster/in/104",
    inOffset: new Vec2(),
    out: "monster/out/104",
    outOffset: new Vec2(),
    label: "独眼巨魔",
    level: 1,
    description: "独眼巨魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("105", {
    icon: "monster/icon/105",
    in: "monster/in/105",
    inOffset: new Vec2(),
    out: "monster/out/105",
    outOffset: new Vec2(),
    label: "骨翼蝠魔",
    level: 1,
    description: "骨翼蝠魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("106", {
    icon: "monster/icon/106",
    in: "monster/in/106",
    inOffset: new Vec2(),
    out: "monster/out/106",
    outOffset: new Vec2(),
    label: "棕毛跳猿兽",
    level: 1,
    description: "棕毛跳猿兽",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("107", {
    icon: "monster/icon/107",
    in: "monster/in/107",
    inOffset: new Vec2(),
    out: "monster/out/107",
    outOffset: new Vec2(),
    label: "白毛狼牙锤怪",
    level: 1,
    description: "白毛狼牙锤怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("108", {
    icon: "monster/icon/108",
    in: "monster/in/108",
    inOffset: new Vec2(),
    out: "monster/out/108",
    outOffset: new Vec2(),
    label: "电光双鞭将",
    level: 1,
    description: "电光双鞭将",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("109", {
    icon: "monster/icon/109",
    in: "monster/in/109",
    inOffset: new Vec2(),
    out: "monster/out/109",
    outOffset: new Vec2(),
    label: "金冠弯刀卫",
    level: 1,
    description: "金冠弯刀卫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("110", {
    icon: "monster/icon/110",
    in: "monster/in/110",
    inOffset: new Vec2(),
    out: "monster/out/110",
    outOffset: new Vec2(),
    label: "血蛛后",
    level: 1,
    description: "血蛛后",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("111", {
    icon: "monster/icon/111",
    in: "monster/in/111",
    inOffset: new Vec2(),
    out: "monster/out/111",
    outOffset: new Vec2(),
    label: "碎金残兵堆",
    level: 1,
    description: "碎金残兵堆",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("112", {
    icon: "monster/icon/112",
    in: "monster/in/112",
    inOffset: new Vec2(),
    out: "monster/out/112",
    outOffset: new Vec2(),
    label: "骨杖蛮巫",
    level: 1,
    description: "骨杖蛮巫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("113", {
    icon: "monster/icon/113",
    in: "monster/in/113",
    inOffset: new Vec2(),
    out: "monster/out/113",
    outOffset: new Vec2(),
    label: "牛角红袍祭司",
    level: 1,
    description: "牛角红袍祭司",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("114", {
    icon: "monster/icon/114",
    in: "monster/in/114",
    inOffset: new Vec2(),
    out: "monster/out/114",
    outOffset: new Vec2(),
    label: "冰晶翼灵",
    level: 1,
    description: "冰晶翼灵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("115", {
    icon: "monster/icon/115",
    in: "monster/in/115",
    inOffset: new Vec2(),
    out: "monster/out/115",
    outOffset: new Vec2(),
    label: "赤肌血魔",
    level: 1,
    description: "赤肌血魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("116", {
    icon: "monster/icon/116",
    in: "monster/in/116",
    inOffset: new Vec2(),
    out: "monster/out/116",
    outOffset: new Vec2(),
    label: "金环武僧",
    level: 1,
    description: "金环武僧",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("117", {
    icon: "monster/icon/117",
    in: "monster/in/117",
    inOffset: new Vec2(),
    out: "monster/out/117",
    outOffset: new Vec2(),
    label: "机关木偶",
    level: 1,
    description: "机关木偶",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("118", {
    icon: "monster/icon/118",
    in: "monster/in/118",
    inOffset: new Vec2(),
    out: "monster/out/118",
    outOffset: new Vec2(),
    label: "红袍披风鬼将",
    level: 1,
    description: "红袍披风鬼将",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("119", {
    icon: "monster/icon/119",
    in: "monster/in/119",
    inOffset: new Vec2(),
    out: "monster/out/119",
    outOffset: new Vec2(),
    label: "悬空剑灵",
    level: 1,
    description: "悬空剑灵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("120", {
    icon: "monster/icon/120",
    in: "monster/in/120",
    inOffset: new Vec2(),
    out: "monster/out/120",
    outOffset: new Vec2(),
    label: "金莲法阵",
    level: 1,
    description: "金莲法阵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("121", {
    icon: "monster/icon/121",
    in: "monster/in/121",
    inOffset: new Vec2(),
    out: "monster/out/121",
    outOffset: new Vec2(),
    label: "断戟残卒堆",
    level: 1,
    description: "断戟残卒堆",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("122", {
    icon: "monster/icon/122",
    in: "monster/in/122",
    inOffset: new Vec2(),
    out: "monster/out/122",
    outOffset: new Vec2(),
    label: "赤凰翔灵",
    level: 1,
    description: "赤凰翔灵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("123", {
    icon: "monster/icon/123",
    in: "monster/in/123",
    inOffset: new Vec2(),
    out: "monster/out/123",
    outOffset: new Vec2(),
    label: "蓝冰晶簇",
    level: 1,
    description: "蓝冰晶簇",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("124", {
    icon: "monster/icon/124",
    in: "monster/in/124",
    inOffset: new Vec2(),
    out: "monster/out/124",
    outOffset: new Vec2(),
    label: "金冠法王",
    level: 1,
    description: "金冠法王",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("125", {
    icon: "monster/icon/125",
    in: "monster/in/125",
    inOffset: new Vec2(),
    out: "monster/out/125",
    outOffset: new Vec2(),
    label: "藤蔓树魔",
    level: 1,
    description: "藤蔓树魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("126", {
    icon: "monster/icon/126",
    in: "monster/in/126",
    inOffset: new Vec2(),
    out: "monster/out/126",
    outOffset: new Vec2(),
    label: "缟素女鬼",
    level: 1,
    description: "缟素女鬼",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("127", {
    icon: "monster/icon/127",
    in: "monster/in/127",
    inOffset: new Vec2(),
    out: "monster/out/127",
    outOffset: new Vec2(),
    label: "巨翼骨蝠王",
    level: 1,
    description: "巨翼骨蝠王",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("128", {
    icon: "monster/icon/128",
    in: "monster/in/128",
    inOffset: new Vec2(),
    out: "monster/out/128",
    outOffset: new Vec2(),
    label: "皮甲猎弓手",
    level: 1,
    description: "皮甲猎弓手",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("129", {
    icon: "monster/icon/129",
    in: "monster/in/129",
    inOffset: new Vec2(),
    out: "monster/out/129",
    outOffset: new Vec2(),
    label: "金甲长枪灵",
    level: 1,
    description: "金甲长枪灵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("130", {
    icon: "monster/icon/130",
    in: "monster/in/130",
    inOffset: new Vec2(),
    out: "monster/out/130",
    outOffset: new Vec2(),
    label: "双锤牛魔",
    level: 1,
    description: "双锤牛魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("131", {
    icon: "monster/icon/131",
    in: "monster/in/131",
    inOffset: new Vec2(),
    out: "monster/out/131",
    outOffset: new Vec2(),
    label: "尸骸兵器冢",
    level: 1,
    description: "尸骸兵器冢",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("132", {
    icon: "monster/icon/132",
    in: "monster/in/132",
    inOffset: new Vec2(),
    out: "monster/out/132",
    outOffset: new Vec2(),
    label: "焰发女妖",
    level: 1,
    description: "焰发女妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("133", {
    icon: "monster/icon/133",
    in: "monster/in/133",
    inOffset: new Vec2(),
    out: "monster/out/133",
    outOffset: new Vec2(),
    label: "金链骷髅阵",
    level: 1,
    description: "金链骷髅阵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("134", {
    icon: "monster/icon/134",
    in: "monster/in/134",
    inOffset: new Vec2(),
    out: "monster/out/134",
    outOffset: new Vec2(),
    label: "粉晶机关兽",
    level: 1,
    description: "粉晶机关兽",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("135", {
    icon: "monster/icon/135",
    in: "monster/in/135",
    inOffset: new Vec2(),
    out: "monster/out/135",
    outOffset: new Vec2(),
    label: "金蟾精",
    level: 1,
    description: "金蟾精",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("136", {
    icon: "monster/icon/136",
    in: "monster/in/136",
    inOffset: new Vec2(),
    out: "monster/out/136",
    outOffset: new Vec2(),
    label: "冰杖法童",
    level: 1,
    description: "冰杖法童",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("137", {
    icon: "monster/icon/137",
    in: "monster/in/137",
    inOffset: new Vec2(),
    out: "monster/out/137",
    outOffset: new Vec2(),
    label: "提灯行商怪",
    level: 1,
    description: "提灯行商怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("138", {
    icon: "monster/icon/138",
    in: "monster/in/138",
    inOffset: new Vec2(),
    out: "monster/out/138",
    outOffset: new Vec2(),
    label: "绿杖树精",
    level: 1,
    description: "绿杖树精",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("139", {
    icon: "monster/icon/139",
    in: "monster/in/139",
    inOffset: new Vec2(),
    out: "monster/out/139",
    outOffset: new Vec2(),
    label: "双筒火铳魔",
    level: 1,
    description: "双筒火铳魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("140", {
    icon: "monster/icon/140",
    in: "monster/in/140",
    inOffset: new Vec2(),
    out: "monster/out/140",
    outOffset: new Vec2(),
    label: "白狐少女妖",
    level: 1,
    description: "白狐少女妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("141", {
    icon: "monster/icon/141",
    in: "monster/in/141",
    inOffset: new Vec2(),
    out: "monster/out/141",
    outOffset: new Vec2(),
    label: "金轮骨僧",
    level: 1,
    description: "金轮骨僧",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("142", {
    icon: "monster/icon/142",
    in: "monster/in/142",
    inOffset: new Vec2(),
    out: "monster/out/142",
    outOffset: new Vec2(),
    label: "碧鳞蛟龙",
    level: 1,
    description: "碧鳞蛟龙",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("143", {
    icon: "monster/icon/143",
    in: "monster/in/143",
    inOffset: new Vec2(),
    out: "monster/out/143",
    outOffset: new Vec2(),
    label: "金纹道人",
    level: 1,
    description: "金纹道人",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("144", {
    icon: "monster/icon/144",
    in: "monster/in/144",
    inOffset: new Vec2(),
    out: "monster/out/144",
    outOffset: new Vec2(),
    label: "枯骨翼妖",
    level: 1,
    description: "枯骨翼妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("145", {
    icon: "monster/icon/145",
    in: "monster/in/145",
    inOffset: new Vec2(),
    out: "monster/out/145",
    outOffset: new Vec2(),
    label: "黑棘龙兽",
    level: 1,
    description: "黑棘龙兽",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("146", {
    icon: "monster/icon/146",
    in: "monster/in/146",
    inOffset: new Vec2(),
    out: "monster/out/146",
    outOffset: new Vec2(),
    label: "紫电武魂",
    level: 1,
    description: "紫电武魂",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("147", {
    icon: "monster/icon/147",
    in: "monster/in/147",
    inOffset: new Vec2(),
    out: "monster/out/147",
    outOffset: new Vec2(),
    label: "莲台鲛人",
    level: 1,
    description: "莲台鲛人",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("148", {
    icon: "monster/icon/148",
    in: "monster/in/148",
    inOffset: new Vec2(),
    out: "monster/out/148",
    outOffset: new Vec2(),
    label: "血刃狂魔",
    level: 1,
    description: "血刃狂魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("149", {
    icon: "monster/icon/149",
    in: "monster/in/149",
    inOffset: new Vec2(),
    out: "monster/out/149",
    outOffset: new Vec2(),
    label: "骨幡妖将",
    level: 1,
    description: "骨幡妖将",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("150", {
    icon: "monster/icon/150",
    in: "monster/in/150",
    inOffset: new Vec2(),
    out: "monster/out/150",
    outOffset: new Vec2(),
    label: "翠纹飞蜥",
    level: 1,
    description: "翠纹飞蜥",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("151", {
    icon: "monster/icon/151",
    in: "monster/in/151",
    inOffset: new Vec2(),
    out: "monster/out/151",
    outOffset: new Vec2(),
    label: "血翼蝠群",
    level: 1,
    description: "血翼蝠群",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("152", {
    icon: "monster/icon/152",
    in: "monster/in/152",
    inOffset: new Vec2(),
    out: "monster/out/152",
    outOffset: new Vec2(),
    label: "金鬃瑞狮",
    level: 1,
    description: "金鬃瑞狮",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("153", {
    icon: "monster/icon/153",
    in: "monster/in/153",
    inOffset: new Vec2(),
    out: "monster/out/153",
    outOffset: new Vec2(),
    label: "独眼锤魔",
    level: 1,
    description: "独眼锤魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("154", {
    icon: "monster/icon/154",
    in: "monster/in/154",
    inOffset: new Vec2(),
    out: "monster/out/154",
    outOffset: new Vec2(),
    label: "长尾铁蝎",
    level: 1,
    description: "长尾铁蝎",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("155", {
    icon: "monster/icon/155",
    in: "monster/in/155",
    inOffset: new Vec2(),
    out: "monster/out/155",
    outOffset: new Vec2(),
    label: "血羽战鹰",
    level: 1,
    description: "血羽战鹰",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("156", {
    icon: "monster/icon/156",
    in: "monster/in/156",
    inOffset: new Vec2(),
    out: "monster/out/156",
    outOffset: new Vec2(),
    label: "血雾散魂",
    level: 1,
    description: "血雾散魂",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("157", {
    icon: "monster/icon/157",
    in: "monster/in/157",
    inOffset: new Vec2(),
    out: "monster/out/157",
    outOffset: new Vec2(),
    label: "金甲骁将",
    level: 1,
    description: "金甲骁将",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("158", {
    icon: "monster/icon/158",
    in: "monster/in/158",
    inOffset: new Vec2(),
    out: "monster/out/158",
    outOffset: new Vec2(),
    label: "赤尾巨蝎",
    level: 1,
    description: "赤尾巨蝎",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("159", {
    icon: "monster/icon/159",
    in: "monster/in/159",
    inOffset: new Vec2(),
    out: "monster/out/159",
    outOffset: new Vec2(),
    label: "橙腹长脚蛛",
    level: 1,
    description: "橙腹长脚蛛",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("160", {
    icon: "monster/icon/160",
    in: "monster/in/160",
    inOffset: new Vec2(),
    out: "monster/out/160",
    outOffset: new Vec2(),
    label: "缚链石魔",
    level: 1,
    description: "缚链石魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("161", {
    icon: "monster/icon/161",
    in: "monster/in/161",
    inOffset: new Vec2(),
    out: "monster/out/161",
    outOffset: new Vec2(),
    label: "伏地金蟾",
    level: 1,
    description: "伏地金蟾",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("162", {
    icon: "monster/icon/162",
    in: "monster/in/162",
    inOffset: new Vec2(),
    out: "monster/out/162",
    outOffset: new Vec2(),
    label: "吐钱金蟾",
    level: 1,
    description: "吐钱金蟾",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("163", {
    icon: "monster/icon/163",
    in: "monster/in/163",
    inOffset: new Vec2(),
    out: "monster/out/163",
    outOffset: new Vec2(),
    label: "倾覆货车怪",
    level: 1,
    description: "倾覆货车怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("164", {
    icon: "monster/icon/164",
    in: "monster/in/164",
    inOffset: new Vec2(),
    out: "monster/out/164",
    outOffset: new Vec2(),
    label: "翻车货担怪",
    level: 1,
    description: "翻车货担怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("165", {
    icon: "monster/icon/165",
    in: "monster/in/165",
    inOffset: new Vec2(),
    out: "monster/out/165",
    outOffset: new Vec2(),
    label: "侧翻车厢怪",
    level: 1,
    description: "侧翻车厢怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("166", {
    icon: "monster/icon/166",
    in: "monster/in/166",
    inOffset: new Vec2(),
    out: "monster/out/166",
    outOffset: new Vec2(),
    label: "攻城战车怪",
    level: 1,
    description: "攻城战车怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("167", {
    icon: "monster/icon/167",
    in: "monster/in/167",
    inOffset: new Vec2(),
    out: "monster/out/167",
    outOffset: new Vec2(),
    label: "冲车机关怪",
    level: 1,
    description: "冲车机关怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("168", {
    icon: "monster/icon/168",
    in: "monster/in/168",
    inOffset: new Vec2(),
    out: "monster/out/168",
    outOffset: new Vec2(),
    label: "赤羽斗鸡",
    level: 1,
    description: "赤羽斗鸡",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("169", {
    icon: "monster/icon/169",
    in: "monster/in/169",
    inOffset: new Vec2(),
    out: "monster/out/169",
    outOffset: new Vec2(),
    label: "金斑幼鹿",
    level: 1,
    description: "金斑幼鹿",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("170", {
    icon: "monster/icon/170",
    in: "monster/in/170",
    inOffset: new Vec2(),
    out: "monster/out/170",
    outOffset: new Vec2(),
    label: "枯瘦黄衣行者",
    level: 1,
    description: "枯瘦黄衣行者",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("171", {
    icon: "monster/icon/171",
    in: "monster/in/171",
    inOffset: new Vec2(),
    out: "monster/out/171",
    outOffset: new Vec2(),
    label: "举臂长毛猿",
    level: 1,
    description: "举臂长毛猿",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("172", {
    icon: "monster/icon/172",
    in: "monster/in/172",
    inOffset: new Vec2(),
    out: "monster/out/172",
    outOffset: new Vec2(),
    label: "藤杖猴妖",
    level: 1,
    description: "藤杖猴妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("173", {
    icon: "monster/icon/173",
    in: "monster/in/173",
    inOffset: new Vec2(),
    out: "monster/out/173",
    outOffset: new Vec2(),
    label: "象鼻地獾",
    level: 1,
    description: "象鼻地獾",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("174", {
    icon: "monster/icon/174",
    in: "monster/in/174",
    inOffset: new Vec2(),
    out: "monster/out/174",
    outOffset: new Vec2(),
    label: "白骨行尸",
    level: 1,
    description: "白骨行尸",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("175", {
    icon: "monster/icon/175",
    in: "monster/in/175",
    inOffset: new Vec2(),
    out: "monster/out/175",
    outOffset: new Vec2(),
    label: "持斧骷髅卫",
    level: 1,
    description: "持斧骷髅卫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("176", {
    icon: "monster/icon/176",
    in: "monster/in/176",
    inOffset: new Vec2(),
    out: "monster/out/176",
    outOffset: new Vec2(),
    label: "持锄白毛猿",
    level: 1,
    description: "持锄白毛猿",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("177", {
    icon: "monster/icon/177",
    in: "monster/in/177",
    inOffset: new Vec2(),
    out: "monster/out/177",
    outOffset: new Vec2(),
    label: "血爪夜叉",
    level: 1,
    description: "血爪夜叉",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("178", {
    icon: "monster/icon/178",
    in: "monster/in/178",
    inOffset: new Vec2(),
    out: "monster/out/178",
    outOffset: new Vec2(),
    label: "灰甲蝼蛄",
    level: 1,
    description: "灰甲蝼蛄",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("179", {
    icon: "monster/icon/179",
    in: "monster/in/179",
    inOffset: new Vec2(),
    out: "monster/out/179",
    outOffset: new Vec2(),
    label: "金龟甲虫",
    level: 1,
    description: "金龟甲虫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("180", {
    icon: "monster/icon/180",
    in: "monster/in/180",
    inOffset: new Vec2(),
    out: "monster/out/180",
    outOffset: new Vec2(),
    label: "金翎鸟灵",
    level: 1,
    description: "金翎鸟灵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("181", {
    icon: "monster/icon/181",
    in: "monster/in/181",
    inOffset: new Vec2(),
    out: "monster/out/181",
    outOffset: new Vec2(),
    label: "黄斑腐尸",
    level: 1,
    description: "黄斑腐尸",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("182", {
    icon: "monster/icon/182",
    in: "monster/in/182",
    inOffset: new Vec2(),
    out: "monster/out/182",
    outOffset: new Vec2(),
    label: "破衲行者",
    level: 1,
    description: "破衲行者",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("183", {
    icon: "monster/icon/183",
    in: "monster/in/183",
    inOffset: new Vec2(),
    out: "monster/out/183",
    outOffset: new Vec2(),
    label: "螺蛳灰虫",
    level: 1,
    description: "螺蛳灰虫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("184", {
    icon: "monster/icon/184",
    in: "monster/in/184",
    inOffset: new Vec2(),
    out: "monster/out/184",
    outOffset: new Vec2(),
    label: "金环灵蛇",
    level: 1,
    description: "金环灵蛇",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("185", {
    icon: "monster/icon/185",
    in: "monster/in/185",
    inOffset: new Vec2(),
    out: "monster/out/185",
    outOffset: new Vec2(),
    label: "赤信蛇妖",
    level: 1,
    description: "赤信蛇妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("186", {
    icon: "monster/icon/186",
    in: "monster/in/186",
    inOffset: new Vec2(),
    out: "monster/out/186",
    outOffset: new Vec2(),
    label: "金毛鬃兽",
    level: 1,
    description: "金毛鬃兽",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("187", {
    icon: "monster/icon/187",
    in: "monster/in/187",
    inOffset: new Vec2(),
    out: "monster/out/187",
    outOffset: new Vec2(),
    label: "黄肚蛙将",
    level: 1,
    description: "黄肚蛙将",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("188", {
    icon: "monster/icon/188",
    in: "monster/in/188",
    inOffset: new Vec2(),
    out: "monster/out/188",
    outOffset: new Vec2(),
    label: "骨刺橙蜈蚣",
    level: 1,
    description: "骨刺橙蜈蚣",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("189", {
    icon: "monster/icon/189",
    in: "monster/in/189",
    inOffset: new Vec2(),
    out: "monster/out/189",
    outOffset: new Vec2(),
    label: "银角仙蜕",
    level: 1,
    description: "银角仙蜕",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("190", {
    icon: "monster/icon/190",
    in: "monster/in/190",
    inOffset: new Vec2(),
    out: "monster/out/190",
    outOffset: new Vec2(),
    label: "白骨团怪",
    level: 1,
    description: "白骨团怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("191", {
    icon: "monster/icon/191",
    in: "monster/in/191",
    inOffset: new Vec2(),
    out: "monster/out/191",
    outOffset: new Vec2(),
    label: "铁甲双钳虫",
    level: 1,
    description: "铁甲双钳虫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("192", {
    icon: "monster/icon/192",
    in: "monster/in/192",
    inOffset: new Vec2(),
    out: "monster/out/192",
    outOffset: new Vec2(),
    label: "银针骨虫",
    level: 1,
    description: "银针骨虫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("193", {
    icon: "monster/icon/193",
    in: "monster/in/193",
    inOffset: new Vec2(),
    out: "monster/out/193",
    outOffset: new Vec2(),
    label: "泥沼爬行兽",
    level: 1,
    description: "泥沼爬行兽",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("194", {
    icon: "monster/icon/194",
    in: "monster/in/194",
    inOffset: new Vec2(),
    out: "monster/out/194",
    outOffset: new Vec2(),
    label: "石肤鬼王",
    level: 1,
    description: "石肤鬼王",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("195", {
    icon: "monster/icon/195",
    in: "monster/in/195",
    inOffset: new Vec2(),
    out: "monster/out/195",
    outOffset: new Vec2(),
    label: "持叉狼妖",
    level: 1,
    description: "持叉狼妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("196", {
    icon: "monster/icon/196",
    in: "monster/in/196",
    inOffset: new Vec2(),
    out: "monster/out/196",
    outOffset: new Vec2(),
    label: "骨刺链锤魔",
    level: 1,
    description: "骨刺链锤魔",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("197", {
    icon: "monster/icon/197",
    in: "monster/in/197",
    inOffset: new Vec2(),
    out: "monster/out/197",
    outOffset: new Vec2(),
    label: "血翼魔王",
    level: 1,
    description: "血翼魔王",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("198", {
    icon: "monster/icon/198",
    in: "monster/in/198",
    inOffset: new Vec2(),
    out: "monster/out/198",
    outOffset: new Vec2(),
    label: "坠马铁骨怪",
    level: 1,
    description: "坠马铁骨怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("199", {
    icon: "monster/icon/199",
    in: "monster/in/199",
    inOffset: new Vec2(),
    out: "monster/out/199",
    outOffset: new Vec2(),
    label: "骨翼小飞龙",
    level: 1,
    description: "骨翼小飞龙",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("200", {
    icon: "monster/icon/200",
    in: "monster/in/200",
    inOffset: new Vec2(),
    out: "monster/out/200",
    outOffset: new Vec2(),
    label: "长尾跳鼠怪",
    level: 1,
    description: "长尾跳鼠怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("201", {
    icon: "monster/icon/201",
    in: "monster/in/201",
    inOffset: new Vec2(),
    out: "monster/out/201",
    outOffset: new Vec2(),
    label: "白骨弓手",
    level: 1,
    description: "白骨弓手",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("202", {
    icon: "monster/icon/202",
    in: "monster/in/202",
    inOffset: new Vec2(),
    out: "monster/out/202",
    outOffset: new Vec2(),
    label: "铁甲长戟卫",
    level: 1,
    description: "铁甲长戟卫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("203", {
    icon: "monster/icon/203",
    in: "monster/in/203",
    inOffset: new Vec2(),
    out: "monster/out/203",
    outOffset: new Vec2(),
    label: "断臂独锤兵",
    level: 1,
    description: "断臂独锤兵",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("204", {
    icon: "monster/icon/204",
    in: "monster/in/204",
    inOffset: new Vec2(),
    out: "monster/out/204",
    outOffset: new Vec2(),
    label: "红肤举锤巨人",
    level: 1,
    description: "红肤举锤巨人",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("205", {
    icon: "monster/icon/205",
    in: "monster/in/205",
    inOffset: new Vec2(),
    out: "monster/out/205",
    outOffset: new Vec2(),
    label: "狼头黑锤妖",
    level: 1,
    description: "狼头黑锤妖",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("206", {
    icon: "monster/icon/206",
    in: "monster/in/206",
    inOffset: new Vec2(),
    out: "monster/out/206",
    outOffset: new Vec2(),
    label: "铁节钢蜈蚣",
    level: 1,
    description: "铁节钢蜈蚣",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("207", {
    icon: "monster/icon/207",
    in: "monster/in/207",
    inOffset: new Vec2(),
    out: "monster/out/207",
    outOffset: new Vec2(),
    label: "雪白羊怪",
    level: 1,
    description: "雪白羊怪",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("208", {
    icon: "monster/icon/208",
    in: "monster/in/208",
    inOffset: new Vec2(),
    out: "monster/out/208",
    outOffset: new Vec2(),
    label: "荆棘刺球兽",
    level: 1,
    description: "荆棘刺球兽",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("209", {
    icon: "monster/icon/209",
    in: "monster/in/209",
    inOffset: new Vec2(),
    out: "monster/out/209",
    outOffset: new Vec2(),
    label: "土黄瘦狐",
    level: 1,
    description: "土黄瘦狐",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("210", {
    icon: "monster/icon/210",
    in: "monster/in/210",
    inOffset: new Vec2(),
    out: "monster/out/210",
    outOffset: new Vec2(),
    label: "白袍布衣道人",
    level: 1,
    description: "白袍布衣道人",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("211", {
    icon: "monster/icon/211",
    in: "monster/in/211",
    inOffset: new Vec2(),
    out: "monster/out/211",
    outOffset: new Vec2(),
    label: "血背金龟虫",
    level: 1,
    description: "血背金龟虫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("212", {
    icon: "monster/icon/212",
    in: "monster/in/212",
    inOffset: new Vec2(),
    out: "monster/out/212",
    outOffset: new Vec2(),
    label: "青绿毛毛虫",
    level: 1,
    description: "青绿毛毛虫",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("213", {
    icon: "monster/icon/213",
    in: "monster/in/213",
    inOffset: new Vec2(),
    out: "monster/out/213",
    outOffset: new Vec2(),
    label: "白骨腐尸",
    level: 1,
    description: "白骨腐尸",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("214", {
    icon: "monster/icon/214",
    in: "monster/in/214",
    inOffset: new Vec2(),
    out: "monster/out/214",
    outOffset: new Vec2(),
    label: "铁尾黑蝎",
    level: 1,
    description: "铁尾黑蝎",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("215", {
    icon: "monster/icon/215",
    in: "monster/in/215",
    inOffset: new Vec2(),
    out: "monster/out/215",
    outOffset: new Vec2(),
    label: "褐翼黑蝙蝠",
    level: 1,
    description: "褐翼黑蝙蝠",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("216", {
    icon: "monster/icon/216",
    in: "monster/in/216",
    inOffset: new Vec2(),
    out: "monster/out/216",
    outOffset: new Vec2(),
    label: "银斧圆盾矮人",
    level: 1,
    description: "银斧圆盾矮人",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("217", {
    icon: "monster/icon/217",
    in: "monster/in/217",
    inOffset: new Vec2(),
    out: "monster/out/217",
    outOffset: new Vec2(),
    label: "绿皮蟾人",
    level: 1,
    description: "绿皮蟾人",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("218", {
    icon: "monster/icon/218",
    in: "monster/in/218",
    inOffset: new Vec2(),
    out: "monster/out/218",
    outOffset: new Vec2(),
    label: "金鬃狻猊",
    level: 1,
    description: "金鬃狻猊",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("219", {
    icon: "monster/icon/219",
    in: "monster/in/219",
    inOffset: new Vec2(),
    out: "monster/out/219",
    outOffset: new Vec2(),
    label: "铁钩海盗",
    level: 1,
    description: "铁钩海盗",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});
monsters.set("220", {
    icon: "monster/icon/220",
    in: "monster/in/220",
    inOffset: new Vec2(),
    out: "monster/out/220",
    outOffset: new Vec2(),
    label: "牛角石肤巨人",
    level: 1,
    description: "牛角石肤巨人",
    sellPirce: 0,
    physicalAttack: [0, 1],
    magicAttack: [0, 0],
    taoistAttack: [0, 0],
    physicalDefense: [0, 0],
    magicDefense: [0, 0],
    taoistDefense: [0, 0],
    maxHp: 10,
});

export default monsters;